// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0025.rs");
static MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "FLASH",
        kind: MemoryKind::Flash,
        address: 0,
        size: 262144,
        retained_through: PowerMode::Shutdown,
    },
    MemoryRegion {
        name: "RAM",
        kind: MemoryKind::Ram,
        address: 538968064,
        size: 65536,
        retained_through: PowerMode::Standby,
    },
    MemoryRegion {
        name: "RAM_BANK",
        kind: MemoryKind::Ram,
        address: 539033600,
        size: 65536,
        retained_through: PowerMode::Sleep,
    },
];
pub static METADATA: Metadata = Metadata {
    name: "mspm0g1518pt",
    family: "mspm0g151x",
    memory: MEMORY,
    peripherals: PERIPHERALS,
    pins: PINS,
    nvic_priority_bits: 2,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 12,
    adc_vrsel: 5,
    max_mclk_hz: 80000000,
    max_ulpclk_hz: 40000000,
    backup_domain: false,
};
