// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#[cfg(feature = "rt")]
pub const NVIC_PRIO_BITS: u8 = 2;
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Interrupt {
    SYSCTL = 0,
    DEBUGSS = 1,
    UC6 = 3,
    ADC0 = 4,
    TIMB0 = 5,
    TIMB1 = 6,
    COMP0 = 7,
    UC7 = 8,
    UC8 = 9,
    TIMB2 = 13,
    TIMB3 = 14,
    UC4 = 15,
    TIMG14 = 16,
    TIMG2 = 17,
    TIMA0 = 18,
    TIMG1 = 19,
    GPIOA = 22,
    GPIOB = 23,
    UC11 = 24,
    AESADV = 26,
    FLASHCTL = 27,
    WWDT0 = 29,
    LFSS = 30,
    DMA = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[cfg(feature = "rt")]
mod _vectors {
    extern "C" {
        fn NonMaskableInt();
        fn HardFault();
        fn SVCall();
        fn PendSV();
        fn SysTick();
        fn SYSCTL();
        fn DEBUGSS();
        fn UC6();
        fn ADC0();
        fn TIMB0();
        fn TIMB1();
        fn COMP0();
        fn UC7();
        fn UC8();
        fn TIMB2();
        fn TIMB3();
        fn UC4();
        fn TIMG14();
        fn TIMG2();
        fn TIMA0();
        fn TIMG1();
        fn GPIOA();
        fn GPIOB();
        fn UC11();
        fn AESADV();
        fn FLASHCTL();
        fn WWDT0();
        fn LFSS();
        fn DMA();
    }
    #[repr(C)]
    pub union Vector {
        _handler: unsafe extern "C" fn(),
        _reserved: u32,
    }
    #[link_section = ".vector_table.interrupts"]
    #[no_mangle]
    pub static __INTERRUPTS: [Vector; 32] = [
        Vector { _handler: SYSCTL },
        Vector { _handler: DEBUGSS },
        Vector { _reserved: 0 },
        Vector { _handler: UC6 },
        Vector { _handler: ADC0 },
        Vector { _handler: TIMB0 },
        Vector { _handler: TIMB1 },
        Vector { _handler: COMP0 },
        Vector { _handler: UC7 },
        Vector { _handler: UC8 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _handler: TIMB2 },
        Vector { _handler: TIMB3 },
        Vector { _handler: UC4 },
        Vector { _handler: TIMG14 },
        Vector { _handler: TIMG2 },
        Vector { _handler: TIMA0 },
        Vector { _handler: TIMG1 },
        Vector { _reserved: 0 },
        Vector { _reserved: 0 },
        Vector { _handler: GPIOA },
        Vector { _handler: GPIOB },
        Vector { _handler: UC11 },
        Vector { _reserved: 0 },
        Vector { _handler: AESADV },
        Vector { _handler: FLASHCTL },
        Vector { _reserved: 0 },
        Vector { _handler: WWDT0 },
        Vector { _handler: LFSS },
        Vector { _handler: DMA },
    ];
}
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[cfg(feature = "rt")]
pub use Interrupt as interrupt;
#[path = "../../peripherals/adc_v1.rs"]
pub mod adc;
#[path = "../../peripherals/cpuss_v1.rs"]
pub mod cpuss;
#[path = "../../peripherals/dma_v1.rs"]
pub mod dma;
#[path = "../../peripherals/factoryregion_v1.rs"]
pub mod factoryregion;
#[path = "../../peripherals/flashctl_v1.rs"]
pub mod flashctl;
#[path = "../../peripherals/gpio_v1.rs"]
pub mod gpio;
#[path = "../../peripherals/iomux_v1.rs"]
pub mod iomux;
#[path = "../../peripherals/sysctl_l122x_l222x.rs"]
pub mod sysctl;
#[path = "../../peripherals/tim_v1.rs"]
pub mod tim;
#[path = "../../peripherals/tim_btimer.rs"]
pub mod timb;
#[path = "../../peripherals/unicomm_v1.rs"]
pub mod unicomm;
#[path = "../../peripherals/unicommi2cc_v1.rs"]
pub mod unicommi2cc;
#[path = "../../peripherals/unicommi2ct_v1.rs"]
pub mod unicommi2ct;
#[path = "../../peripherals/unicommspi_v1.rs"]
pub mod unicommspi;
#[path = "../../peripherals/unicommuart_v1.rs"]
pub mod unicommuart;
#[path = "../../peripherals/vref_v1.rs"]
pub mod vref;
#[path = "../../peripherals/wwdt_v1.rs"]
pub mod wwdt;
pub const ADC0: adc::Adc = unsafe { adc::Adc::from_ptr(1073758208 as *mut _) };
#[doc = "Address: 1078206464"]
pub const AESADV: () = ();
#[doc = "Address: 1073774592"]
pub const COMP0: () = ();
pub const CPUSS: cpuss::Cpuss = unsafe { cpuss::Cpuss::from_ptr(1077936128 as *mut _) };
#[doc = "Address: 1078198272"]
pub const CRC0: () = ();
#[doc = "Address: 1074556928"]
pub const DEBUGSS: () = ();
pub const DMA: dma::Dma = unsafe { dma::Dma::from_ptr(1078108160 as *mut _) };
#[doc = "Address: 1074565120"]
pub const EVENT: () = ();
pub const FACTORYREGION: factoryregion::Factoryregion =
    unsafe { factoryregion::Factoryregion::from_ptr(1103364096 as *mut _) };
pub const FLASHCTL: flashctl::Flashctl =
    unsafe { flashctl::Flashctl::from_ptr(1074581504 as *mut _) };
pub const GPIOA: gpio::Gpio = unsafe { gpio::Gpio::from_ptr(1074397184 as *mut _) };
pub const GPIOB: gpio::Gpio = unsafe { gpio::Gpio::from_ptr(1074405376 as *mut _) };
pub const IOMUX: iomux::Iomux = unsafe { iomux::Iomux::from_ptr(1078099968 as *mut _) };
#[doc = "Address: 1074348032"]
pub const IWDT: () = ();
#[doc = "Address: 1074446336"]
pub const KEYSTORECTL: () = ();
#[doc = "Address: 1074348032"]
pub const LFSS: () = ();
#[doc = "Address: 1074348032"]
pub const RTC_B: () = ();
#[doc = "Address: 1084878848"]
pub const SPG0: () = ();
pub const SYSCTL: sysctl::Sysctl = unsafe { sysctl::Sysctl::from_ptr(1074458624 as *mut _) };
pub const TIMA0: tim::Tim = unsafe { tim::Tim::from_ptr(1082523648 as *mut _) };
pub const TIMB0: timb::Tim = unsafe { timb::Tim::from_ptr(1074495488 as *mut _) };
pub const TIMB1: timb::Tim = unsafe { timb::Tim::from_ptr(1074503680 as *mut _) };
pub const TIMB2: timb::Tim = unsafe { timb::Tim::from_ptr(1074511872 as *mut _) };
pub const TIMB3: timb::Tim = unsafe { timb::Tim::from_ptr(1074520064 as *mut _) };
pub const TIMG1: tim::Tim = unsafe { tim::Tim::from_ptr(1074290688 as *mut _) };
pub const TIMG14: tim::Tim = unsafe { tim::Tim::from_ptr(1074282496 as *mut _) };
pub const TIMG2: tim::Tim = unsafe { tim::Tim::from_ptr(1074298880 as *mut _) };
pub const UC11: unicomm::Unicomm = unsafe { unicomm::Unicomm::from_ptr(1085808640 as *mut _) };
pub const UC11_UART: unicommuart::Unicommuart =
    unsafe { unicommuart::Unicommuart::from_ptr(1085284352 as *mut _) };
pub const UC4: unicomm::Unicomm = unsafe { unicomm::Unicomm::from_ptr(1084751872 as *mut _) };
pub const UC4_SPI: unicommspi::Unicommspi =
    unsafe { unicommspi::Unicommspi::from_ptr(1084620800 as *mut _) };
pub const UC4_UART: unicommuart::Unicommuart =
    unsafe { unicommuart::Unicommuart::from_ptr(1084227584 as *mut _) };
pub const UC6: unicomm::Unicomm = unsafe { unicomm::Unicomm::from_ptr(1084760064 as *mut _) };
pub const UC6_I2CC: unicommi2cc::Unicommi2cc =
    unsafe { unicommi2cc::Unicommi2cc::from_ptr(1084366848 as *mut _) };
pub const UC7: unicomm::Unicomm = unsafe { unicomm::Unicomm::from_ptr(1084768256 as *mut _) };
pub const UC7_I2CT: unicommi2ct::Unicommi2ct =
    unsafe { unicommi2ct::Unicommi2ct::from_ptr(1084506112 as *mut _) };
pub const UC8: unicomm::Unicomm = unsafe { unicomm::Unicomm::from_ptr(1085800448 as *mut _) };
pub const UC8_SPI: unicommspi::Unicommspi =
    unsafe { unicommspi::Unicommspi::from_ptr(1085669376 as *mut _) };
pub const UC8_UART: unicommuart::Unicommuart =
    unsafe { unicommuart::Unicommuart::from_ptr(1085276160 as *mut _) };
pub const VREF: vref::Vref = unsafe { vref::Vref::from_ptr(1073938432 as *mut _) };
#[doc = "Address: 1078083584"]
pub const WUC: () = ();
pub const WWDT0: wwdt::Wwdt = unsafe { wwdt::Wwdt::from_ptr(1074266112 as *mut _) };
