// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
///PERIPHERALREGION.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Comp {
    ptr: *mut u8,
}
unsafe impl Send for Comp {}
unsafe impl Sync for Comp {}
impl Comp {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Subscriber Configuration Register.
    #[inline(always)]
    pub const fn fsub(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        assert!(n < 2usize);
        unsafe {
            crate::common::Reg::from_ptr(
                self.ptr.wrapping_add(0x0400usize + n * 4usize) as _,
            )
        }
    }
    ///Publisher Configuration Register.
    #[inline(always)]
    pub const fn fpub(self) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0444usize) as _) }
    }
    #[inline(always)]
    pub const fn gprcm(self, n: usize) -> Gprcm {
        assert!(n < 1usize);
        unsafe { Gprcm::from_ptr(self.ptr.wrapping_add(0x0800usize + n * 24usize) as _) }
    }
    #[inline(always)]
    pub const fn cpu_int(self, n: usize) -> CpuInt {
        assert!(n < 1usize);
        unsafe {
            CpuInt::from_ptr(self.ptr.wrapping_add(0x1020usize + n * 44usize) as _)
        }
    }
    #[inline(always)]
    pub const fn gen_event(self, n: usize) -> GenEvent {
        assert!(n < 1usize);
        unsafe {
            GenEvent::from_ptr(self.ptr.wrapping_add(0x1050usize + n * 44usize) as _)
        }
    }
    ///Event Mode.
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e0usize) as _) }
    }
    ///Module Description.
    #[inline(always)]
    pub const fn desc(self) -> crate::common::Reg<regs::Desc, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10fcusize) as _) }
    }
    ///Control 0.
    #[inline(always)]
    pub const fn ctl0(self) -> crate::common::Reg<regs::Ctl0, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1100usize) as _) }
    }
    ///Control 1.
    #[inline(always)]
    pub const fn ctl1(self) -> crate::common::Reg<regs::Ctl1, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1104usize) as _) }
    }
    ///Control 2.
    #[inline(always)]
    pub const fn ctl2(self) -> crate::common::Reg<regs::Ctl2, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1108usize) as _) }
    }
    ///Control 3.
    #[inline(always)]
    pub const fn ctl3(self) -> crate::common::Reg<regs::Ctl3, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x110cusize) as _) }
    }
    ///Status.
    #[inline(always)]
    pub const fn stat(self) -> crate::common::Reg<regs::Stat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1120usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CpuInt {
    ptr: *mut u8,
}
unsafe impl Send for CpuInt {}
unsafe impl Sync for CpuInt {}
impl CpuInt {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct GenEvent {
    ptr: *mut u8,
}
unsafe impl Send for GenEvent {}
unsafe impl Sync for GenEvent {}
impl GenEvent {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Gprcm {
    ptr: *mut u8,
}
unsafe impl Send for Gprcm {}
unsafe impl Sync for Gprcm {}
impl Gprcm {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Power enable.
    #[inline(always)]
    pub const fn pwren(self) -> crate::common::Reg<regs::Pwren, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Reset Control.
    #[inline(always)]
    pub const fn rstctl(self) -> crate::common::Reg<regs::Rstctl, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///Peripheral Clock Configuration Register.
    #[inline(always)]
    pub const fn clkcfg(self) -> crate::common::Reg<regs::Clkcfg, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Status Register.
    #[inline(always)]
    pub const fn gprcm_stat(
        self,
    ) -> crate::common::Reg<regs::GprcmStat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
    }
}
pub mod regs {
    ///Peripheral Clock Configuration Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Clkcfg(pub u32);
    impl Clkcfg {
        ///Async Clock Request is blocked from starting SYSOSC or forcing bus clock to 32MHz.
        #[must_use]
        #[inline(always)]
        pub const fn blockasync(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///Async Clock Request is blocked from starting SYSOSC or forcing bus clock to 32MHz.
        #[inline(always)]
        pub const fn set_blockasync(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        ///KEY to Allow State Change A9h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::ClkcfgKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::ClkcfgKey::from_bits(val as u8)
        }
        ///KEY to Allow State Change A9h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::ClkcfgKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Clkcfg {
        #[inline(always)]
        fn default() -> Clkcfg {
            Clkcfg(0)
        }
    }
    impl core::fmt::Debug for Clkcfg {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Clkcfg")
                .field("blockasync", &self.blockasync())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Clkcfg {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Clkcfg {{ blockasync: {=bool:?}, key: {:?} }}", self.blockasync(),
                self.key()
            )
        }
    }
    ///Control 0.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl0(pub u32);
    impl Ctl0 {
        ///Channel input selected for the positive terminal of the comparator if IPEN is set to 1.
        #[must_use]
        #[inline(always)]
        pub const fn ipsel(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x07;
            val as u8
        }
        ///Channel input selected for the positive terminal of the comparator if IPEN is set to 1.
        #[inline(always)]
        pub const fn set_ipsel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize);
        }
        ///Channel input enable for the positive terminal of the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn ipen(&self) -> bool {
            let val = (self.0 >> 15usize) & 0x01;
            val != 0
        }
        ///Channel input enable for the positive terminal of the comparator.
        #[inline(always)]
        pub const fn set_ipen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize);
        }
        ///Channel input selected for the negative terminal of the comparator if IMEN is set to 1.
        #[must_use]
        #[inline(always)]
        pub const fn imsel(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0x07;
            val as u8
        }
        ///Channel input selected for the negative terminal of the comparator if IMEN is set to 1.
        #[inline(always)]
        pub const fn set_imsel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize);
        }
        ///Channel input enable for the negative terminal of the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn imen(&self) -> bool {
            let val = (self.0 >> 31usize) & 0x01;
            val != 0
        }
        ///Channel input enable for the negative terminal of the comparator.
        #[inline(always)]
        pub const fn set_imen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize);
        }
    }
    impl Default for Ctl0 {
        #[inline(always)]
        fn default() -> Ctl0 {
            Ctl0(0)
        }
    }
    impl core::fmt::Debug for Ctl0 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl0")
                .field("ipsel", &self.ipsel())
                .field("ipen", &self.ipen())
                .field("imsel", &self.imsel())
                .field("imen", &self.imen())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl0 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl0 {{ ipsel: {=u8:?}, ipen: {=bool:?}, imsel: {=u8:?}, imen: {=bool:?} }}",
                self.ipsel(), self.ipen(), self.imsel(), self.imen()
            )
        }
    }
    ///Control 1.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl1(pub u32);
    impl Ctl1 {
        ///This bit turns on the comparator. When the comparator is turned off it consumes no power.
        #[must_use]
        #[inline(always)]
        pub const fn enable(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///This bit turns on the comparator. When the comparator is turned off it consumes no power.
        #[inline(always)]
        pub const fn set_enable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///This bit selects the comparator operating mode.
        #[must_use]
        #[inline(always)]
        pub const fn mode(&self) -> super::vals::Mode {
            let val = (self.0 >> 1usize) & 0x01;
            super::vals::Mode::from_bits(val as u8)
        }
        ///This bit selects the comparator operating mode.
        #[inline(always)]
        pub const fn set_mode(&mut self, val: super::vals::Mode) {
            self.0 = (self.0 & !(0x01 << 1usize))
                | (((val.to_bits() as u32) & 0x01) << 1usize);
        }
        ///This bit exchanges the comparator inputs and inverts the comparator output.
        #[must_use]
        #[inline(always)]
        pub const fn exch(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///This bit exchanges the comparator inputs and inverts the comparator output.
        #[inline(always)]
        pub const fn set_exch(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///This bit shorts the positive and negative input terminals of the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn short(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///This bit shorts the positive and negative input terminals of the comparator.
        #[inline(always)]
        pub const fn set_short(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///This bit selected the interrupt edge for COMPIFG and COMPINVIFG.
        #[must_use]
        #[inline(always)]
        pub const fn ies(&self) -> super::vals::Ies {
            let val = (self.0 >> 4usize) & 0x01;
            super::vals::Ies::from_bits(val as u8)
        }
        ///This bit selected the interrupt edge for COMPIFG and COMPINVIFG.
        #[inline(always)]
        pub const fn set_ies(&mut self, val: super::vals::Ies) {
            self.0 = (self.0 & !(0x01 << 4usize))
                | (((val.to_bits() as u32) & 0x01) << 4usize);
        }
        ///These bits select the hysteresis setting of the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn hyst(&self) -> super::vals::Hyst {
            let val = (self.0 >> 5usize) & 0x03;
            super::vals::Hyst::from_bits(val as u8)
        }
        ///These bits select the hysteresis setting of the comparator.
        #[inline(always)]
        pub const fn set_hyst(&mut self, val: super::vals::Hyst) {
            self.0 = (self.0 & !(0x03 << 5usize))
                | (((val.to_bits() as u32) & 0x03) << 5usize);
        }
        ///This bit selects the comparator output polarity.
        #[must_use]
        #[inline(always)]
        pub const fn outpol(&self) -> super::vals::Outpol {
            let val = (self.0 >> 7usize) & 0x01;
            super::vals::Outpol::from_bits(val as u8)
        }
        ///This bit selects the comparator output polarity.
        #[inline(always)]
        pub const fn set_outpol(&mut self, val: super::vals::Outpol) {
            self.0 = (self.0 & !(0x01 << 7usize))
                | (((val.to_bits() as u32) & 0x01) << 7usize);
        }
        ///This bit enables the analog filter at comparator output.
        #[must_use]
        #[inline(always)]
        pub const fn flten(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///This bit enables the analog filter at comparator output.
        #[inline(always)]
        pub const fn set_flten(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        ///These bits select the comparator output filter delay. See the device-specific data sheet for specific values on comparator propagation delay for different filter delay settings.
        #[must_use]
        #[inline(always)]
        pub const fn fltdly(&self) -> super::vals::Fltdly {
            let val = (self.0 >> 9usize) & 0x03;
            super::vals::Fltdly::from_bits(val as u8)
        }
        ///These bits select the comparator output filter delay. See the device-specific data sheet for specific values on comparator propagation delay for different filter delay settings.
        #[inline(always)]
        pub const fn set_fltdly(&mut self, val: super::vals::Fltdly) {
            self.0 = (self.0 & !(0x03 << 9usize))
                | (((val.to_bits() as u32) & 0x03) << 9usize);
        }
        ///This bit enables DAC8 output to be connected to the pin.
        #[must_use]
        #[inline(always)]
        pub const fn dacouten(&self) -> bool {
            let val = (self.0 >> 11usize) & 0x01;
            val != 0
        }
        ///This bit enables DAC8 output to be connected to the pin.
        #[inline(always)]
        pub const fn set_dacouten(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize);
        }
        ///This bit enables window comparator operation of comparator.
        #[must_use]
        #[inline(always)]
        pub const fn wincompen(&self) -> bool {
            let val = (self.0 >> 12usize) & 0x01;
            val != 0
        }
        ///This bit enables window comparator operation of comparator.
        #[inline(always)]
        pub const fn set_wincompen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize);
        }
    }
    impl Default for Ctl1 {
        #[inline(always)]
        fn default() -> Ctl1 {
            Ctl1(0)
        }
    }
    impl core::fmt::Debug for Ctl1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl1")
                .field("enable", &self.enable())
                .field("mode", &self.mode())
                .field("exch", &self.exch())
                .field("short", &self.short())
                .field("ies", &self.ies())
                .field("hyst", &self.hyst())
                .field("outpol", &self.outpol())
                .field("flten", &self.flten())
                .field("fltdly", &self.fltdly())
                .field("dacouten", &self.dacouten())
                .field("wincompen", &self.wincompen())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl1 {{ enable: {=bool:?}, mode: {:?}, exch: {=bool:?}, short: {=bool:?}, ies: {:?}, hyst: {:?}, outpol: {:?}, flten: {=bool:?}, fltdly: {:?}, dacouten: {=bool:?}, wincompen: {=bool:?} }}",
                self.enable(), self.mode(), self.exch(), self.short(), self.ies(), self
                .hyst(), self.outpol(), self.flten(), self.fltdly(), self.dacouten(),
                self.wincompen()
            )
        }
    }
    ///Control 2.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl2(pub u32);
    impl Ctl2 {
        ///This bit requests ULP_REF bandgap operation in fast mode(static) or low power mode (sampled). The local reference buffer and 8-bit DAC inside comparator module are also configured accordingly. Fast mode operation offers higher accuracy but consumes higher current. Low power operation consumes lower current but with relaxed reference voltage accuracy. Comparator requests for reference voltage from ULP_REF only when REFLVL > 0.
        #[must_use]
        #[inline(always)]
        pub const fn refmode(&self) -> super::vals::Refmode {
            let val = (self.0 >> 0usize) & 0x01;
            super::vals::Refmode::from_bits(val as u8)
        }
        ///This bit requests ULP_REF bandgap operation in fast mode(static) or low power mode (sampled). The local reference buffer and 8-bit DAC inside comparator module are also configured accordingly. Fast mode operation offers higher accuracy but consumes higher current. Low power operation consumes lower current but with relaxed reference voltage accuracy. Comparator requests for reference voltage from ULP_REF only when REFLVL > 0.
        #[inline(always)]
        pub const fn set_refmode(&mut self, val: super::vals::Refmode) {
            self.0 = (self.0 & !(0x01 << 0usize))
                | (((val.to_bits() as u32) & 0x01) << 0usize);
        }
        ///These bits select the reference source for the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn refsrc(&self) -> super::vals::Refsrc {
            let val = (self.0 >> 3usize) & 0x07;
            super::vals::Refsrc::from_bits(val as u8)
        }
        ///These bits select the reference source for the comparator.
        #[inline(always)]
        pub const fn set_refsrc(&mut self, val: super::vals::Refsrc) {
            self.0 = (self.0 & !(0x07 << 3usize))
                | (((val.to_bits() as u32) & 0x07) << 3usize);
        }
        ///This bit selects if the selected reference voltage is applied to positive or negative terminal of the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn refsel(&self) -> super::vals::Refsel {
            let val = (self.0 >> 7usize) & 0x01;
            super::vals::Refsel::from_bits(val as u8)
        }
        ///This bit selects if the selected reference voltage is applied to positive or negative terminal of the comparator.
        #[inline(always)]
        pub const fn set_refsel(&mut self, val: super::vals::Refsel) {
            self.0 = (self.0 & !(0x01 << 7usize))
                | (((val.to_bits() as u32) & 0x01) << 7usize);
        }
        ///These bits select the blanking source for the comparator.
        #[must_use]
        #[inline(always)]
        pub const fn blanksrc(&self) -> super::vals::Blanksrc {
            let val = (self.0 >> 8usize) & 0x07;
            super::vals::Blanksrc::from_bits(val as u8)
        }
        ///These bits select the blanking source for the comparator.
        #[inline(always)]
        pub const fn set_blanksrc(&mut self, val: super::vals::Blanksrc) {
            self.0 = (self.0 & !(0x07 << 8usize))
                | (((val.to_bits() as u32) & 0x07) << 8usize);
        }
        ///This bit determines if the comparator output or DACSW bit controls the selection between DACCODE0 and DACCODE1.
        #[must_use]
        #[inline(always)]
        pub const fn dacctl(&self) -> super::vals::Dacctl {
            let val = (self.0 >> 16usize) & 0x01;
            super::vals::Dacctl::from_bits(val as u8)
        }
        ///This bit determines if the comparator output or DACSW bit controls the selection between DACCODE0 and DACCODE1.
        #[inline(always)]
        pub const fn set_dacctl(&mut self, val: super::vals::Dacctl) {
            self.0 = (self.0 & !(0x01 << 16usize))
                | (((val.to_bits() as u32) & 0x01) << 16usize);
        }
        ///This bit selects between DACCODE0 and DACCODE1 to 8-bit DAC when DACCTL bit is 1.
        #[must_use]
        #[inline(always)]
        pub const fn dacsw(&self) -> super::vals::Dacsw {
            let val = (self.0 >> 17usize) & 0x01;
            super::vals::Dacsw::from_bits(val as u8)
        }
        ///This bit selects between DACCODE0 and DACCODE1 to 8-bit DAC when DACCTL bit is 1.
        #[inline(always)]
        pub const fn set_dacsw(&mut self, val: super::vals::Dacsw) {
            self.0 = (self.0 & !(0x01 << 17usize))
                | (((val.to_bits() as u32) & 0x01) << 17usize);
        }
        ///Enable sampled mode of comparator.
        #[must_use]
        #[inline(always)]
        pub const fn sampmode(&self) -> bool {
            let val = (self.0 >> 24usize) & 0x01;
            val != 0
        }
        ///Enable sampled mode of comparator.
        #[inline(always)]
        pub const fn set_sampmode(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize);
        }
    }
    impl Default for Ctl2 {
        #[inline(always)]
        fn default() -> Ctl2 {
            Ctl2(0)
        }
    }
    impl core::fmt::Debug for Ctl2 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl2")
                .field("refmode", &self.refmode())
                .field("refsrc", &self.refsrc())
                .field("refsel", &self.refsel())
                .field("blanksrc", &self.blanksrc())
                .field("dacctl", &self.dacctl())
                .field("dacsw", &self.dacsw())
                .field("sampmode", &self.sampmode())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl2 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl2 {{ refmode: {:?}, refsrc: {:?}, refsel: {:?}, blanksrc: {:?}, dacctl: {:?}, dacsw: {:?}, sampmode: {=bool:?} }}",
                self.refmode(), self.refsrc(), self.refsel(), self.blanksrc(), self
                .dacctl(), self.dacsw(), self.sampmode()
            )
        }
    }
    ///Control 3.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl3(pub u32);
    impl Ctl3 {
        ///The two 8-bit DAC codes; DACCTL and DACSW select which one drives the DAC. When the code is 0x0 the DAC output is the selected reference voltage x 1/256 V, and when it is 0xFF, x 255/256 V.
        #[must_use]
        #[inline(always)]
        pub const fn daccode(&self, n: usize) -> u8 {
            assert!(n < 2usize);
            let offs = 0usize + n * 16usize;
            let val = (self.0 >> offs) & 0xff;
            val as u8
        }
        ///The two 8-bit DAC codes; DACCTL and DACSW select which one drives the DAC. When the code is 0x0 the DAC output is the selected reference voltage x 1/256 V, and when it is 0xFF, x 255/256 V.
        #[inline(always)]
        pub const fn set_daccode(&mut self, n: usize, val: u8) {
            assert!(n < 2usize);
            let offs = 0usize + n * 16usize;
            self.0 = (self.0 & !(0xff << offs)) | (((val as u32) & 0xff) << offs);
        }
    }
    impl Default for Ctl3 {
        #[inline(always)]
        fn default() -> Ctl3 {
            Ctl3(0)
        }
    }
    impl core::fmt::Debug for Ctl3 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl3")
                .field("daccode[0]", &self.daccode(0usize))
                .field("daccode[1]", &self.daccode(1usize))
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl3 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Ctl3 {{ daccode[0]: {=u8:?}, daccode[1]: {=u8:?} }}", self
                .daccode(0usize), self.daccode(1usize)
            )
        }
    }
    ///Module Description.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Desc(pub u32);
    impl Desc {
        ///Minor rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn minrev(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///Minor rev of the IP.
        #[inline(always)]
        pub const fn set_minrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
        ///Major rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn majrev(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x0f;
            val as u8
        }
        ///Major rev of the IP.
        #[inline(always)]
        pub const fn set_majrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize);
        }
        ///Feature Set for the module *instance*.
        #[must_use]
        #[inline(always)]
        pub const fn featurever(&self) -> u8 {
            let val = (self.0 >> 12usize) & 0x0f;
            val as u8
        }
        ///Feature Set for the module *instance*.
        #[inline(always)]
        pub const fn set_featurever(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize);
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[must_use]
        #[inline(always)]
        pub const fn moduleid(&self) -> u16 {
            let val = (self.0 >> 16usize) & 0xffff;
            val as u16
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[inline(always)]
        pub const fn set_moduleid(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 16usize))
                | (((val as u32) & 0xffff) << 16usize);
        }
    }
    impl Default for Desc {
        #[inline(always)]
        fn default() -> Desc {
            Desc(0)
        }
    }
    impl core::fmt::Debug for Desc {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Desc")
                .field("minrev", &self.minrev())
                .field("majrev", &self.majrev())
                .field("featurever", &self.featurever())
                .field("moduleid", &self.moduleid())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Desc {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Desc {{ minrev: {=u8:?}, majrev: {=u8:?}, featurever: {=u8:?}, moduleid: {=u16:?} }}",
                self.minrev(), self.majrev(), self.featurever(), self.moduleid()
            )
        }
    }
    ///Event Mode.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        ///Event line mode select for event corresponding to CPU_INT.
        #[must_use]
        #[inline(always)]
        pub const fn cpu(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to CPU_INT.
        #[inline(always)]
        pub const fn set_cpu(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 0usize))
                | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
        ///Event line mode select for event corresponding to GEN_EVENT.
        #[must_use]
        #[inline(always)]
        pub const fn gen_event(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 2usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to GEN_EVENT.
        #[inline(always)]
        pub const fn set_gen_event(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 2usize))
                | (((val.to_bits() as u32) & 0x03) << 2usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    impl core::fmt::Debug for EvtMode {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("EvtMode")
                .field("cpu", &self.cpu())
                .field("gen_event", &self.gen_event())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for EvtMode {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "EvtMode {{ cpu: {:?}, gen_event: {:?} }}", self.cpu(), self
                .gen_event()
            )
        }
    }
    ///Event subscriber/publisher channel selection.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Fport(pub u32);
    impl Fport {
        ///0 = disconnected. 1-15 = connected to channelID = CHANID.
        #[must_use]
        #[inline(always)]
        pub const fn chanid(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///0 = disconnected. 1-15 = connected to channelID = CHANID.
        #[inline(always)]
        pub const fn set_chanid(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
    }
    impl Default for Fport {
        #[inline(always)]
        fn default() -> Fport {
            Fport(0)
        }
    }
    impl core::fmt::Debug for Fport {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Fport").field("chanid", &self.chanid()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Fport {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Fport {{ chanid: {=u8:?} }}", self.chanid())
        }
    }
    ///Status Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct GprcmStat(pub u32);
    impl GprcmStat {
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstky(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[inline(always)]
        pub const fn set_resetstky(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for GprcmStat {
        #[inline(always)]
        fn default() -> GprcmStat {
            GprcmStat(0)
        }
    }
    impl core::fmt::Debug for GprcmStat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("GprcmStat").field("resetstky", &self.resetstky()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for GprcmStat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "GprcmStat {{ resetstky: {=bool:?} }}", self.resetstky())
        }
    }
    ///Interrupt index.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Iidx(pub u32);
    impl Iidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::IidxStat {
            let val = (self.0 >> 0usize) & 0x07;
            super::vals::IidxStat::from_bits(val as u8)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::IidxStat) {
            self.0 = (self.0 & !(0x07 << 0usize))
                | (((val.to_bits() as u32) & 0x07) << 0usize);
        }
    }
    impl Default for Iidx {
        #[inline(always)]
        fn default() -> Iidx {
            Iidx(0)
        }
    }
    impl core::fmt::Debug for Iidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Iidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Iidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Iidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Interrupt.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Int(pub u32);
    impl Int {
        ///Masks COMPIFG.
        #[must_use]
        #[inline(always)]
        pub const fn compifg(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Masks COMPIFG.
        #[inline(always)]
        pub const fn set_compifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Masks COMPINVIFG.
        #[must_use]
        #[inline(always)]
        pub const fn compinvifg(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Masks COMPINVIFG.
        #[inline(always)]
        pub const fn set_compinvifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Masks OUTRDYIFG.
        #[must_use]
        #[inline(always)]
        pub const fn outrdyifg(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Masks OUTRDYIFG.
        #[inline(always)]
        pub const fn set_outrdyifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for Int {
        #[inline(always)]
        fn default() -> Int {
            Int(0)
        }
    }
    impl core::fmt::Debug for Int {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Int")
                .field("compifg", &self.compifg())
                .field("compinvifg", &self.compinvifg())
                .field("outrdyifg", &self.outrdyifg())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Int {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Int {{ compifg: {=bool:?}, compinvifg: {=bool:?}, outrdyifg: {=bool:?} }}",
                self.compifg(), self.compinvifg(), self.outrdyifg()
            )
        }
    }
    ///Power enable.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pwren(pub u32);
    impl Pwren {
        ///Enable the power.
        #[must_use]
        #[inline(always)]
        pub const fn enable(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Enable the power.
        #[inline(always)]
        pub const fn set_enable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::PwrenKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::PwrenKey::from_bits(val as u8)
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::PwrenKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Pwren {
        #[inline(always)]
        fn default() -> Pwren {
            Pwren(0)
        }
    }
    impl core::fmt::Debug for Pwren {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pwren")
                .field("enable", &self.enable())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pwren {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pwren {{ enable: {=bool:?}, key: {:?} }}", self.enable(), self.key()
            )
        }
    }
    ///Reset Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Rstctl(pub u32);
    impl Rstctl {
        ///Assert reset to the peripheral.
        #[must_use]
        #[inline(always)]
        pub const fn resetassert(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Assert reset to the peripheral.
        #[inline(always)]
        pub const fn set_resetassert(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Clear the RESETSTKY bit in the STAT register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstkyclr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Clear the RESETSTKY bit in the STAT register.
        #[inline(always)]
        pub const fn set_resetstkyclr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::ResetKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::ResetKey::from_bits(val as u8)
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::ResetKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Rstctl {
        #[inline(always)]
        fn default() -> Rstctl {
            Rstctl(0)
        }
    }
    impl core::fmt::Debug for Rstctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Rstctl")
                .field("resetassert", &self.resetassert())
                .field("resetstkyclr", &self.resetstkyclr())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Rstctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Rstctl {{ resetassert: {=bool:?}, resetstkyclr: {=bool:?}, key: {:?} }}",
                self.resetassert(), self.resetstkyclr(), self.key()
            )
        }
    }
    ///Status.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Stat(pub u32);
    impl Stat {
        ///This bit reflects the value of the comparator output. Writing to this bit has no effect on the comparator output.
        #[must_use]
        #[inline(always)]
        pub const fn out(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///This bit reflects the value of the comparator output. Writing to this bit has no effect on the comparator output.
        #[inline(always)]
        pub const fn set_out(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Stat {
        #[inline(always)]
        fn default() -> Stat {
            Stat(0)
        }
    }
    impl core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Stat").field("out", &self.out()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Stat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Stat {{ out: {=bool:?} }}", self.out())
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Blanksrc {
        ///Blanking source disabled.
        Disable = 0x0,
        ///Select Blanking Source 1.
        Blanksrc1 = 0x01,
        ///Select Blanking Source 2.
        Blanksrc2 = 0x02,
        ///Select Blanking Source 3.
        Blanksrc3 = 0x03,
        ///Select Blanking Source 4.
        Blanksrc4 = 0x04,
        ///Select Blanking Source 5.
        Blanksrc5 = 0x05,
        ///Select Blanking Source 6.
        Blanksrc6 = 0x06,
        _RESERVED_7 = 0x07,
    }
    impl Blanksrc {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Blanksrc {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Blanksrc {
        #[inline(always)]
        fn from(val: u8) -> Blanksrc {
            Blanksrc::from_bits(val)
        }
    }
    impl From<Blanksrc> for u8 {
        #[inline(always)]
        fn from(val: Blanksrc) -> u8 {
            Blanksrc::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct ClkcfgKey(u8);
    impl ClkcfgKey {
        pub const Key: Self = Self(0xa9);
    }
    impl ClkcfgKey {
        pub const fn from_bits(val: u8) -> ClkcfgKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for ClkcfgKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xa9 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ClkcfgKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xa9 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for ClkcfgKey {
        #[inline(always)]
        fn from(val: u8) -> ClkcfgKey {
            ClkcfgKey::from_bits(val)
        }
    }
    impl From<ClkcfgKey> for u8 {
        #[inline(always)]
        fn from(val: ClkcfgKey) -> u8 {
            ClkcfgKey::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Dacctl {
        ///Comparator output controls selection between DACCODE0 and DACCODE1.
        CompoutSel = 0x0,
        ///DACSW bit controls selection between DACCODE0 and DACCODE1.
        DacswSel = 0x01,
    }
    impl Dacctl {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Dacctl {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Dacctl {
        #[inline(always)]
        fn from(val: u8) -> Dacctl {
            Dacctl::from_bits(val)
        }
    }
    impl From<Dacctl> for u8 {
        #[inline(always)]
        fn from(val: Dacctl) -> u8 {
            Dacctl::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Dacsw {
        ///DACCODE0 selected for 8-bit DAC.
        Daccode0Sel = 0x0,
        ///DACCODE1 selected for 8-bit DAC.
        Daccode1Sel = 0x01,
    }
    impl Dacsw {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Dacsw {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Dacsw {
        #[inline(always)]
        fn from(val: u8) -> Dacsw {
            Dacsw::from_bits(val)
        }
    }
    impl From<Dacsw> for u8 {
        #[inline(always)]
        fn from(val: Dacsw) -> u8 {
            Dacsw::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Fltdly {
        ///Typical filter delay of 70 ns.
        Dly0 = 0x0,
        ///Typical filter delay of 500 ns.
        Dly1 = 0x01,
        ///Typical filter delay of 1200 ns.
        Dly2 = 0x02,
        ///Typical filter delay of 2700 ns.
        Dly3 = 0x03,
    }
    impl Fltdly {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Fltdly {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Fltdly {
        #[inline(always)]
        fn from(val: u8) -> Fltdly {
            Fltdly::from_bits(val)
        }
    }
    impl From<Fltdly> for u8 {
        #[inline(always)]
        fn from(val: Fltdly) -> u8 {
            Fltdly::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Hyst {
        ///No hysteresis.
        NoHys = 0x0,
        ///Low hysteresis, typical 10mV.
        LowHys = 0x01,
        ///Medium hysteresis, typical 20mV.
        MedHys = 0x02,
        ///High hysteresis, typical 30mV.
        HighHys = 0x03,
    }
    impl Hyst {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Hyst {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Hyst {
        #[inline(always)]
        fn from(val: u8) -> Hyst {
            Hyst::from_bits(val)
        }
    }
    impl From<Hyst> for u8 {
        #[inline(always)]
        fn from(val: Hyst) -> u8 {
            Hyst::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Ies {
        ///Rising edge sets COMPIFG and falling edge sets COMPINVIFG.
        Rising = 0x0,
        ///Falling edge sets COMPIFG and rising edge sets COMPINVIFG.
        Falling = 0x01,
    }
    impl Ies {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Ies {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Ies {
        #[inline(always)]
        fn from(val: u8) -> Ies {
            Ies::from_bits(val)
        }
    }
    impl From<Ies> for u8 {
        #[inline(always)]
        fn from(val: Ies) -> u8 {
            Ies::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum IidxStat {
        ///No pending interrupt.
        NoIntr = 0x0,
        _RESERVED_1 = 0x01,
        ///Comparator output interrupt.
        Compifg = 0x02,
        ///Comparator output inverted interrupt.
        Compinvifg = 0x03,
        ///Comparator output ready interrupt.
        Outrdyifg = 0x04,
        _RESERVED_5 = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
    }
    impl IidxStat {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> IidxStat {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for IidxStat {
        #[inline(always)]
        fn from(val: u8) -> IidxStat {
            IidxStat::from_bits(val)
        }
    }
    impl From<IidxStat> for u8 {
        #[inline(always)]
        fn from(val: IidxStat) -> u8 {
            IidxStat::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum IntCfg {
        ///The interrupt or event line is disabled.
        Disable = 0x0,
        ///The interrupt or event line is in software mode. Software must clear the RIS.
        Software = 0x01,
        ///The interrupt or event line is in hardware mode. The hardware (another module) clears automatically the associated RIS flag.
        Hardware = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl IntCfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> IntCfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for IntCfg {
        #[inline(always)]
        fn from(val: u8) -> IntCfg {
            IntCfg::from_bits(val)
        }
    }
    impl From<IntCfg> for u8 {
        #[inline(always)]
        fn from(val: IntCfg) -> u8 {
            IntCfg::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Mode {
        ///Comparator is in fast mode.
        Fast = 0x0,
        ///Comparator is in ultra-low power mode.
        Ulp = 0x01,
    }
    impl Mode {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Mode {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Mode {
        #[inline(always)]
        fn from(val: u8) -> Mode {
            Mode::from_bits(val)
        }
    }
    impl From<Mode> for u8 {
        #[inline(always)]
        fn from(val: Mode) -> u8 {
            Mode::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Outpol {
        ///Comparator output is non-inverted.
        NonInv = 0x0,
        ///Comparator output is inverted.
        Inv = 0x01,
    }
    impl Outpol {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Outpol {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Outpol {
        #[inline(always)]
        fn from(val: u8) -> Outpol {
            Outpol::from_bits(val)
        }
    }
    impl From<Outpol> for u8 {
        #[inline(always)]
        fn from(val: Outpol) -> u8 {
            Outpol::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct PwrenKey(u8);
    impl PwrenKey {
        pub const Key: Self = Self(0x26);
    }
    impl PwrenKey {
        pub const fn from_bits(val: u8) -> PwrenKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for PwrenKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x26 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for PwrenKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x26 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for PwrenKey {
        #[inline(always)]
        fn from(val: u8) -> PwrenKey {
            PwrenKey::from_bits(val)
        }
    }
    impl From<PwrenKey> for u8 {
        #[inline(always)]
        fn from(val: PwrenKey) -> u8 {
            PwrenKey::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Refmode {
        ///ULP_REF bandgap, local reference buffer and 8-bit DAC inside comparator operate in static mode.
        Static = 0x0,
        ///ULP_REF bandgap, local reference buffer and 8-bit DAC inside comparator operate in sampled mode.
        Sampled = 0x01,
    }
    impl Refmode {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Refmode {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Refmode {
        #[inline(always)]
        fn from(val: u8) -> Refmode {
            Refmode::from_bits(val)
        }
    }
    impl From<Refmode> for u8 {
        #[inline(always)]
        fn from(val: Refmode) -> u8 {
            Refmode::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Refsel {
        ///If EXCH bit is 0, the selected reference is applied to positive terminal. If EXCH bit is 1, the selected reference is applied to negative terminal.
        Positive = 0x0,
        ///If EXCH bit is 0, the selected reference is applied to negative terminal. If EXCH bit is 1, the selected reference is applied to positive terminal.
        Negative = 0x01,
    }
    impl Refsel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Refsel {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Refsel {
        #[inline(always)]
        fn from(val: u8) -> Refsel {
            Refsel::from_bits(val)
        }
    }
    impl From<Refsel> for u8 {
        #[inline(always)]
        fn from(val: Refsel) -> u8 {
            Refsel::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Refsrc {
        ///Reference voltage generator is disabled (local reference buffer as well as DAC).
        Off = 0x0,
        ///VDDA selected as the reference source to DAC and DAC output applied as reference to comparator.
        VddaDac = 0x01,
        ///VREF selected as reference to DAC and DAC output applied as reference to comparator.
        VrefDac = 0x02,
        ///In devices where internal VREF is buffered and hookedup to extrernal VREF pin, VREF applied as reference to comparator. DAC is switched off.
        Vref = 0x03,
        _RESERVED_4 = 0x04,
        ///VDDA is used as comparator reference.
        Vdda = 0x05,
        ///Internal reference selected as the reference source to DAC and DAC output applied as reference to comparator.
        IntvrefDac = 0x06,
        ///Internal VREF is used as the source of comparator. Not all devices will have this option.
        Intvref = 0x07,
    }
    impl Refsrc {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Refsrc {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Refsrc {
        #[inline(always)]
        fn from(val: u8) -> Refsrc {
            Refsrc::from_bits(val)
        }
    }
    impl From<Refsrc> for u8 {
        #[inline(always)]
        fn from(val: Refsrc) -> u8 {
            Refsrc::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct ResetKey(u8);
    impl ResetKey {
        pub const Key: Self = Self(0xb1);
    }
    impl ResetKey {
        pub const fn from_bits(val: u8) -> ResetKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for ResetKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xb1 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ResetKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xb1 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for ResetKey {
        #[inline(always)]
        fn from(val: u8) -> ResetKey {
            ResetKey::from_bits(val)
        }
    }
    impl From<ResetKey> for u8 {
        #[inline(always)]
        fn from(val: ResetKey) -> u8 {
            ResetKey::to_bits(val)
        }
    }
}
