// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CpuInt {
    ptr: *mut u8,
}
unsafe impl Send for CpuInt {}
unsafe impl Sync for CpuInt {}
impl CpuInt {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
///The debug subsystem. Its useful half is the DSSM mailbox at 1100h-110Ch, a pair of 32-bit buffers with flow control that carry messages between a debug probe and the target over SWD, which SLAU847 SS35.2.4 offers for "communicating with application software running on the target device when no other communication interface is present". PWRUPIFG and PWRDWNIFG report a probe attaching and disconnecting.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Debugss {
    ptr: *mut u8,
}
unsafe impl Send for Debugss {}
unsafe impl Sync for Debugss {}
impl Debugss {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    #[inline(always)]
    pub const fn cpu_int(self, n: usize) -> CpuInt {
        assert!(n < 1usize);
        unsafe {
            CpuInt::from_ptr(self.ptr.wrapping_add(0x1020usize + n * 44usize) as _)
        }
    }
    ///Event Mode.
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e0usize) as _) }
    }
    ///Module Description.
    #[inline(always)]
    pub const fn desc(self) -> crate::common::Reg<regs::Desc, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10fcusize) as _) }
    }
    ///Transmit data register.
    #[inline(always)]
    pub const fn txd(self) -> crate::common::Reg<u32, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1100usize) as _) }
    }
    ///Transmit control register.
    #[inline(always)]
    pub const fn txctl(self) -> crate::common::Reg<regs::Txctl, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1104usize) as _) }
    }
    ///Receive data register.
    #[inline(always)]
    pub const fn rxd(self) -> crate::common::Reg<u32, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1108usize) as _) }
    }
    ///Receive control register.
    #[inline(always)]
    pub const fn rxctl(self) -> crate::common::Reg<regs::Rxctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x110cusize) as _) }
    }
    ///Special enable authorization register.
    #[inline(always)]
    pub const fn special_auth(
        self,
    ) -> crate::common::Reg<regs::SpecialAuth, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1200usize) as _) }
    }
    ///Application CPU0 authorization register.
    #[inline(always)]
    pub const fn app_auth(self) -> crate::common::Reg<regs::AppAuth, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1210usize) as _) }
    }
}
pub mod regs {
    ///Application CPU0 authorization register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct AppAuth(pub u32);
    impl AppAuth {
        ///Controls invasive debug enable.
        #[must_use]
        #[inline(always)]
        pub const fn dbgen(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Controls invasive debug enable.
        #[inline(always)]
        pub const fn set_dbgen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Controls non-invasive debug enable.
        #[must_use]
        #[inline(always)]
        pub const fn niden(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Controls non-invasive debug enable.
        #[inline(always)]
        pub const fn set_niden(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Secure invasive debug enable.
        #[must_use]
        #[inline(always)]
        pub const fn spiden(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Secure invasive debug enable.
        #[inline(always)]
        pub const fn set_spiden(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Secure non-invasive debug enable.
        #[must_use]
        #[inline(always)]
        pub const fn spniden(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Secure non-invasive debug enable.
        #[inline(always)]
        pub const fn set_spniden(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for AppAuth {
        #[inline(always)]
        fn default() -> AppAuth {
            AppAuth(0)
        }
    }
    impl core::fmt::Debug for AppAuth {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("AppAuth")
                .field("dbgen", &self.dbgen())
                .field("niden", &self.niden())
                .field("spiden", &self.spiden())
                .field("spniden", &self.spniden())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for AppAuth {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "AppAuth {{ dbgen: {=bool:?}, niden: {=bool:?}, spiden: {=bool:?}, spniden: {=bool:?} }}",
                self.dbgen(), self.niden(), self.spiden(), self.spniden()
            )
        }
    }
    ///Module Description.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Desc(pub u32);
    impl Desc {
        ///Minor rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn minrev(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///Minor rev of the IP.
        #[inline(always)]
        pub const fn set_minrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
        ///Major rev of the IP.
        #[must_use]
        #[inline(always)]
        pub const fn majrev(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x0f;
            val as u8
        }
        ///Major rev of the IP.
        #[inline(always)]
        pub const fn set_majrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize);
        }
        ///Instance Number within the device. This will be a parameter to the RTL for modules that can have multiple instances.
        #[must_use]
        #[inline(always)]
        pub const fn instnum(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0x0f;
            val as u8
        }
        ///Instance Number within the device. This will be a parameter to the RTL for modules that can have multiple instances.
        #[inline(always)]
        pub const fn set_instnum(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize);
        }
        ///Feature Set for the module *instance*.
        #[must_use]
        #[inline(always)]
        pub const fn featurever(&self) -> u8 {
            let val = (self.0 >> 12usize) & 0x0f;
            val as u8
        }
        ///Feature Set for the module *instance*.
        #[inline(always)]
        pub const fn set_featurever(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize);
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[must_use]
        #[inline(always)]
        pub const fn moduleid(&self) -> u16 {
            let val = (self.0 >> 16usize) & 0xffff;
            val as u16
        }
        ///Module identification contains a unique peripheral identification number. The assignments are maintained in a central database for all of the platform modules to ensure uniqueness.
        #[inline(always)]
        pub const fn set_moduleid(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 16usize))
                | (((val as u32) & 0xffff) << 16usize);
        }
    }
    impl Default for Desc {
        #[inline(always)]
        fn default() -> Desc {
            Desc(0)
        }
    }
    impl core::fmt::Debug for Desc {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Desc")
                .field("minrev", &self.minrev())
                .field("majrev", &self.majrev())
                .field("instnum", &self.instnum())
                .field("featurever", &self.featurever())
                .field("moduleid", &self.moduleid())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Desc {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Desc {{ minrev: {=u8:?}, majrev: {=u8:?}, instnum: {=u8:?}, featurever: {=u8:?}, moduleid: {=u16:?} }}",
                self.minrev(), self.majrev(), self.instnum(), self.featurever(), self
                .moduleid()
            )
        }
    }
    ///Event Mode.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        ///Event line mode select for peripheral events.
        #[must_use]
        #[inline(always)]
        pub const fn cpu(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for peripheral events.
        #[inline(always)]
        pub const fn set_cpu(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 0usize))
                | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    impl core::fmt::Debug for EvtMode {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("EvtMode").field("cpu", &self.cpu()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for EvtMode {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "EvtMode {{ cpu: {:?} }}", self.cpu())
        }
    }
    ///Interrupt index.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Iidx(pub u32);
    impl Iidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::Stat {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::Stat::from_bits(val as u8)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::Stat) {
            self.0 = (self.0 & !(0xff << 0usize))
                | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
    }
    impl Default for Iidx {
        #[inline(always)]
        fn default() -> Iidx {
            Iidx(0)
        }
    }
    impl core::fmt::Debug for Iidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Iidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Iidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Iidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Interrupt clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Int(pub u32);
    impl Int {
        ///Clears TXIFG in RIS register.
        #[must_use]
        #[inline(always)]
        pub const fn txifg(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Clears TXIFG in RIS register.
        #[inline(always)]
        pub const fn set_txifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Clears RXIFG in RIS register.
        #[must_use]
        #[inline(always)]
        pub const fn rxifg(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Clears RXIFG in RIS register.
        #[inline(always)]
        pub const fn set_rxifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Clears PWRUPIFG in RIS register.
        #[must_use]
        #[inline(always)]
        pub const fn pwrupifg(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Clears PWRUPIFG in RIS register.
        #[inline(always)]
        pub const fn set_pwrupifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Clears PWRDWNIFG in RIS register.
        #[must_use]
        #[inline(always)]
        pub const fn pwrdwnifg(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Clears PWRDWNIFG in RIS register.
        #[inline(always)]
        pub const fn set_pwrdwnifg(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for Int {
        #[inline(always)]
        fn default() -> Int {
            Int(0)
        }
    }
    impl core::fmt::Debug for Int {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Int")
                .field("txifg", &self.txifg())
                .field("rxifg", &self.rxifg())
                .field("pwrupifg", &self.pwrupifg())
                .field("pwrdwnifg", &self.pwrdwnifg())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Int {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Int {{ txifg: {=bool:?}, rxifg: {=bool:?}, pwrupifg: {=bool:?}, pwrdwnifg: {=bool:?} }}",
                self.txifg(), self.rxifg(), self.pwrupifg(), self.pwrdwnifg()
            )
        }
    }
    ///Receive control register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Rxctl(pub u32);
    impl Rxctl {
        ///Indicates SW write to the DSSM.RXD register. A read of the DSSM.RXD register by SWD Access Port will clear the RX field.
        #[must_use]
        #[inline(always)]
        pub const fn receive(&self) -> super::vals::Receive {
            let val = (self.0 >> 0usize) & 0x01;
            super::vals::Receive::from_bits(val as u8)
        }
        ///Indicates SW write to the DSSM.RXD register. A read of the DSSM.RXD register by SWD Access Port will clear the RX field.
        #[inline(always)]
        pub const fn set_receive(&mut self, val: super::vals::Receive) {
            self.0 = (self.0 & !(0x01 << 0usize))
                | (((val.to_bits() as u32) & 0x01) << 0usize);
        }
        ///Generic RX flags that can be set by SW and read by external debug tool. Functionality is defined by SW.
        #[must_use]
        #[inline(always)]
        pub const fn receive_flags(&self) -> u8 {
            let val = (self.0 >> 1usize) & 0x7f;
            val as u8
        }
        ///Generic RX flags that can be set by SW and read by external debug tool. Functionality is defined by SW.
        #[inline(always)]
        pub const fn set_receive_flags(&mut self, val: u8) {
            self.0 = (self.0 & !(0x7f << 1usize)) | (((val as u32) & 0x7f) << 1usize);
        }
    }
    impl Default for Rxctl {
        #[inline(always)]
        fn default() -> Rxctl {
            Rxctl(0)
        }
    }
    impl core::fmt::Debug for Rxctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Rxctl")
                .field("receive", &self.receive())
                .field("receive_flags", &self.receive_flags())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Rxctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Rxctl {{ receive: {:?}, receive_flags: {=u8:?} }}", self.receive(),
                self.receive_flags()
            )
        }
    }
    ///Special enable authorization register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct SpecialAuth(pub u32);
    impl SpecialAuth {
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can use the Security-AP to communicate with security control logic. When deasserted, a DAPBUS firewall will isolate the AP and prevent access to the Security-AP.
        #[must_use]
        #[inline(always)]
        pub const fn secapen(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can use the Security-AP to communicate with security control logic. When deasserted, a DAPBUS firewall will isolate the AP and prevent access to the Security-AP.
        #[inline(always)]
        pub const fn set_secapen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///When asserted, the SW-DP functions normally. When deasserted, the SW-DP effectively disables all external debug access.
        #[must_use]
        #[inline(always)]
        pub const fn swdporten(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///When asserted, the SW-DP functions normally. When deasserted, the SW-DP effectively disables all external debug access.
        #[inline(always)]
        pub const fn set_swdporten(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can then access the DFT-AP external to the DebugSS lite. When deasserted, a DAPBUS firewall will isolate the AP and prevent access.
        #[must_use]
        #[inline(always)]
        pub const fn dftapen(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can then access the DFT-AP external to the DebugSS lite. When deasserted, a DAPBUS firewall will isolate the AP and prevent access.
        #[inline(always)]
        pub const fn set_dftapen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can then access an ET-AP external to the DebugSS lite. When deasserted, a DAPBUS firewall will isolate the AP and prevent access.
        #[must_use]
        #[inline(always)]
        pub const fn etapen(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can then access an ET-AP external to the DebugSS lite. When deasserted, a DAPBUS firewall will isolate the AP and prevent access.
        #[inline(always)]
        pub const fn set_etapen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can use the Config-AP to read device configuration information. When deasserted, a DAPBUS firewall will isolate the AP and prevent access to the Config-AP.
        #[must_use]
        #[inline(always)]
        pub const fn cfgapen(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can use the Config-AP to read device configuration information. When deasserted, a DAPBUS firewall will isolate the AP and prevent access to the Config-AP.
        #[inline(always)]
        pub const fn set_cfgapen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Disabling / enabling debug access to the M0+ Core via the AHB-AP DAP bus isolation.
        #[must_use]
        #[inline(always)]
        pub const fn ahbapen(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        ///Disabling / enabling debug access to the M0+ Core via the AHB-AP DAP bus isolation.
        #[inline(always)]
        pub const fn set_ahbapen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can then access the PWR-AP to power and reset state of the CPU. When deasserted, a DAPBUS firewall will isolate the AP and prevent access.
        #[must_use]
        #[inline(always)]
        pub const fn pwrapen(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        ///An active high input. When asserted (and SWD access is also permitted), the debug tools can then access the PWR-AP to power and reset state of the CPU. When deasserted, a DAPBUS firewall will isolate the AP and prevent access.
        #[inline(always)]
        pub const fn set_pwrapen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
    }
    impl Default for SpecialAuth {
        #[inline(always)]
        fn default() -> SpecialAuth {
            SpecialAuth(0)
        }
    }
    impl core::fmt::Debug for SpecialAuth {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("SpecialAuth")
                .field("secapen", &self.secapen())
                .field("swdporten", &self.swdporten())
                .field("dftapen", &self.dftapen())
                .field("etapen", &self.etapen())
                .field("cfgapen", &self.cfgapen())
                .field("ahbapen", &self.ahbapen())
                .field("pwrapen", &self.pwrapen())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for SpecialAuth {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "SpecialAuth {{ secapen: {=bool:?}, swdporten: {=bool:?}, dftapen: {=bool:?}, etapen: {=bool:?}, cfgapen: {=bool:?}, ahbapen: {=bool:?}, pwrapen: {=bool:?} }}",
                self.secapen(), self.swdporten(), self.dftapen(), self.etapen(), self
                .cfgapen(), self.ahbapen(), self.pwrapen()
            )
        }
    }
    ///Transmit control register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Txctl(pub u32);
    impl Txctl {
        ///Indicates data request in DSSM.TXD, set on write via Debug AP to DSSM.TXD. A read of the DSSM.TXD register by SW will clear the TX field. The tool can check that TXD is empty by reading this field.
        #[must_use]
        #[inline(always)]
        pub const fn transmit(&self) -> super::vals::Transmit {
            let val = (self.0 >> 0usize) & 0x01;
            super::vals::Transmit::from_bits(val as u8)
        }
        ///Indicates data request in DSSM.TXD, set on write via Debug AP to DSSM.TXD. A read of the DSSM.TXD register by SW will clear the TX field. The tool can check that TXD is empty by reading this field.
        #[inline(always)]
        pub const fn set_transmit(&mut self, val: super::vals::Transmit) {
            self.0 = (self.0 & !(0x01 << 0usize))
                | (((val.to_bits() as u32) & 0x01) << 0usize);
        }
        ///Generic TX flags that can be set by external debug tool. Functionality is defined by SW.
        #[must_use]
        #[inline(always)]
        pub const fn transmit_flags(&self) -> u32 {
            let val = (self.0 >> 1usize) & 0x7fff_ffff;
            val as u32
        }
        ///Generic TX flags that can be set by external debug tool. Functionality is defined by SW.
        #[inline(always)]
        pub const fn set_transmit_flags(&mut self, val: u32) {
            self.0 = (self.0 & !(0x7fff_ffff << 1usize))
                | (((val as u32) & 0x7fff_ffff) << 1usize);
        }
    }
    impl Default for Txctl {
        #[inline(always)]
        fn default() -> Txctl {
            Txctl(0)
        }
    }
    impl core::fmt::Debug for Txctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Txctl")
                .field("transmit", &self.transmit())
                .field("transmit_flags", &self.transmit_flags())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Txctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Txctl {{ transmit: {:?}, transmit_flags: {=u32:?} }}", self
                .transmit(), self.transmit_flags()
            )
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum IntCfg {
        ///The interrupt or event line is disabled.
        Disable = 0x0,
        ///The interrupt or event line is in software mode. Software must clear the RIS.
        Software = 0x01,
        ///The interrupt or event line is in hardware mode. The hardware (another module) clears automatically the associated RIS flag.
        Hardware = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl IntCfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> IntCfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for IntCfg {
        #[inline(always)]
        fn from(val: u8) -> IntCfg {
            IntCfg::from_bits(val)
        }
    }
    impl From<IntCfg> for u8 {
        #[inline(always)]
        fn from(val: IntCfg) -> u8 {
            IntCfg::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Receive {
        ///RXD empty.
        Empty = 0x0,
        ///RXD full.
        Full = 0x01,
    }
    impl Receive {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Receive {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Receive {
        #[inline(always)]
        fn from(val: u8) -> Receive {
            Receive::from_bits(val)
        }
    }
    impl From<Receive> for u8 {
        #[inline(always)]
        fn from(val: Receive) -> u8 {
            Receive::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Stat(u8);
    impl Stat {
        ///No pending interrupt request.
        pub const NoIntr: Self = Self(0x0);
        ///TX interrupt.
        pub const Txifg: Self = Self(0x01);
        ///RX interrupt.
        pub const Rxifg: Self = Self(0x02);
        ///Power-up interrupt. A debug session has started.
        pub const Pwrup: Self = Self(0x03);
        ///Power-up interrupt. A debug session has started.
        pub const Pwrdwn: Self = Self(0x04);
    }
    impl Stat {
        pub const fn from_bits(val: u8) -> Stat {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x0 => f.write_str("NoIntr"),
                0x01 => f.write_str("Txifg"),
                0x02 => f.write_str("Rxifg"),
                0x03 => f.write_str("Pwrup"),
                0x04 => f.write_str("Pwrdwn"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Stat {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x0 => defmt::write!(f, "NoIntr"),
                0x01 => defmt::write!(f, "Txifg"),
                0x02 => defmt::write!(f, "Rxifg"),
                0x03 => defmt::write!(f, "Pwrup"),
                0x04 => defmt::write!(f, "Pwrdwn"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for Stat {
        #[inline(always)]
        fn from(val: u8) -> Stat {
            Stat::from_bits(val)
        }
    }
    impl From<Stat> for u8 {
        #[inline(always)]
        fn from(val: Stat) -> u8 {
            Stat::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Transmit {
        ///TXD is empty.
        Empty = 0x0,
        ///TXD is full.
        Full = 0x01,
    }
    impl Transmit {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Transmit {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Transmit {
        #[inline(always)]
        fn from(val: u8) -> Transmit {
            Transmit::from_bits(val)
        }
    }
    impl From<Transmit> for u8 {
        #[inline(always)]
        fn from(val: Transmit) -> u8 {
            Transmit::to_bits(val)
        }
    }
}
