// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]

#[doc = "NVMNW_GANDALF."]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Flashctl {
    ptr: *mut u8,
}
unsafe impl Send for Flashctl {}
unsafe impl Sync for Flashctl {}
impl Flashctl {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    #[doc = "Interrupt Index Register."]
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1020usize) as _) }
    }
    #[doc = "Interrupt Mask Register."]
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1028usize) as _) }
    }
    #[doc = "Raw Interrupt Status Register."]
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1030usize) as _) }
    }
    #[doc = "Masked Interrupt Status Register."]
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1038usize) as _) }
    }
    #[doc = "Interrupt Set Register."]
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1040usize) as _) }
    }
    #[doc = "Interrupt Clear Register."]
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1048usize) as _) }
    }
    #[doc = "Event Mode."]
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x10e0usize) as _) }
    }
    #[doc = "Hardware Version Description Register."]
    #[inline(always)]
    pub const fn desc(self) -> crate::common::Reg<regs::Desc, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x10fcusize) as _) }
    }
    #[doc = "Command Execute Register."]
    #[inline(always)]
    pub const fn cmdexec(self) -> crate::common::Reg<regs::Cmdexec, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1100usize) as _) }
    }
    #[doc = "Command Type Register."]
    #[inline(always)]
    pub const fn cmdtype(self) -> crate::common::Reg<regs::Cmdtype, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1104usize) as _) }
    }
    #[doc = "Command Control Register."]
    #[inline(always)]
    pub const fn cmdctl(self) -> crate::common::Reg<regs::Cmdctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1108usize) as _) }
    }
    #[doc = "Command Address Register."]
    #[inline(always)]
    pub const fn cmdaddr(self) -> crate::common::Reg<u32, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1120usize) as _) }
    }
    #[doc = "Command Program Byte Enable Register."]
    #[inline(always)]
    pub const fn cmdbyten(self) -> crate::common::Reg<regs::Cmdbyten, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1124usize) as _) }
    }
    #[doc = "Command Data Index Register."]
    #[inline(always)]
    pub const fn cmddataindex(self) -> crate::common::Reg<regs::Cmddataindex, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x112cusize) as _) }
    }
    #[doc = "Command Data Register 0."]
    #[inline(always)]
    pub const fn cmddata(self, n: usize) -> crate::common::Reg<u32, crate::common::RW> {
        assert!(n < 32usize);
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1130usize + n * 4usize) as _) }
    }
    #[doc = "Command Data Register ECC 0."]
    #[inline(always)]
    pub const fn cmddataecc(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Cmddataecc, crate::common::RW> {
        assert!(n < 8usize);
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x11b0usize + n * 4usize) as _) }
    }
    #[doc = "Command Write Erase Protect A Register."]
    #[inline(always)]
    pub const fn cmdweprota(self) -> crate::common::Reg<regs::Cmdweprot, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x11d0usize) as _) }
    }
    #[doc = "Command Write Erase Protect B Register."]
    #[inline(always)]
    pub const fn cmdweprotb(self) -> crate::common::Reg<regs::Cmdweprot, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x11d4usize) as _) }
    }
    #[doc = "Command Write Erase Protect C Register."]
    #[inline(always)]
    pub const fn cmdweprotc(self) -> crate::common::Reg<regs::Cmdweprot, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x11d8usize) as _) }
    }
    #[doc = "Command Write Erase Protect Non-Main Register."]
    #[inline(always)]
    pub const fn cmdweprotnm(self) -> crate::common::Reg<regs::Cmdweprot, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1210usize) as _) }
    }
    #[doc = "Command Write Erase Protect Trim Register."]
    #[inline(always)]
    pub const fn cmdweprottr(self) -> crate::common::Reg<regs::Cmdweprot, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1214usize) as _) }
    }
    #[doc = "Command Write Erase Protect Engr Register."]
    #[inline(always)]
    pub const fn cmdweproten(self) -> crate::common::Reg<regs::Cmdweprot, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1218usize) as _) }
    }
    #[doc = "Command Configuration Register."]
    #[inline(always)]
    pub const fn cfgcmd(self) -> crate::common::Reg<regs::Cfgcmd, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13b0usize) as _) }
    }
    #[doc = "Pulse Counter Configuration Register."]
    #[inline(always)]
    pub const fn cfgpcnt(self) -> crate::common::Reg<regs::Cfgpcnt, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13b4usize) as _) }
    }
    #[doc = "Command Status Register."]
    #[inline(always)]
    pub const fn statcmd(self) -> crate::common::Reg<regs::Statcmd, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13d0usize) as _) }
    }
    #[doc = "Address Status Register."]
    #[inline(always)]
    pub const fn stataddr(self) -> crate::common::Reg<regs::Stataddr, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13d4usize) as _) }
    }
    #[doc = "Pulse Count Status Register."]
    #[inline(always)]
    pub const fn statpcnt(self) -> crate::common::Reg<regs::Statpcnt, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13d8usize) as _) }
    }
    #[doc = "Mode Status Register."]
    #[inline(always)]
    pub const fn statmode(self) -> crate::common::Reg<regs::Statmode, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13dcusize) as _) }
    }
    #[doc = "Global Information Register 0."]
    #[inline(always)]
    pub const fn gblinfo0(self) -> crate::common::Reg<regs::Gblinfo0, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13f0usize) as _) }
    }
    #[doc = "Global Information Register 1."]
    #[inline(always)]
    pub const fn gblinfo1(self) -> crate::common::Reg<regs::Gblinfo1, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13f4usize) as _) }
    }
    #[doc = "Global Information Register 2."]
    #[inline(always)]
    pub const fn gblinfo2(self) -> crate::common::Reg<regs::Gblinfo2, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x13f8usize) as _) }
    }
    #[doc = "Bank Information Register 0."]
    #[inline(always)]
    pub const fn bankinfo0(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Bankinfo0, crate::common::R> {
        assert!(n < 5usize);
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1400usize + n * 16usize) as _) }
    }
    #[doc = "Bank Information Register 1."]
    #[inline(always)]
    pub const fn bankinfo1(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Bankinfo1, crate::common::R> {
        assert!(n < 5usize);
        unsafe { crate::common::Reg::from_ptr(self.ptr.add(0x1404usize + n * 16usize) as _) }
    }
}
pub mod regs {
    #[doc = "Bank Information Register 0."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Bankinfo0(pub u32);
    impl Bankinfo0 {
        #[doc = "Main region size in sectors Minimum: 0x8 (8) Maximum: 0x200 (512)."]
        #[inline(always)]
        pub const fn mainsize(&self) -> super::vals::BankinfoMainsize {
            let val = (self.0 >> 0usize) & 0x0fff;
            super::vals::BankinfoMainsize::from_bits(val as u16)
        }
        #[doc = "Main region size in sectors Minimum: 0x8 (8) Maximum: 0x200 (512)."]
        #[inline(always)]
        pub fn set_mainsize(&mut self, val: super::vals::BankinfoMainsize) {
            self.0 = (self.0 & !(0x0fff << 0usize)) | (((val.to_bits() as u32) & 0x0fff) << 0usize);
        }
    }
    impl Default for Bankinfo0 {
        #[inline(always)]
        fn default() -> Bankinfo0 {
            Bankinfo0(0)
        }
    }
    #[doc = "Bank Information Register 1."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Bankinfo1(pub u32);
    impl Bankinfo1 {
        #[doc = "Non-main region size in sectors Minimum: 0x0 (0) Maximum: 0x10 (16)."]
        #[inline(always)]
        pub const fn nonmainsize(&self) -> super::vals::BankinfoNonmainsize {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::BankinfoNonmainsize::from_bits(val as u8)
        }
        #[doc = "Non-main region size in sectors Minimum: 0x0 (0) Maximum: 0x10 (16)."]
        #[inline(always)]
        pub fn set_nonmainsize(&mut self, val: super::vals::BankinfoNonmainsize) {
            self.0 = (self.0 & !(0xff << 0usize)) | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
        #[doc = "Trim region size in sectors Minimum: 0x0 (0) Maximum: 0x10 (16)."]
        #[inline(always)]
        pub const fn trimsize(&self) -> super::vals::BankinfoTrimsize {
            let val = (self.0 >> 8usize) & 0xff;
            super::vals::BankinfoTrimsize::from_bits(val as u8)
        }
        #[doc = "Trim region size in sectors Minimum: 0x0 (0) Maximum: 0x10 (16)."]
        #[inline(always)]
        pub fn set_trimsize(&mut self, val: super::vals::BankinfoTrimsize) {
            self.0 = (self.0 & !(0xff << 8usize)) | (((val.to_bits() as u32) & 0xff) << 8usize);
        }
        #[doc = "Engr region size in sectors Minimum: 0x0 (0) Maximum: 0x10 (16)."]
        #[inline(always)]
        pub const fn engrsize(&self) -> super::vals::BankinfoEngrsize {
            let val = (self.0 >> 16usize) & 0xff;
            super::vals::BankinfoEngrsize::from_bits(val as u8)
        }
        #[doc = "Engr region size in sectors Minimum: 0x0 (0) Maximum: 0x10 (16)."]
        #[inline(always)]
        pub fn set_engrsize(&mut self, val: super::vals::BankinfoEngrsize) {
            self.0 = (self.0 & !(0xff << 16usize)) | (((val.to_bits() as u32) & 0xff) << 16usize);
        }
    }
    impl Default for Bankinfo1 {
        #[inline(always)]
        fn default() -> Bankinfo1 {
            Bankinfo1(0)
        }
    }
    #[doc = "Command Configuration Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cfgcmd(pub u32);
    impl Cfgcmd {
        #[doc = "Wait State setting for program verify, erase verify and read verify."]
        #[inline(always)]
        pub const fn waitstate(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        #[doc = "Wait State setting for program verify, erase verify and read verify."]
        #[inline(always)]
        pub fn set_waitstate(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
        #[doc = "Enable pulse stretching when generating a read clock to the flash bank from the flash wrapper. This effectively divides the read clock driven to the bank in order to avoid minimum pulse width requirements at the bank."]
        #[inline(always)]
        pub const fn rdclkstren(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        #[doc = "Enable pulse stretching when generating a read clock to the flash bank from the flash wrapper. This effectively divides the read clock driven to the bank in order to avoid minimum pulse width requirements at the bank."]
        #[inline(always)]
        pub fn set_rdclkstren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        #[doc = "Enable pulse stretching when generating a control clock to the flash bank from the flash wrapper. This effectively divides the control clock driven to the bank in order to avoid minimum pulse width requirements at the bank."]
        #[inline(always)]
        pub const fn ctrlclkstren(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        #[doc = "Enable pulse stretching when generating a control clock to the flash bank from the flash wrapper. This effectively divides the control clock driven to the bank in order to avoid minimum pulse width requirements at the bank."]
        #[inline(always)]
        pub fn set_ctrlclkstren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        #[doc = "Enable pulse stretching for the clocking of the hold latches for inputs to the flash bank. This effectively divides the flash controller internal clock in order to create a 50/50 duty cycle clock for hold latching."]
        #[inline(always)]
        pub const fn holdclkstren(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        #[doc = "Enable pulse stretching for the clocking of the hold latches for inputs to the flash bank. This effectively divides the flash controller internal clock in order to create a 50/50 duty cycle clock for hold latching."]
        #[inline(always)]
        pub fn set_holdclkstren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
    }
    impl Default for Cfgcmd {
        #[inline(always)]
        fn default() -> Cfgcmd {
            Cfgcmd(0)
        }
    }
    #[doc = "Pulse Counter Configuration Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cfgpcnt(pub u32);
    impl Cfgpcnt {
        #[doc = "Override hard-wired maximum pulse count. If MAXERSPCNTOVR is not set, then setting this value alone will override the max pulse count for both program and erase. If MAXERSPCNTOVR is set, then this bit will only control the max pulse count setting for program. By default, this bit is 0, and a hard-wired max pulse count is used."]
        #[inline(always)]
        pub const fn maxpcntovr(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "Override hard-wired maximum pulse count. If MAXERSPCNTOVR is not set, then setting this value alone will override the max pulse count for both program and erase. If MAXERSPCNTOVR is set, then this bit will only control the max pulse count setting for program. By default, this bit is 0, and a hard-wired max pulse count is used."]
        #[inline(always)]
        pub fn set_maxpcntovr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        #[doc = "Override maximum pulse counter with this value. If MAXPCNTOVR = 0, then this field is ignored. If MAXPCNTOVR = 1 and MAXERSPCNTOVR = 0, then this value will be used to override the max pulse count for both program and erase. Full max value will be {4'h0, MAXPCNTVAL} . If MAXPCNTOVR = 1 and MAXERSPCNTOVR = 1, then this value will be used to override the max pulse count for program only. Full max value will be {4'h0, MAXPCNTVAL}."]
        #[inline(always)]
        pub const fn maxpcntval(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0xff;
            val as u8
        }
        #[doc = "Override maximum pulse counter with this value. If MAXPCNTOVR = 0, then this field is ignored. If MAXPCNTOVR = 1 and MAXERSPCNTOVR = 0, then this value will be used to override the max pulse count for both program and erase. Full max value will be {4'h0, MAXPCNTVAL} . If MAXPCNTOVR = 1 and MAXERSPCNTOVR = 1, then this value will be used to override the max pulse count for program only. Full max value will be {4'h0, MAXPCNTVAL}."]
        #[inline(always)]
        pub fn set_maxpcntval(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 4usize)) | (((val as u32) & 0xff) << 4usize);
        }
        #[doc = "Override hard-wired maximum pulse count for erase. If set, then the value in MAXERSPCNTVAL will be used as the max pulse count for erase operations. By default, this bit is 0, and a hard-wired max pulse count is used."]
        #[inline(always)]
        pub const fn maxerspcntovr(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        #[doc = "Override hard-wired maximum pulse count for erase. If set, then the value in MAXERSPCNTVAL will be used as the max pulse count for erase operations. By default, this bit is 0, and a hard-wired max pulse count is used."]
        #[inline(always)]
        pub fn set_maxerspcntovr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
        #[doc = "Override maximum pulse count for erase with this value. If MAXERSPCNTOVR = 0, then this field is ignored. If MAXERSPCNTOVR = 1, then this value will be used to override the max pulse count for erase."]
        #[inline(always)]
        pub const fn maxerspcntval(&self) -> u16 {
            let val = (self.0 >> 20usize) & 0x0fff;
            val as u16
        }
        #[doc = "Override maximum pulse count for erase with this value. If MAXERSPCNTOVR = 0, then this field is ignored. If MAXERSPCNTOVR = 1, then this value will be used to override the max pulse count for erase."]
        #[inline(always)]
        pub fn set_maxerspcntval(&mut self, val: u16) {
            self.0 = (self.0 & !(0x0fff << 20usize)) | (((val as u32) & 0x0fff) << 20usize);
        }
    }
    impl Default for Cfgpcnt {
        #[inline(always)]
        fn default() -> Cfgpcnt {
            Cfgpcnt(0)
        }
    }
    #[doc = "Command Program Byte Enable Register. Controls which bytes of the flash word (including ECC) are active."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmdbyten(pub u32);
    impl Cmdbyten {
        #[doc = "Data byte enable. Each bit controls one flash byte within a flash word."]
        #[inline(always)]
        pub const fn data(&self, n: usize) -> bool {
            assert!(n < 8usize);
            let offs = 0usize + n * 1usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        #[doc = "Data byte enable. Each bit controls one flash byte within a flash word."]
        #[inline(always)]
        pub fn set_data(&mut self, n: usize, val: bool) {
            assert!(n < 8usize);
            let offs = 0usize + n * 1usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
        #[doc = "ECC byte enable. Controls if the ECC byte is active."]
        #[inline(always)]
        pub const fn ecc(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        #[doc = "ECC byte enable. Controls if the ECC byte is active."]
        #[inline(always)]
        pub fn set_ecc(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
    }
    impl Default for Cmdbyten {
        #[inline(always)]
        fn default() -> Cmdbyten {
            Cmdbyten(0)
        }
    }
    #[doc = "Command Control Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmdctl(pub u32);
    impl Cmdctl {
        #[doc = "Mode This field is only used for the Mode Change command type. Otherwise, bank and pump modes are set automaticlly through the NW hardware."]
        #[inline(always)]
        pub const fn modesel(&self) -> super::vals::Mode {
            let val = (self.0 >> 0usize) & 0x0f;
            super::vals::Mode::from_bits(val as u8)
        }
        #[doc = "Mode This field is only used for the Mode Change command type. Otherwise, bank and pump modes are set automaticlly through the NW hardware."]
        #[inline(always)]
        pub fn set_modesel(&mut self, val: super::vals::Mode) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val.to_bits() as u32) & 0x0f) << 0usize);
        }
        #[doc = "Bank Select A specific Bank ID can be written to this field to indicate to which bank an operation is to be applied if CMDCTL.ADDRXLATEOVR is set."]
        #[inline(always)]
        pub const fn banksel(&self) -> super::vals::Bank {
            let val = (self.0 >> 4usize) & 0x1f;
            super::vals::Bank::from_bits(val as u8)
        }
        #[doc = "Bank Select A specific Bank ID can be written to this field to indicate to which bank an operation is to be applied if CMDCTL.ADDRXLATEOVR is set."]
        #[inline(always)]
        pub fn set_banksel(&mut self, val: super::vals::Bank) {
            self.0 = (self.0 & !(0x1f << 4usize)) | (((val.to_bits() as u32) & 0x1f) << 4usize);
        }
        #[doc = "Bank Region A specific region ID can be written to this field to indicate to which region an operation is to be applied if CMDCTL.ADDRXLATEOVR is set."]
        #[inline(always)]
        pub const fn regionsel(&self) -> super::vals::Regionsel {
            let val = (self.0 >> 9usize) & 0x0f;
            super::vals::Regionsel::from_bits(val as u8)
        }
        #[doc = "Bank Region A specific region ID can be written to this field to indicate to which region an operation is to be applied if CMDCTL.ADDRXLATEOVR is set."]
        #[inline(always)]
        pub fn set_regionsel(&mut self, val: super::vals::Regionsel) {
            self.0 = (self.0 & !(0x0f << 9usize)) | (((val.to_bits() as u32) & 0x0f) << 9usize);
        }
        #[doc = "Enable verify before program or erase. For program, bits already programmed to the requests value will be masked. For erase, sectors already erased will be masked."]
        #[inline(always)]
        pub const fn preveren(&self) -> bool {
            let val = (self.0 >> 14usize) & 0x01;
            val != 0
        }
        #[doc = "Enable verify before program or erase. For program, bits already programmed to the requests value will be masked. For erase, sectors already erased will be masked."]
        #[inline(always)]
        pub fn set_preveren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize);
        }
        #[doc = "Enable verify after program or erase"]
        #[inline(always)]
        pub const fn postveren(&self) -> bool {
            let val = (self.0 >> 15usize) & 0x01;
            val != 0
        }
        #[doc = "Enable verify after program or erase"]
        #[inline(always)]
        pub fn set_postveren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize);
        }
        #[doc = "Override hardware address translation of address in CMDADDR from a system address to a bank address and bank ID. Use data written to CMDADDR directly as the bank address. Use the value written to CMDCTL.BANKSEL directly as the bank ID. Use the value written to CMDCTL.REGIONSEL directly as the region ID."]
        #[inline(always)]
        pub const fn addrxlateovr(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        #[doc = "Override hardware address translation of address in CMDADDR from a system address to a bank address and bank ID. Use data written to CMDADDR directly as the bank address. Use the value written to CMDCTL.BANKSEL directly as the bank ID. Use the value written to CMDCTL.REGIONSEL directly as the region ID."]
        #[inline(always)]
        pub fn set_addrxlateovr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
        #[doc = "Override hardware generation of ECC data for program. Use data written to CMDDATAECC*."]
        #[inline(always)]
        pub const fn eccgenovr(&self) -> bool {
            let val = (self.0 >> 17usize) & 0x01;
            val != 0
        }
        #[doc = "Override hardware generation of ECC data for program. Use data written to CMDDATAECC*."]
        #[inline(always)]
        pub fn set_eccgenovr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize);
        }
        #[doc = "Disable use of program mask for programming. Bit masking will not be used during program verify. If any bits fail the verify either before (prever) or after (postver) the operation, then all specified flash entries will receive subsequent program pulse."]
        #[inline(always)]
        pub const fn progmaskdis(&self) -> bool {
            let val = (self.0 >> 18usize) & 0x01;
            val != 0
        }
        #[doc = "Disable use of program mask for programming. Bit masking will not be used during program verify. If any bits fail the verify either before (prever) or after (postver) the operation, then all specified flash entries will receive subsequent program pulse."]
        #[inline(always)]
        pub fn set_progmaskdis(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize);
        }
        #[doc = "Disable use of erase mask for erase Bit masking will not be used during erase verify. If any sectors fail the verify either before (prever) or after (postver) the operation, then all specified flash sectors will receive subsequent erase pulse."]
        #[inline(always)]
        pub const fn erasemaskdis(&self) -> bool {
            let val = (self.0 >> 19usize) & 0x01;
            val != 0
        }
        #[doc = "Disable use of erase mask for erase Bit masking will not be used during erase verify. If any sectors fail the verify either before (prever) or after (postver) the operation, then all specified flash sectors will receive subsequent erase pulse."]
        #[inline(always)]
        pub fn set_erasemaskdis(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize);
        }
        #[doc = "Disable Stair-Step Erase. If set, the default VHV trim voltage setting will be used for all erase pulses. By default, this bit is reset, meaning that the VHV voltage will be stepped during successive erase pulses. The step count, step voltage, begin and end voltages are all hard-wired."]
        #[inline(always)]
        pub const fn sserasedis(&self) -> bool {
            let val = (self.0 >> 20usize) & 0x01;
            val != 0
        }
        #[doc = "Disable Stair-Step Erase. If set, the default VHV trim voltage setting will be used for all erase pulses. By default, this bit is reset, meaning that the VHV voltage will be stepped during successive erase pulses. The step count, step voltage, begin and end voltages are all hard-wired."]
        #[inline(always)]
        pub fn set_sserasedis(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize);
        }
        #[doc = "Enable invalid data verify. This checks for 0->1 transitions in the memory when a program operation is initiated. If such a transition is found, the program will fail with an error without executing the program."]
        #[inline(always)]
        pub const fn dataveren(&self) -> bool {
            let val = (self.0 >> 21usize) & 0x01;
            val != 0
        }
        #[doc = "Enable invalid data verify. This checks for 0->1 transitions in the memory when a program operation is initiated. If such a transition is found, the program will fail with an error without executing the program."]
        #[inline(always)]
        pub fn set_dataveren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize);
        }
    }
    impl Default for Cmdctl {
        #[inline(always)]
        fn default() -> Cmdctl {
            Cmdctl(0)
        }
    }
    #[doc = "Command Data Register ECC 0."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmddataecc(pub u32);
    impl Cmddataecc {
        #[doc = "ECC data for bits 63:0 of the data is placed here."]
        #[inline(always)]
        pub const fn val0(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0xff;
            val as u8
        }
        #[doc = "ECC data for bits 63:0 of the data is placed here."]
        #[inline(always)]
        pub fn set_val0(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 0usize)) | (((val as u32) & 0xff) << 0usize);
        }
        #[doc = "ECC data for bits 127:64 of the data is placed here."]
        #[inline(always)]
        pub const fn val1(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0xff;
            val as u8
        }
        #[doc = "ECC data for bits 127:64 of the data is placed here."]
        #[inline(always)]
        pub fn set_val1(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 8usize)) | (((val as u32) & 0xff) << 8usize);
        }
    }
    impl Default for Cmddataecc {
        #[inline(always)]
        fn default() -> Cmddataecc {
            Cmddataecc(0)
        }
    }
    #[doc = "Command Data Index Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmddataindex(pub u32);
    impl Cmddataindex {
        #[doc = "Data register index."]
        #[inline(always)]
        pub const fn val(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x07;
            val as u8
        }
        #[doc = "Data register index."]
        #[inline(always)]
        pub fn set_val(&mut self, val: u8) {
            self.0 = (self.0 & !(0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize);
        }
    }
    impl Default for Cmddataindex {
        #[inline(always)]
        fn default() -> Cmddataindex {
            Cmddataindex(0)
        }
    }
    #[doc = "Command Execute Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmdexec(pub u32);
    impl Cmdexec {
        #[doc = "Command Execute value. Initiates execution of the command specified in the CMDTYPE register. This register is blocked for writes after being written to 1 and prior to STATCMD.DONE being set by the flash wrapper hardware. Flash wrapper hardware clears this register after the processing of the command has completed."]
        #[inline(always)]
        pub const fn val(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "Command Execute value. Initiates execution of the command specified in the CMDTYPE register. This register is blocked for writes after being written to 1 and prior to STATCMD.DONE being set by the flash wrapper hardware. Flash wrapper hardware clears this register after the processing of the command has completed."]
        #[inline(always)]
        pub fn set_val(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Cmdexec {
        #[inline(always)]
        fn default() -> Cmdexec {
            Cmdexec(0)
        }
    }
    #[doc = "Command Type Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmdtype(pub u32);
    impl Cmdtype {
        #[doc = "Command type."]
        #[inline(always)]
        pub const fn command(&self) -> super::vals::Command {
            let val = (self.0 >> 0usize) & 0x07;
            super::vals::Command::from_bits(val as u8)
        }
        #[doc = "Command type."]
        #[inline(always)]
        pub fn set_command(&mut self, val: super::vals::Command) {
            self.0 = (self.0 & !(0x07 << 0usize)) | (((val.to_bits() as u32) & 0x07) << 0usize);
        }
        #[doc = "Command size."]
        #[inline(always)]
        pub const fn size(&self) -> super::vals::Size {
            let val = (self.0 >> 4usize) & 0x07;
            super::vals::Size::from_bits(val as u8)
        }
        #[doc = "Command size."]
        #[inline(always)]
        pub fn set_size(&mut self, val: super::vals::Size) {
            self.0 = (self.0 & !(0x07 << 4usize)) | (((val.to_bits() as u32) & 0x07) << 4usize);
        }
    }
    impl Default for Cmdtype {
        #[inline(always)]
        fn default() -> Cmdtype {
            Cmdtype(0)
        }
    }
    #[doc = "Command write enable protection register"]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cmdweprot(pub u32);
    impl Cmdweprot {
        #[doc = "Region of flash being write (un)protected"]
        #[inline(always)]
        pub const fn region(&self, n: usize) -> bool {
            assert!(n < 32usize);
            let offs = 0usize + n * 1usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        #[doc = "Region of flash being write (un)protected"]
        #[inline(always)]
        pub fn set_region(&mut self, n: usize, val: bool) {
            assert!(n < 32usize);
            let offs = 0usize + n * 1usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
    }
    impl Default for Cmdweprot {
        #[inline(always)]
        fn default() -> Cmdweprot {
            Cmdweprot(0)
        }
    }
    #[doc = "Hardware Version Description Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Desc(pub u32);
    impl Desc {
        #[doc = "Minor Revision."]
        #[inline(always)]
        pub const fn minrev(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        #[doc = "Minor Revision."]
        #[inline(always)]
        pub fn set_minrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
        #[doc = "Major Revision."]
        #[inline(always)]
        pub const fn majrev(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x0f;
            val as u8
        }
        #[doc = "Major Revision."]
        #[inline(always)]
        pub fn set_majrev(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize);
        }
        #[doc = "Instance number."]
        #[inline(always)]
        pub const fn instnum(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0x0f;
            val as u8
        }
        #[doc = "Instance number."]
        #[inline(always)]
        pub fn set_instnum(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize);
        }
        #[doc = "Feature set."]
        #[inline(always)]
        pub const fn featurever(&self) -> u8 {
            let val = (self.0 >> 12usize) & 0x0f;
            val as u8
        }
        #[doc = "Feature set."]
        #[inline(always)]
        pub fn set_featurever(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize);
        }
        #[doc = "Module ID."]
        #[inline(always)]
        pub const fn moduleid(&self) -> u16 {
            let val = (self.0 >> 16usize) & 0xffff;
            val as u16
        }
        #[doc = "Module ID."]
        #[inline(always)]
        pub fn set_moduleid(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize);
        }
    }
    impl Default for Desc {
        #[inline(always)]
        fn default() -> Desc {
            Desc(0)
        }
    }
    #[doc = "Event Mode."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        #[doc = "Event line mode select for peripheral event."]
        #[inline(always)]
        pub const fn int0_cfg(&self) -> super::vals::Int0Cfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::Int0Cfg::from_bits(val as u8)
        }
        #[doc = "Event line mode select for peripheral event."]
        #[inline(always)]
        pub fn set_int0_cfg(&mut self, val: super::vals::Int0Cfg) {
            self.0 = (self.0 & !(0x03 << 0usize)) | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    #[doc = "Global Information Register 0."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Gblinfo0(pub u32);
    impl Gblinfo0 {
        #[doc = "Sector size in bytes."]
        #[inline(always)]
        pub const fn sectorsize(&self) -> super::vals::Sectorsize {
            let val = (self.0 >> 0usize) & 0xffff;
            super::vals::Sectorsize::from_bits(val as u16)
        }
        #[doc = "Sector size in bytes."]
        #[inline(always)]
        pub fn set_sectorsize(&mut self, val: super::vals::Sectorsize) {
            self.0 = (self.0 & !(0xffff << 0usize)) | (((val.to_bits() as u32) & 0xffff) << 0usize);
        }
        #[doc = "Number of banks instantiated Minimum: 1 Maximum: 5."]
        #[inline(always)]
        pub const fn numbanks(&self) -> super::vals::Numbanks {
            let val = (self.0 >> 16usize) & 0x07;
            super::vals::Numbanks::from_bits(val as u8)
        }
        #[doc = "Number of banks instantiated Minimum: 1 Maximum: 5."]
        #[inline(always)]
        pub fn set_numbanks(&mut self, val: super::vals::Numbanks) {
            self.0 = (self.0 & !(0x07 << 16usize)) | (((val.to_bits() as u32) & 0x07) << 16usize);
        }
    }
    impl Default for Gblinfo0 {
        #[inline(always)]
        fn default() -> Gblinfo0 {
            Gblinfo0(0)
        }
    }
    #[doc = "Global Information Register 1."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Gblinfo1(pub u32);
    impl Gblinfo1 {
        #[doc = "Data width in bits."]
        #[inline(always)]
        pub const fn datawidth(&self) -> super::vals::Datawidth {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::Datawidth::from_bits(val as u8)
        }
        #[doc = "Data width in bits."]
        #[inline(always)]
        pub fn set_datawidth(&mut self, val: super::vals::Datawidth) {
            self.0 = (self.0 & !(0xff << 0usize)) | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
        #[doc = "ECC data width in bits."]
        #[inline(always)]
        pub const fn eccwidth(&self) -> super::vals::Eccwidth {
            let val = (self.0 >> 8usize) & 0x1f;
            super::vals::Eccwidth::from_bits(val as u8)
        }
        #[doc = "ECC data width in bits."]
        #[inline(always)]
        pub fn set_eccwidth(&mut self, val: super::vals::Eccwidth) {
            self.0 = (self.0 & !(0x1f << 8usize)) | (((val.to_bits() as u32) & 0x1f) << 8usize);
        }
        #[doc = "Redundant data width in bits."]
        #[inline(always)]
        pub const fn redwidth(&self) -> super::vals::Redwidth {
            let val = (self.0 >> 16usize) & 0x07;
            super::vals::Redwidth::from_bits(val as u8)
        }
        #[doc = "Redundant data width in bits."]
        #[inline(always)]
        pub fn set_redwidth(&mut self, val: super::vals::Redwidth) {
            self.0 = (self.0 & !(0x07 << 16usize)) | (((val.to_bits() as u32) & 0x07) << 16usize);
        }
    }
    impl Default for Gblinfo1 {
        #[inline(always)]
        fn default() -> Gblinfo1 {
            Gblinfo1(0)
        }
    }
    #[doc = "Global Information Register 2."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Gblinfo2(pub u32);
    impl Gblinfo2 {
        #[doc = "Number of data registers present."]
        #[inline(always)]
        pub const fn dataregisters(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        #[doc = "Number of data registers present."]
        #[inline(always)]
        pub fn set_dataregisters(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
    }
    impl Default for Gblinfo2 {
        #[inline(always)]
        fn default() -> Gblinfo2 {
            Gblinfo2(0)
        }
    }
    #[doc = "Interrupt Index Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Iidx(pub u32);
    impl Iidx {
        #[doc = "Indicates which interrupt has fired. 0x0 means no event pending. The priority order is fixed. On each read, only one interrupt is indicated. On a read, the current interrupt (highest priority) is automatically cleared by the hardware and the corresponding interrupt flags in the RIS and MIS are cleared as well. After a read from the CPU (not from the debug interface), the register must be updated with the next highest priority interrupt."]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::Stat {
            let val = (self.0 >> 0usize) & 0x01;
            super::vals::Stat::from_bits(val as u8)
        }
        #[doc = "Indicates which interrupt has fired. 0x0 means no event pending. The priority order is fixed. On each read, only one interrupt is indicated. On a read, the current interrupt (highest priority) is automatically cleared by the hardware and the corresponding interrupt flags in the RIS and MIS are cleared as well. After a read from the CPU (not from the debug interface), the register must be updated with the next highest priority interrupt."]
        #[inline(always)]
        pub fn set_stat(&mut self, val: super::vals::Stat) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val.to_bits() as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Iidx {
        #[inline(always)]
        fn default() -> Iidx {
            Iidx(0)
        }
    }
    #[doc = "Interrupt Clear Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Int(pub u32);
    impl Int {
        #[doc = "0: No effect 1: Clear the DONE interrupt in the RIS register."]
        #[inline(always)]
        pub const fn done(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "0: No effect 1: Clear the DONE interrupt in the RIS register."]
        #[inline(always)]
        pub fn set_done(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Int {
        #[inline(always)]
        fn default() -> Int {
            Int(0)
        }
    }
    #[doc = "Address Status Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Stataddr(pub u32);
    impl Stataddr {
        #[doc = "Current Bank Address A bank offset address is stored in this register."]
        #[inline(always)]
        pub const fn bankaddr(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        #[doc = "Current Bank Address A bank offset address is stored in this register."]
        #[inline(always)]
        pub fn set_bankaddr(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize);
        }
        #[doc = "Current Region ID A region indicator is stored in this register which represents the current flash region on which the state machine is operating."]
        #[inline(always)]
        pub const fn regionid(&self) -> super::vals::Regionid {
            let val = (self.0 >> 16usize) & 0x1f;
            super::vals::Regionid::from_bits(val as u8)
        }
        #[doc = "Current Region ID A region indicator is stored in this register which represents the current flash region on which the state machine is operating."]
        #[inline(always)]
        pub fn set_regionid(&mut self, val: super::vals::Regionid) {
            self.0 = (self.0 & !(0x1f << 16usize)) | (((val.to_bits() as u32) & 0x1f) << 16usize);
        }
        #[doc = "Current Bank ID A bank indicator is stored in this register which represents the current bank on which the state machine is operating. There is 1 bit per bank."]
        #[inline(always)]
        pub const fn bankid(&self) -> super::vals::Bankid {
            let val = (self.0 >> 21usize) & 0x1f;
            super::vals::Bankid::from_bits(val as u8)
        }
        #[doc = "Current Bank ID A bank indicator is stored in this register which represents the current bank on which the state machine is operating. There is 1 bit per bank."]
        #[inline(always)]
        pub fn set_bankid(&mut self, val: super::vals::Bankid) {
            self.0 = (self.0 & !(0x1f << 21usize)) | (((val.to_bits() as u32) & 0x1f) << 21usize);
        }
    }
    impl Default for Stataddr {
        #[inline(always)]
        fn default() -> Stataddr {
            Stataddr(0)
        }
    }
    #[doc = "Command Status Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Statcmd(pub u32);
    impl Statcmd {
        #[doc = "Command Done."]
        #[inline(always)]
        pub const fn done(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "Command Done."]
        #[inline(always)]
        pub fn set_done(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        #[doc = "Command Pass - valid when CMD_DONE field is 1."]
        #[inline(always)]
        pub const fn pass(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        #[doc = "Command Pass - valid when CMD_DONE field is 1."]
        #[inline(always)]
        pub fn set_pass(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        #[doc = "Command In Progress."]
        #[inline(always)]
        pub const fn inprogress(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        #[doc = "Command In Progress."]
        #[inline(always)]
        pub fn set_inprogress(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        #[doc = "Command failed due to Write/Erase Protect Sector Violation."]
        #[inline(always)]
        pub const fn failweprot(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        #[doc = "Command failed due to Write/Erase Protect Sector Violation."]
        #[inline(always)]
        pub fn set_failweprot(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        #[doc = "Command failed due to verify error."]
        #[inline(always)]
        pub const fn failverify(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        #[doc = "Command failed due to verify error."]
        #[inline(always)]
        pub fn set_failverify(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        #[doc = "Command failed due to the use of an illegal address."]
        #[inline(always)]
        pub const fn faililladdr(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        #[doc = "Command failed due to the use of an illegal address."]
        #[inline(always)]
        pub fn set_faililladdr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        #[doc = "Command failed because a bank has been set to a mode other than READ. Program and Erase commands cannot be initiated unless all banks are in READ mode."]
        #[inline(always)]
        pub const fn failmode(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        #[doc = "Command failed because a bank has been set to a mode other than READ. Program and Erase commands cannot be initiated unless all banks are in READ mode."]
        #[inline(always)]
        pub fn set_failmode(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
        #[doc = "Program command failed because an attempt was made to program a stored 0 value to a 1."]
        #[inline(always)]
        pub const fn failinvdata(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        #[doc = "Program command failed because an attempt was made to program a stored 0 value to a 1."]
        #[inline(always)]
        pub fn set_failinvdata(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        #[doc = "Command failed due to error other than write/erase protect violation or verify error. This is an extra bit in case a new failure mechanism is added which requires a status bit."]
        #[inline(always)]
        pub const fn failmisc(&self) -> bool {
            let val = (self.0 >> 12usize) & 0x01;
            val != 0
        }
        #[doc = "Command failed due to error other than write/erase protect violation or verify error. This is an extra bit in case a new failure mechanism is added which requires a status bit."]
        #[inline(always)]
        pub fn set_failmisc(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize);
        }
    }
    impl Default for Statcmd {
        #[inline(always)]
        fn default() -> Statcmd {
            Statcmd(0)
        }
    }
    #[doc = "Mode Status Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Statmode(pub u32);
    impl Statmode {
        #[doc = "Bank not in read mode. Indicates which banks are not in READ mode. There is 1 bit per bank."]
        #[inline(always)]
        pub const fn banknotinrd(&self) -> super::vals::Bank {
            let val = (self.0 >> 0usize) & 0x1f;
            super::vals::Bank::from_bits(val as u8)
        }
        #[doc = "Bank not in read mode. Indicates which banks are not in READ mode. There is 1 bit per bank."]
        #[inline(always)]
        pub fn set_banknotinrd(&mut self, val: super::vals::Bank) {
            self.0 = (self.0 & !(0x1f << 0usize)) | (((val.to_bits() as u32) & 0x1f) << 0usize);
        }
        #[doc = "Indicates mode of bank(s) that are not in READ mode."]
        #[inline(always)]
        pub const fn bankmode(&self) -> super::vals::Mode {
            let val = (self.0 >> 8usize) & 0x0f;
            super::vals::Mode::from_bits(val as u8)
        }
        #[doc = "Indicates mode of bank(s) that are not in READ mode."]
        #[inline(always)]
        pub fn set_bankmode(&mut self, val: super::vals::Mode) {
            self.0 = (self.0 & !(0x0f << 8usize)) | (((val.to_bits() as u32) & 0x0f) << 8usize);
        }
        #[doc = "Bank 2T Ready. Bank(s) are ready for 2T access. This is accomplished when the pump has fully driven power rails to the bank(s)."]
        #[inline(always)]
        pub const fn bank2trdy(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        #[doc = "Bank 2T Ready. Bank(s) are ready for 2T access. This is accomplished when the pump has fully driven power rails to the bank(s)."]
        #[inline(always)]
        pub fn set_bank2trdy(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
        #[doc = "Bank 1T Ready. Bank(s) are ready for 1T access. This is accomplished when the bank and pump have been trimmed."]
        #[inline(always)]
        pub const fn bank1trdy(&self) -> bool {
            let val = (self.0 >> 17usize) & 0x01;
            val != 0
        }
        #[doc = "Bank 1T Ready. Bank(s) are ready for 1T access. This is accomplished when the bank and pump have been trimmed."]
        #[inline(always)]
        pub fn set_bank1trdy(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize);
        }
    }
    impl Default for Statmode {
        #[inline(always)]
        fn default() -> Statmode {
            Statmode(0)
        }
    }
    #[doc = "Pulse Count Status Register."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Statpcnt(pub u32);
    impl Statpcnt {
        #[doc = "Current Pulse Counter Value."]
        #[inline(always)]
        pub const fn pulsecnt(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0x0fff;
            val as u16
        }
        #[doc = "Current Pulse Counter Value."]
        #[inline(always)]
        pub fn set_pulsecnt(&mut self, val: u16) {
            self.0 = (self.0 & !(0x0fff << 0usize)) | (((val as u32) & 0x0fff) << 0usize);
        }
    }
    impl Default for Statpcnt {
        #[inline(always)]
        fn default() -> Statpcnt {
            Statpcnt(0)
        }
    }
}
pub mod vals {
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Bank(pub u8);
    impl Bank {
        #[doc = "Bank 0."]
        pub const BANK0: Self = Self(0x01);
        #[doc = "Bank 1."]
        pub const BANK1: Self = Self(0x02);
        #[doc = "Bank 2."]
        pub const BANK2: Self = Self(0x04);
        #[doc = "Bank 3."]
        pub const BANK3: Self = Self(0x08);
        #[doc = "Bank 4."]
        pub const BANK4: Self = Self(0x10);
    }
    impl Bank {
        pub const fn from_bits(val: u8) -> Bank {
            Self(val & 0x1f)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for Bank {
        #[inline(always)]
        fn from(val: u8) -> Bank {
            Bank::from_bits(val)
        }
    }
    impl From<Bank> for u8 {
        #[inline(always)]
        fn from(val: Bank) -> u8 {
            Bank::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Bankid(pub u8);
    impl Bankid {
        #[doc = "Bank 0."]
        pub const BANK0: Self = Self(0x01);
        #[doc = "Bank 1."]
        pub const BANK1: Self = Self(0x02);
        #[doc = "Bank 2."]
        pub const BANK2: Self = Self(0x04);
        #[doc = "Bank 3."]
        pub const BANK3: Self = Self(0x08);
        #[doc = "Bank 4."]
        pub const BANK4: Self = Self(0x10);
    }
    impl Bankid {
        pub const fn from_bits(val: u8) -> Bankid {
            Self(val & 0x1f)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for Bankid {
        #[inline(always)]
        fn from(val: u8) -> Bankid {
            Bankid::from_bits(val)
        }
    }
    impl From<Bankid> for u8 {
        #[inline(always)]
        fn from(val: Bankid) -> u8 {
            Bankid::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct BankinfoEngrsize(pub u8);
    impl BankinfoEngrsize {
        #[doc = "Minimum value of \\[ENGRSIZE\\]."]
        pub const MINSECTORS: Self = Self(0x0);
        #[doc = "Maximum value of \\[ENGRSIZE\\]."]
        pub const MAXSECTORS: Self = Self(0x20);
    }
    impl BankinfoEngrsize {
        pub const fn from_bits(val: u8) -> BankinfoEngrsize {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for BankinfoEngrsize {
        #[inline(always)]
        fn from(val: u8) -> BankinfoEngrsize {
            BankinfoEngrsize::from_bits(val)
        }
    }
    impl From<BankinfoEngrsize> for u8 {
        #[inline(always)]
        fn from(val: BankinfoEngrsize) -> u8 {
            BankinfoEngrsize::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct BankinfoMainsize(pub u16);
    impl BankinfoMainsize {
        #[doc = "Minimum value of \\[MAINSIZE\\]."]
        pub const MINSECTORS: Self = Self(0x08);
        #[doc = "Maximum value of \\[MAINSIZE\\]."]
        pub const MAXSECTORS: Self = Self(0x0200);
    }
    impl BankinfoMainsize {
        pub const fn from_bits(val: u16) -> BankinfoMainsize {
            Self(val & 0x0fff)
        }
        pub const fn to_bits(self) -> u16 {
            self.0
        }
    }
    impl From<u16> for BankinfoMainsize {
        #[inline(always)]
        fn from(val: u16) -> BankinfoMainsize {
            BankinfoMainsize::from_bits(val)
        }
    }
    impl From<BankinfoMainsize> for u16 {
        #[inline(always)]
        fn from(val: BankinfoMainsize) -> u16 {
            BankinfoMainsize::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct BankinfoNonmainsize(pub u8);
    impl BankinfoNonmainsize {
        #[doc = "Minimum value of \\[NONMAINSIZE\\]."]
        pub const MINSECTORS: Self = Self(0x0);
        #[doc = "Maximum value of \\[NONMAINSIZE\\]."]
        pub const MAXSECTORS: Self = Self(0x20);
    }
    impl BankinfoNonmainsize {
        pub const fn from_bits(val: u8) -> BankinfoNonmainsize {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for BankinfoNonmainsize {
        #[inline(always)]
        fn from(val: u8) -> BankinfoNonmainsize {
            BankinfoNonmainsize::from_bits(val)
        }
    }
    impl From<BankinfoNonmainsize> for u8 {
        #[inline(always)]
        fn from(val: BankinfoNonmainsize) -> u8 {
            BankinfoNonmainsize::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct BankinfoTrimsize(pub u8);
    impl BankinfoTrimsize {
        #[doc = "Minimum value of \\[TRIMSIZE\\]."]
        pub const MINSECTORS: Self = Self(0x0);
        #[doc = "Maximum value of \\[TRIMSIZE\\]."]
        pub const MAXSECTORS: Self = Self(0x20);
    }
    impl BankinfoTrimsize {
        pub const fn from_bits(val: u8) -> BankinfoTrimsize {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for BankinfoTrimsize {
        #[inline(always)]
        fn from(val: u8) -> BankinfoTrimsize {
            BankinfoTrimsize::from_bits(val)
        }
    }
    impl From<BankinfoTrimsize> for u8 {
        #[inline(always)]
        fn from(val: BankinfoTrimsize) -> u8 {
            BankinfoTrimsize::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Command {
        #[doc = "No Operation."]
        NOOP = 0x0,
        #[doc = "Program."]
        PROGRAM = 0x01,
        #[doc = "Erase."]
        ERASE = 0x02,
        #[doc = "Read Verify - Perform a standalone read verify operation."]
        READVERIFY = 0x03,
        #[doc = "Mode Change - Perform a mode change only, no other operation."]
        MODECHANGE = 0x04,
        #[doc = "Clear Status - Clear status bits in FW_SMSTAT only."]
        CLEARSTATUS = 0x05,
        #[doc = "Blank Verify - Check whether a flash word is in the erased state. This command may only be used with CMDTYPE.SIZE = ONEWORD."]
        BLANKVERIFY = 0x06,
        _RESERVED_7 = 0x07,
    }
    impl Command {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Command {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Command {
        #[inline(always)]
        fn from(val: u8) -> Command {
            Command::from_bits(val)
        }
    }
    impl From<Command> for u8 {
        #[inline(always)]
        fn from(val: Command) -> u8 {
            Command::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Datawidth(pub u8);
    impl Datawidth {
        #[doc = "Data width is 64 bits."]
        pub const W64BIT: Self = Self(0x40);
        #[doc = "Data width is 128 bits."]
        pub const W128BIT: Self = Self(0x80);
    }
    impl Datawidth {
        pub const fn from_bits(val: u8) -> Datawidth {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for Datawidth {
        #[inline(always)]
        fn from(val: u8) -> Datawidth {
            Datawidth::from_bits(val)
        }
    }
    impl From<Datawidth> for u8 {
        #[inline(always)]
        fn from(val: Datawidth) -> u8 {
            Datawidth::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Eccwidth(pub u8);
    impl Eccwidth {
        #[doc = "ECC data width is 0. ECC not used."]
        pub const W0BIT: Self = Self(0x0);
        #[doc = "ECC data width is 8 bits."]
        pub const W8BIT: Self = Self(0x08);
        #[doc = "ECC data width is 16 bits."]
        pub const W16BIT: Self = Self(0x10);
    }
    impl Eccwidth {
        pub const fn from_bits(val: u8) -> Eccwidth {
            Self(val & 0x1f)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for Eccwidth {
        #[inline(always)]
        fn from(val: u8) -> Eccwidth {
            Eccwidth::from_bits(val)
        }
    }
    impl From<Eccwidth> for u8 {
        #[inline(always)]
        fn from(val: Eccwidth) -> u8 {
            Eccwidth::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Int0Cfg {
        #[doc = "The interrupt or event line is disabled."]
        DISABLE = 0x0,
        #[doc = "The interrupt or event line is in software mode. Software must clear the RIS."]
        SOFTWARE = 0x01,
        #[doc = "The interrupt or event line is in hardware mode. Hardware must clear the RIS."]
        HARDWARE = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl Int0Cfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Int0Cfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Int0Cfg {
        #[inline(always)]
        fn from(val: u8) -> Int0Cfg {
            Int0Cfg::from_bits(val)
        }
    }
    impl From<Int0Cfg> for u8 {
        #[inline(always)]
        fn from(val: Int0Cfg) -> u8 {
            Int0Cfg::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Mode {
        #[doc = "Read Mode."]
        READ = 0x0,
        _RESERVED_1 = 0x01,
        #[doc = "Read Margin 0 Mode."]
        RDMARG0 = 0x02,
        _RESERVED_3 = 0x03,
        #[doc = "Read Margin 1 Mode."]
        RDMARG1 = 0x04,
        _RESERVED_5 = 0x05,
        #[doc = "Read Margin 0B Mode."]
        RDMARG0B = 0x06,
        #[doc = "Read Margin 1B Mode."]
        RDMARG1B = 0x07,
        _RESERVED_8 = 0x08,
        #[doc = "Program Verify Mode."]
        PGMVER = 0x09,
        #[doc = "Program Single Word."]
        PGMSW = 0x0a,
        #[doc = "Erase Verify Mode."]
        ERASEVER = 0x0b,
        #[doc = "Erase Sector."]
        ERASESECT = 0x0c,
        _RESERVED_d = 0x0d,
        #[doc = "Program Multiple Word."]
        PGMMW = 0x0e,
        #[doc = "Erase Bank."]
        ERASEBNK = 0x0f,
    }
    impl Mode {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Mode {
            unsafe { core::mem::transmute(val & 0x0f) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Mode {
        #[inline(always)]
        fn from(val: u8) -> Mode {
            Mode::from_bits(val)
        }
    }
    impl From<Mode> for u8 {
        #[inline(always)]
        fn from(val: Mode) -> u8 {
            Mode::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Numbanks {
        _RESERVED_0 = 0x0,
        MINBANKS = 0x01,
        _RESERVED_2 = 0x02,
        _RESERVED_3 = 0x03,
        _RESERVED_4 = 0x04,
        MAXBANKS = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
    }
    impl Numbanks {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Numbanks {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Numbanks {
        #[inline(always)]
        fn from(val: u8) -> Numbanks {
            Numbanks::from_bits(val)
        }
    }
    impl From<Numbanks> for u8 {
        #[inline(always)]
        fn from(val: Numbanks) -> u8 {
            Numbanks::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Redwidth {
        #[doc = "Redundant data width is 0. Redundancy/Repair not present."]
        W0BIT = 0x0,
        _RESERVED_1 = 0x01,
        #[doc = "Redundant data width is 2 bits."]
        W2BIT = 0x02,
        _RESERVED_3 = 0x03,
        #[doc = "Redundant data width is 4 bits."]
        W4BIT = 0x04,
        _RESERVED_5 = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
    }
    impl Redwidth {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Redwidth {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Redwidth {
        #[inline(always)]
        fn from(val: u8) -> Redwidth {
            Redwidth::from_bits(val)
        }
    }
    impl From<Redwidth> for u8 {
        #[inline(always)]
        fn from(val: Redwidth) -> u8 {
            Redwidth::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Regionid(pub u8);
    impl Regionid {
        #[doc = "Main Region."]
        pub const MAIN: Self = Self(0x01);
        #[doc = "Non-Main Region."]
        pub const NONMAIN: Self = Self(0x02);
        #[doc = "Trim Region."]
        pub const TRIM: Self = Self(0x04);
        #[doc = "Engr Region."]
        pub const ENGR: Self = Self(0x08);
    }
    impl Regionid {
        pub const fn from_bits(val: u8) -> Regionid {
            Self(val & 0x1f)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl From<u8> for Regionid {
        #[inline(always)]
        fn from(val: u8) -> Regionid {
            Regionid::from_bits(val)
        }
    }
    impl From<Regionid> for u8 {
        #[inline(always)]
        fn from(val: Regionid) -> u8 {
            Regionid::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Regionsel {
        _RESERVED_0 = 0x0,
        #[doc = "Main Region."]
        MAIN = 0x01,
        #[doc = "Non-Main Region."]
        NONMAIN = 0x02,
        _RESERVED_3 = 0x03,
        #[doc = "Trim Region."]
        TRIM = 0x04,
        _RESERVED_5 = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
        #[doc = "Engr Region."]
        ENGR = 0x08,
        _RESERVED_9 = 0x09,
        _RESERVED_a = 0x0a,
        _RESERVED_b = 0x0b,
        _RESERVED_c = 0x0c,
        _RESERVED_d = 0x0d,
        _RESERVED_e = 0x0e,
        _RESERVED_f = 0x0f,
    }
    impl Regionsel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Regionsel {
            unsafe { core::mem::transmute(val & 0x0f) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Regionsel {
        #[inline(always)]
        fn from(val: u8) -> Regionsel {
            Regionsel::from_bits(val)
        }
    }
    impl From<Regionsel> for u8 {
        #[inline(always)]
        fn from(val: Regionsel) -> u8 {
            Regionsel::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct Sectorsize(pub u16);
    impl Sectorsize {
        #[doc = "Sector size is ONEKB."]
        pub const ONEKB: Self = Self(0x0400);
        #[doc = "Sector size is TWOKB."]
        pub const TWOKB: Self = Self(0x0800);
    }
    impl Sectorsize {
        pub const fn from_bits(val: u16) -> Sectorsize {
            Self(val & 0xffff)
        }
        pub const fn to_bits(self) -> u16 {
            self.0
        }
    }
    impl From<u16> for Sectorsize {
        #[inline(always)]
        fn from(val: u16) -> Sectorsize {
            Sectorsize::from_bits(val)
        }
    }
    impl From<Sectorsize> for u16 {
        #[inline(always)]
        fn from(val: Sectorsize) -> u16 {
            Sectorsize::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Size {
        #[doc = "Operate on 1 flash word."]
        ONEWORD = 0x0,
        #[doc = "Operate on 2 flash words."]
        TWOWORD = 0x01,
        #[doc = "Operate on 4 flash words."]
        FOURWORD = 0x02,
        #[doc = "Operate on 8 flash words."]
        EIGHTWORD = 0x03,
        #[doc = "Operate on a flash sector."]
        SECTOR = 0x04,
        #[doc = "Operate on an entire flash bank."]
        BANK = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
    }
    impl Size {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Size {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Size {
        #[inline(always)]
        fn from(val: u8) -> Size {
            Size::from_bits(val)
        }
    }
    impl From<Size> for u8 {
        #[inline(always)]
        fn from(val: Size) -> u8 {
            Size::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub enum Stat {
        #[doc = "No Interrupt Pending."]
        NO_INTR = 0x0,
        #[doc = "DONE Interrupt Pending."]
        DONE = 0x01,
    }
    impl Stat {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Stat {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Stat {
        #[inline(always)]
        fn from(val: u8) -> Stat {
            Stat::from_bits(val)
        }
    }
    impl From<Stat> for u8 {
        #[inline(always)]
        fn from(val: Stat) -> u8 {
            Stat::to_bits(val)
        }
    }
}
