// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CpuInt {
    ptr: *mut u8,
}
unsafe impl Send for CpuInt {}
unsafe impl Sync for CpuInt {}
impl CpuInt {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt Index Register.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::CpuIntIidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::CpuInt, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::CpuInt, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::CpuInt, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::CpuInt, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::CpuInt, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct DmaTrigRx {
    ptr: *mut u8,
}
unsafe impl Send for DmaTrigRx {}
unsafe impl Sync for DmaTrigRx {}
impl DmaTrigRx {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt Index Register.
    #[inline(always)]
    pub const fn iidx(
        self,
    ) -> crate::common::Reg<regs::DmaTrigRxIidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::DmaTrigRx, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::DmaTrigRx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::DmaTrigRx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::DmaTrigRx, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::DmaTrigRx, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct DmaTrigTx {
    ptr: *mut u8,
}
unsafe impl Send for DmaTrigTx {}
unsafe impl Sync for DmaTrigTx {}
impl DmaTrigTx {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt Index Register.
    #[inline(always)]
    pub const fn iidx(
        self,
    ) -> crate::common::Reg<regs::DmaTrigTxIidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::DmaTrigTx, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::DmaTrigTx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::DmaTrigTx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::DmaTrigTx, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::DmaTrigTx, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Gprcm {
    ptr: *mut u8,
}
unsafe impl Send for Gprcm {}
unsafe impl Sync for Gprcm {}
impl Gprcm {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Power enable.
    #[inline(always)]
    pub const fn pwren(self) -> crate::common::Reg<regs::Pwren, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Reset Control.
    #[inline(always)]
    pub const fn rstctl(self) -> crate::common::Reg<regs::Rstctl, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///Peripheral Clock Configuration Register.
    #[inline(always)]
    pub const fn clkcfg(self) -> crate::common::Reg<regs::Clkcfg, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Status Register.
    #[inline(always)]
    pub const fn gprcm_stat(
        self,
    ) -> crate::common::Reg<regs::GprcmStat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
    }
}
///PERIPHERALREGION.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Spi {
    ptr: *mut u8,
}
unsafe impl Send for Spi {}
unsafe impl Sync for Spi {}
impl Spi {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    #[inline(always)]
    pub const fn gprcm(self, n: usize) -> Gprcm {
        assert!(n < 1usize);
        unsafe { Gprcm::from_ptr(self.ptr.wrapping_add(0x0800usize + n * 24usize) as _) }
    }
    ///Clock Divider.
    #[inline(always)]
    pub const fn clkdiv(self) -> crate::common::Reg<regs::Clkdiv, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1000usize) as _) }
    }
    ///Clock Select for Ultra Low Power peripherals.
    #[inline(always)]
    pub const fn clksel(self) -> crate::common::Reg<regs::Clksel, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1004usize) as _) }
    }
    ///Peripheral Debug Control.
    #[inline(always)]
    pub const fn pdbgctl(self) -> crate::common::Reg<regs::Pdbgctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1018usize) as _) }
    }
    #[inline(always)]
    pub const fn cpu_int(self, n: usize) -> CpuInt {
        assert!(n < 1usize);
        unsafe {
            CpuInt::from_ptr(self.ptr.wrapping_add(0x1020usize + n * 44usize) as _)
        }
    }
    #[inline(always)]
    pub const fn dma_trig_rx(self, n: usize) -> DmaTrigRx {
        assert!(n < 1usize);
        unsafe {
            DmaTrigRx::from_ptr(self.ptr.wrapping_add(0x1050usize + n * 44usize) as _)
        }
    }
    #[inline(always)]
    pub const fn dma_trig_tx(self, n: usize) -> DmaTrigTx {
        assert!(n < 1usize);
        unsafe {
            DmaTrigTx::from_ptr(self.ptr.wrapping_add(0x1080usize + n * 44usize) as _)
        }
    }
    ///Event Mode.
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e0usize) as _) }
    }
    ///Interrupt control register.
    #[inline(always)]
    pub const fn intctl(self) -> crate::common::Reg<regs::Intctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e4usize) as _) }
    }
    ///SPI control register 0.
    #[inline(always)]
    pub const fn ctl0(self) -> crate::common::Reg<regs::Ctl0, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1100usize) as _) }
    }
    ///SPI control register 1.
    #[inline(always)]
    pub const fn ctl1(self) -> crate::common::Reg<regs::Ctl1, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1104usize) as _) }
    }
    ///Clock prescaler and divider register.
    #[inline(always)]
    pub const fn clkctl(self) -> crate::common::Reg<regs::Clkctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1108usize) as _) }
    }
    ///Interrupt FIFO Level Select Register.
    #[inline(always)]
    pub const fn ifls(self) -> crate::common::Reg<regs::Ifls, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x110cusize) as _) }
    }
    ///Status Register.
    #[inline(always)]
    pub const fn stat(self) -> crate::common::Reg<regs::Stat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1110usize) as _) }
    }
    ///RXDATA Register.
    #[inline(always)]
    pub const fn rxdata(self) -> crate::common::Reg<regs::Rxdata, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1130usize) as _) }
    }
    ///TXDATA Register.
    #[inline(always)]
    pub const fn txdata(self) -> crate::common::Reg<regs::Txdata, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1140usize) as _) }
    }
}
pub mod regs {
    ///Peripheral Clock Configuration Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Clkcfg(pub u32);
    impl Clkcfg {
        ///Async Clock Request is blocked from starting SYSOSC or forcing bus clock to 32MHz.
        #[must_use]
        #[inline(always)]
        pub const fn blockasync(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///Async Clock Request is blocked from starting SYSOSC or forcing bus clock to 32MHz.
        #[inline(always)]
        pub const fn set_blockasync(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        ///KEY to Allow State Change A9h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::ClkcfgKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::ClkcfgKey::from_bits(val as u8)
        }
        ///KEY to Allow State Change A9h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::ClkcfgKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Clkcfg {
        #[inline(always)]
        fn default() -> Clkcfg {
            Clkcfg(0)
        }
    }
    impl core::fmt::Debug for Clkcfg {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Clkcfg")
                .field("blockasync", &self.blockasync())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Clkcfg {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Clkcfg {{ blockasync: {=bool:?}, key: {:?} }}", self.blockasync(),
                self.key()
            )
        }
    }
    ///Clock prescaler and divider register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Clkctl(pub u32);
    impl Clkctl {
        ///Serial clock divider: This is used to generate the transmit and receive bit rate of the SPI. The SPI bit rate is (SPI's functional clock frequency)/((SCR+1)*2). SCR is a value from 0-1023.
        #[must_use]
        #[inline(always)]
        pub const fn scr(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0x03ff;
            val as u16
        }
        ///Serial clock divider: This is used to generate the transmit and receive bit rate of the SPI. The SPI bit rate is (SPI's functional clock frequency)/((SCR+1)*2). SCR is a value from 0-1023.
        #[inline(always)]
        pub const fn set_scr(&mut self, val: u16) {
            self.0 = (self.0 & !(0x03ff << 0usize))
                | (((val as u32) & 0x03ff) << 0usize);
        }
        ///Delayed sampling value. In controller mode the data on the input pin will be delayed sampled by the defined clock cycles of internal functional clock hence relaxing the setup time of input data. This setting is useful in systems where the board delays and external peripheral delays are more than the input setup time of the controller. Please refer to the datasheet for values of controller input setup time and assess what DSAMPLE value meets the requirement of the system. Note: High values of DSAMPLE can cause HOLD time violations and must be factored in the calculations.
        #[must_use]
        #[inline(always)]
        pub const fn dsample(&self) -> u8 {
            let val = (self.0 >> 28usize) & 0x0f;
            val as u8
        }
        ///Delayed sampling value. In controller mode the data on the input pin will be delayed sampled by the defined clock cycles of internal functional clock hence relaxing the setup time of input data. This setting is useful in systems where the board delays and external peripheral delays are more than the input setup time of the controller. Please refer to the datasheet for values of controller input setup time and assess what DSAMPLE value meets the requirement of the system. Note: High values of DSAMPLE can cause HOLD time violations and must be factored in the calculations.
        #[inline(always)]
        pub const fn set_dsample(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize);
        }
    }
    impl Default for Clkctl {
        #[inline(always)]
        fn default() -> Clkctl {
            Clkctl(0)
        }
    }
    impl core::fmt::Debug for Clkctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Clkctl")
                .field("scr", &self.scr())
                .field("dsample", &self.dsample())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Clkctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Clkctl {{ scr: {=u16:?}, dsample: {=u8:?} }}", self.scr(), self
                .dsample()
            )
        }
    }
    ///Clock Divider.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Clkdiv(pub u32);
    impl Clkdiv {
        ///Selects divide ratio of module clock.
        #[must_use]
        #[inline(always)]
        pub const fn ratio(&self) -> super::vals::Ratio {
            let val = (self.0 >> 0usize) & 0x07;
            super::vals::Ratio::from_bits(val as u8)
        }
        ///Selects divide ratio of module clock.
        #[inline(always)]
        pub const fn set_ratio(&mut self, val: super::vals::Ratio) {
            self.0 = (self.0 & !(0x07 << 0usize))
                | (((val.to_bits() as u32) & 0x07) << 0usize);
        }
    }
    impl Default for Clkdiv {
        #[inline(always)]
        fn default() -> Clkdiv {
            Clkdiv(0)
        }
    }
    impl core::fmt::Debug for Clkdiv {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Clkdiv").field("ratio", &self.ratio()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Clkdiv {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Clkdiv {{ ratio: {:?} }}", self.ratio())
        }
    }
    ///Clock Select for Ultra Low Power peripherals.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Clksel(pub u32);
    impl Clksel {
        ///Selects LFCLK as clock source if enabled.
        #[must_use]
        #[inline(always)]
        pub const fn lfclk_sel(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Selects LFCLK as clock source if enabled.
        #[inline(always)]
        pub const fn set_lfclk_sel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Selects MFCLK as clock source if enabled.
        #[must_use]
        #[inline(always)]
        pub const fn mfclk_sel(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Selects MFCLK as clock source if enabled.
        #[inline(always)]
        pub const fn set_mfclk_sel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Selects SYSCLK as clock source if enabled.
        #[must_use]
        #[inline(always)]
        pub const fn sysclk_sel(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Selects SYSCLK as clock source if enabled.
        #[inline(always)]
        pub const fn set_sysclk_sel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for Clksel {
        #[inline(always)]
        fn default() -> Clksel {
            Clksel(0)
        }
    }
    impl core::fmt::Debug for Clksel {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Clksel")
                .field("lfclk_sel", &self.lfclk_sel())
                .field("mfclk_sel", &self.mfclk_sel())
                .field("sysclk_sel", &self.sysclk_sel())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Clksel {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Clksel {{ lfclk_sel: {=bool:?}, mfclk_sel: {=bool:?}, sysclk_sel: {=bool:?} }}",
                self.lfclk_sel(), self.mfclk_sel(), self.sysclk_sel()
            )
        }
    }
    ///Interrupt clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct CpuInt(pub u32);
    impl CpuInt {
        ///Clear RXFIFO overflow event.
        #[must_use]
        #[inline(always)]
        pub const fn rxfifo_ovf(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Clear RXFIFO overflow event.
        #[inline(always)]
        pub const fn set_rxfifo_ovf(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Clear Parity error event.
        #[must_use]
        #[inline(always)]
        pub const fn per(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Clear Parity error event.
        #[inline(always)]
        pub const fn set_per(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Clear SPI Receive Time-Out Event.
        #[must_use]
        #[inline(always)]
        pub const fn rtout(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Clear SPI Receive Time-Out Event.
        #[inline(always)]
        pub const fn set_rtout(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Clear Receive FIFO event.
        #[must_use]
        #[inline(always)]
        pub const fn rx(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Clear Receive FIFO event.
        #[inline(always)]
        pub const fn set_rx(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Clear Transmit FIFO event.
        #[must_use]
        #[inline(always)]
        pub const fn tx(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Clear Transmit FIFO event.
        #[inline(always)]
        pub const fn set_tx(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Clear Transmit FIFO Empty event.
        #[must_use]
        #[inline(always)]
        pub const fn txempty(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        ///Clear Transmit FIFO Empty event.
        #[inline(always)]
        pub const fn set_txempty(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        ///Clear SPI IDLE mode event.
        #[must_use]
        #[inline(always)]
        pub const fn idle(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        ///Clear SPI IDLE mode event.
        #[inline(always)]
        pub const fn set_idle(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        ///Clear DMA Done 1 event for RX.
        #[must_use]
        #[inline(always)]
        pub const fn dma_done_rx(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        ///Clear DMA Done 1 event for RX.
        #[inline(always)]
        pub const fn set_dma_done_rx(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
        ///Clear DMA Done 1 event for TX.
        #[must_use]
        #[inline(always)]
        pub const fn dma_done_tx(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///Clear DMA Done 1 event for TX.
        #[inline(always)]
        pub const fn set_dma_done_tx(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        ///Clear TXFIFO underflow event.
        #[must_use]
        #[inline(always)]
        pub const fn txfifo_unf(&self) -> bool {
            let val = (self.0 >> 9usize) & 0x01;
            val != 0
        }
        ///Clear TXFIFO underflow event.
        #[inline(always)]
        pub const fn set_txfifo_unf(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize);
        }
        ///Clear RX FIFO underflow event.
        #[must_use]
        #[inline(always)]
        pub const fn rxfull(&self) -> bool {
            let val = (self.0 >> 10usize) & 0x01;
            val != 0
        }
        ///Clear RX FIFO underflow event.
        #[inline(always)]
        pub const fn set_rxfull(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize);
        }
    }
    impl Default for CpuInt {
        #[inline(always)]
        fn default() -> CpuInt {
            CpuInt(0)
        }
    }
    impl core::fmt::Debug for CpuInt {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("CpuInt")
                .field("rxfifo_ovf", &self.rxfifo_ovf())
                .field("per", &self.per())
                .field("rtout", &self.rtout())
                .field("rx", &self.rx())
                .field("tx", &self.tx())
                .field("txempty", &self.txempty())
                .field("idle", &self.idle())
                .field("dma_done_rx", &self.dma_done_rx())
                .field("dma_done_tx", &self.dma_done_tx())
                .field("txfifo_unf", &self.txfifo_unf())
                .field("rxfull", &self.rxfull())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for CpuInt {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "CpuInt {{ rxfifo_ovf: {=bool:?}, per: {=bool:?}, rtout: {=bool:?}, rx: {=bool:?}, tx: {=bool:?}, txempty: {=bool:?}, idle: {=bool:?}, dma_done_rx: {=bool:?}, dma_done_tx: {=bool:?}, txfifo_unf: {=bool:?}, rxfull: {=bool:?} }}",
                self.rxfifo_ovf(), self.per(), self.rtout(), self.rx(), self.tx(), self
                .txempty(), self.idle(), self.dma_done_rx(), self.dma_done_tx(), self
                .txfifo_unf(), self.rxfull()
            )
        }
    }
    ///Interrupt Index Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct CpuIntIidx(pub u32);
    impl CpuIntIidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::CpuIntIidxStat {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::CpuIntIidxStat::from_bits(val as u8)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::CpuIntIidxStat) {
            self.0 = (self.0 & !(0xff << 0usize))
                | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
    }
    impl Default for CpuIntIidx {
        #[inline(always)]
        fn default() -> CpuIntIidx {
            CpuIntIidx(0)
        }
    }
    impl core::fmt::Debug for CpuIntIidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("CpuIntIidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for CpuIntIidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "CpuIntIidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///SPI control register 0.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl0(pub u32);
    impl Ctl0 {
        ///Data Size Select. Values 0 - 2 are reserved and shall not be used. 3h = 4_BIT : 4-bit data SPI allows only values up to 16 Bit.
        #[must_use]
        #[inline(always)]
        pub const fn dss(&self) -> super::vals::Dss {
            let val = (self.0 >> 0usize) & 0x1f;
            super::vals::Dss::from_bits(val as u8)
        }
        ///Data Size Select. Values 0 - 2 are reserved and shall not be used. 3h = 4_BIT : 4-bit data SPI allows only values up to 16 Bit.
        #[inline(always)]
        pub const fn set_dss(&mut self, val: super::vals::Dss) {
            self.0 = (self.0 & !(0x1f << 0usize))
                | (((val.to_bits() as u32) & 0x1f) << 0usize);
        }
        ///Frame format Select.
        #[must_use]
        #[inline(always)]
        pub const fn frf(&self) -> super::vals::Frf {
            let val = (self.0 >> 5usize) & 0x03;
            super::vals::Frf::from_bits(val as u8)
        }
        ///Frame format Select.
        #[inline(always)]
        pub const fn set_frf(&mut self, val: super::vals::Frf) {
            self.0 = (self.0 & !(0x03 << 5usize))
                | (((val.to_bits() as u32) & 0x03) << 5usize);
        }
        ///Packing Enable. When 1, packing feature is enabled inside the IP When 0, packing feature is disabled inside the IP.
        #[must_use]
        #[inline(always)]
        pub const fn packen(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        ///Packing Enable. When 1, packing feature is enabled inside the IP When 0, packing feature is disabled inside the IP.
        #[inline(always)]
        pub const fn set_packen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
        ///CLKOUT polarity (Motorola SPI frame format only).
        #[must_use]
        #[inline(always)]
        pub const fn spo(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///CLKOUT polarity (Motorola SPI frame format only).
        #[inline(always)]
        pub const fn set_spo(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        ///CLKOUT phase (Motorola SPI frame format only) This bit selects the clock edge that captures data and enables it to change state. It has the most impact on the first bit transmitted by either permitting or not permitting a clock transition before the first data capture edge.
        #[must_use]
        #[inline(always)]
        pub const fn sph(&self) -> super::vals::Sph {
            let val = (self.0 >> 9usize) & 0x01;
            super::vals::Sph::from_bits(val as u8)
        }
        ///CLKOUT phase (Motorola SPI frame format only) This bit selects the clock edge that captures data and enables it to change state. It has the most impact on the first bit transmitted by either permitting or not permitting a clock transition before the first data capture edge.
        #[inline(always)]
        pub const fn set_sph(&mut self, val: super::vals::Sph) {
            self.0 = (self.0 & !(0x01 << 9usize))
                | (((val.to_bits() as u32) & 0x01) << 9usize);
        }
        ///Select the CS line to control on data transfer This bit is applicable for both controller/target mode.
        #[must_use]
        #[inline(always)]
        pub const fn cssel(&self) -> super::vals::Cssel {
            let val = (self.0 >> 12usize) & 0x03;
            super::vals::Cssel::from_bits(val as u8)
        }
        ///Select the CS line to control on data transfer This bit is applicable for both controller/target mode.
        #[inline(always)]
        pub const fn set_cssel(&mut self, val: super::vals::Cssel) {
            self.0 = (self.0 & !(0x03 << 12usize))
                | (((val.to_bits() as u32) & 0x03) << 12usize);
        }
        ///Clear shift register counter on CS inactive This bit is relevant only in the peripheral, CTL1.CP=0.
        #[must_use]
        #[inline(always)]
        pub const fn csclr(&self) -> bool {
            let val = (self.0 >> 14usize) & 0x01;
            val != 0
        }
        ///Clear shift register counter on CS inactive This bit is relevant only in the peripheral, CTL1.CP=0.
        #[inline(always)]
        pub const fn set_csclr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize);
        }
    }
    impl Default for Ctl0 {
        #[inline(always)]
        fn default() -> Ctl0 {
            Ctl0(0)
        }
    }
    impl core::fmt::Debug for Ctl0 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl0")
                .field("dss", &self.dss())
                .field("frf", &self.frf())
                .field("packen", &self.packen())
                .field("spo", &self.spo())
                .field("sph", &self.sph())
                .field("cssel", &self.cssel())
                .field("csclr", &self.csclr())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl0 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl0 {{ dss: {:?}, frf: {:?}, packen: {=bool:?}, spo: {=bool:?}, sph: {:?}, cssel: {:?}, csclr: {=bool:?} }}",
                self.dss(), self.frf(), self.packen(), self.spo(), self.sph(), self
                .cssel(), self.csclr()
            )
        }
    }
    ///SPI control register 1.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl1(pub u32);
    impl Ctl1 {
        ///SPI enable.
        #[must_use]
        #[inline(always)]
        pub const fn enable(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///SPI enable.
        #[inline(always)]
        pub const fn set_enable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Loop back mode.
        #[must_use]
        #[inline(always)]
        pub const fn lbm(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Loop back mode.
        #[inline(always)]
        pub const fn set_lbm(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Controller or peripheral mode select. This bit can be modified only when SPI is disabled, CTL1.ENABLE=0.
        #[must_use]
        #[inline(always)]
        pub const fn cp(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Controller or peripheral mode select. This bit can be modified only when SPI is disabled, CTL1.ENABLE=0.
        #[inline(always)]
        pub const fn set_cp(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Peripheral-mode: Data output disabled This bit is relevant only in Peripheral mode. In multiple-peripheral system topologies, SPI controller can broadcast a message to all peripherals, while only one peripheral drives the line. POD can be used by the SPI peripheral to disable driving data on the line.
        #[must_use]
        #[inline(always)]
        pub const fn pod(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Peripheral-mode: Data output disabled This bit is relevant only in Peripheral mode. In multiple-peripheral system topologies, SPI controller can broadcast a message to all peripherals, while only one peripheral drives the line. POD can be used by the SPI peripheral to disable driving data on the line.
        #[inline(always)]
        pub const fn set_pod(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///MSB first select. Controls the direction of the receive and transmit shift register.
        #[must_use]
        #[inline(always)]
        pub const fn msb(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///MSB first select. Controls the direction of the receive and transmit shift register.
        #[inline(always)]
        pub const fn set_msb(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Parity receive enable If enabled, parity reception check will be done for both controller and peripheral modes In case of a parity miss-match the parity error flag RIS.PER will be set.
        #[must_use]
        #[inline(always)]
        pub const fn pren(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        ///Parity receive enable If enabled, parity reception check will be done for both controller and peripheral modes In case of a parity miss-match the parity error flag RIS.PER will be set.
        #[inline(always)]
        pub const fn set_pren(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        ///Even Parity Select.
        #[must_use]
        #[inline(always)]
        pub const fn pes(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        ///Even Parity Select.
        #[inline(always)]
        pub const fn set_pes(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        ///Parity transmit enable If enabled, parity transmission will be done for both controller and peripheral modes.
        #[must_use]
        #[inline(always)]
        pub const fn pten(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///Parity transmit enable If enabled, parity transmission will be done for both controller and peripheral modes.
        #[inline(always)]
        pub const fn set_pten(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
        ///Command/Data Mode enable.
        #[must_use]
        #[inline(always)]
        pub const fn cdenable(&self) -> bool {
            let val = (self.0 >> 11usize) & 0x01;
            val != 0
        }
        ///Command/Data Mode enable.
        #[inline(always)]
        pub const fn set_cdenable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize);
        }
        ///Command/Data Mode Value When CTL1.CDENABLE is 1, CS3 line is used as C/D signal to distinguish between Command (C/D low) and Data (C/D high) information. When a value is written into the CTL1.CDMODE bits, the C/D (CS3) line will go low for the given numbers of byte which are sent by the SPI, starting with the next value to be transmitted after which, C/D line will go high automatically 0: Manual mode with C/D signal as High 1-14: C/D is low while this number of bytes are being sent after which, this field sets to 0 and C/D goes high. Reading this field at any time returns the remaining number of command bytes. 15: Manual mode with C/D signal as Low.
        #[must_use]
        #[inline(always)]
        pub const fn cdmode(&self) -> super::vals::Cdmode {
            let val = (self.0 >> 12usize) & 0x0f;
            super::vals::Cdmode::from_bits(val as u8)
        }
        ///Command/Data Mode Value When CTL1.CDENABLE is 1, CS3 line is used as C/D signal to distinguish between Command (C/D low) and Data (C/D high) information. When a value is written into the CTL1.CDMODE bits, the C/D (CS3) line will go low for the given numbers of byte which are sent by the SPI, starting with the next value to be transmitted after which, C/D line will go high automatically 0: Manual mode with C/D signal as High 1-14: C/D is low while this number of bytes are being sent after which, this field sets to 0 and C/D goes high. Reading this field at any time returns the remaining number of command bytes. 15: Manual mode with C/D signal as Low.
        #[inline(always)]
        pub const fn set_cdmode(&mut self, val: super::vals::Cdmode) {
            self.0 = (self.0 & !(0x0f << 12usize))
                | (((val.to_bits() as u32) & 0x0f) << 12usize);
        }
        ///Counter to repeat last transfer 0: repeat last transfer is disabled. x: repeat the last transfer with the given number. The transfer will be started with writing a data into the TX Buffer. Sending the data will be repeated with the given value, so the data will be transferred X+1 times in total. The behavior is identical as if the data would be written into the TX Buffer that many times as defined by the value here. It can be used to clean a transfer or to pull a certain amount of data by a peripheral.
        #[must_use]
        #[inline(always)]
        pub const fn repeattx(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0xff;
            val as u8
        }
        ///Counter to repeat last transfer 0: repeat last transfer is disabled. x: repeat the last transfer with the given number. The transfer will be started with writing a data into the TX Buffer. Sending the data will be repeated with the given value, so the data will be transferred X+1 times in total. The behavior is identical as if the data would be written into the TX Buffer that many times as defined by the value here. It can be used to clean a transfer or to pull a certain amount of data by a peripheral.
        #[inline(always)]
        pub const fn set_repeattx(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 16usize)) | (((val as u32) & 0xff) << 16usize);
        }
        ///Receive Timeout (only for Peripheral mode) Defines the number of Clock Cycles before after which the Receive Timeout flag RTOUT is set. The time is calculated using the control register for the clock selection and divider in the Controller mode configuration. A value of 0 disables this function.
        #[must_use]
        #[inline(always)]
        pub const fn rxtimeout(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0x3f;
            val as u8
        }
        ///Receive Timeout (only for Peripheral mode) Defines the number of Clock Cycles before after which the Receive Timeout flag RTOUT is set. The time is calculated using the control register for the clock selection and divider in the Controller mode configuration. A value of 0 disables this function.
        #[inline(always)]
        pub const fn set_rxtimeout(&mut self, val: u8) {
            self.0 = (self.0 & !(0x3f << 24usize)) | (((val as u32) & 0x3f) << 24usize);
        }
    }
    impl Default for Ctl1 {
        #[inline(always)]
        fn default() -> Ctl1 {
            Ctl1(0)
        }
    }
    impl core::fmt::Debug for Ctl1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl1")
                .field("enable", &self.enable())
                .field("lbm", &self.lbm())
                .field("cp", &self.cp())
                .field("pod", &self.pod())
                .field("msb", &self.msb())
                .field("pren", &self.pren())
                .field("pes", &self.pes())
                .field("pten", &self.pten())
                .field("cdenable", &self.cdenable())
                .field("cdmode", &self.cdmode())
                .field("repeattx", &self.repeattx())
                .field("rxtimeout", &self.rxtimeout())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl1 {{ enable: {=bool:?}, lbm: {=bool:?}, cp: {=bool:?}, pod: {=bool:?}, msb: {=bool:?}, pren: {=bool:?}, pes: {=bool:?}, pten: {=bool:?}, cdenable: {=bool:?}, cdmode: {:?}, repeattx: {=u8:?}, rxtimeout: {=u8:?} }}",
                self.enable(), self.lbm(), self.cp(), self.pod(), self.msb(), self
                .pren(), self.pes(), self.pten(), self.cdenable(), self.cdmode(), self
                .repeattx(), self.rxtimeout()
            )
        }
    }
    ///Interrupt clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct DmaTrigRx(pub u32);
    impl DmaTrigRx {
        ///Clear SPI Receive Time-Out event.
        #[must_use]
        #[inline(always)]
        pub const fn rtout(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Clear SPI Receive Time-Out event.
        #[inline(always)]
        pub const fn set_rtout(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Clear Receive FIFO event.
        #[must_use]
        #[inline(always)]
        pub const fn rx(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Clear Receive FIFO event.
        #[inline(always)]
        pub const fn set_rx(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for DmaTrigRx {
        #[inline(always)]
        fn default() -> DmaTrigRx {
            DmaTrigRx(0)
        }
    }
    impl core::fmt::Debug for DmaTrigRx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("DmaTrigRx")
                .field("rtout", &self.rtout())
                .field("rx", &self.rx())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DmaTrigRx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "DmaTrigRx {{ rtout: {=bool:?}, rx: {=bool:?} }}", self.rtout(), self
                .rx()
            )
        }
    }
    ///Interrupt Index Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct DmaTrigRxIidx(pub u32);
    impl DmaTrigRxIidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::DmaTrigRxIidxStat {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::DmaTrigRxIidxStat::from_bits(val as u8)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::DmaTrigRxIidxStat) {
            self.0 = (self.0 & !(0xff << 0usize))
                | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
    }
    impl Default for DmaTrigRxIidx {
        #[inline(always)]
        fn default() -> DmaTrigRxIidx {
            DmaTrigRxIidx(0)
        }
    }
    impl core::fmt::Debug for DmaTrigRxIidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("DmaTrigRxIidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DmaTrigRxIidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "DmaTrigRxIidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Interrupt clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct DmaTrigTx(pub u32);
    impl DmaTrigTx {
        ///Clear Transmit FIFO event.
        #[must_use]
        #[inline(always)]
        pub const fn tx(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Clear Transmit FIFO event.
        #[inline(always)]
        pub const fn set_tx(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
    }
    impl Default for DmaTrigTx {
        #[inline(always)]
        fn default() -> DmaTrigTx {
            DmaTrigTx(0)
        }
    }
    impl core::fmt::Debug for DmaTrigTx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("DmaTrigTx").field("tx", &self.tx()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DmaTrigTx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "DmaTrigTx {{ tx: {=bool:?} }}", self.tx())
        }
    }
    ///Interrupt Index Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct DmaTrigTxIidx(pub u32);
    impl DmaTrigTxIidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::DmaTrigTxIidxStat {
            let val = (self.0 >> 0usize) & 0xff;
            super::vals::DmaTrigTxIidxStat::from_bits(val as u8)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::DmaTrigTxIidxStat) {
            self.0 = (self.0 & !(0xff << 0usize))
                | (((val.to_bits() as u32) & 0xff) << 0usize);
        }
    }
    impl Default for DmaTrigTxIidx {
        #[inline(always)]
        fn default() -> DmaTrigTxIidx {
            DmaTrigTxIidx(0)
        }
    }
    impl core::fmt::Debug for DmaTrigTxIidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("DmaTrigTxIidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DmaTrigTxIidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "DmaTrigTxIidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Event Mode.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT0\].
        #[must_use]
        #[inline(always)]
        pub const fn cpu(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT0\].
        #[inline(always)]
        pub const fn set_cpu(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 0usize))
                | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT1\].
        #[must_use]
        #[inline(always)]
        pub const fn dma_trig_rx(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 2usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT1\].
        #[inline(always)]
        pub const fn set_dma_trig_rx(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 2usize))
                | (((val.to_bits() as u32) & 0x03) << 2usize);
        }
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT2\].
        #[must_use]
        #[inline(always)]
        pub const fn dma_trig_tx(&self) -> super::vals::IntCfg {
            let val = (self.0 >> 4usize) & 0x03;
            super::vals::IntCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to \[IPSTANDARD.INT_EVENT2\].
        #[inline(always)]
        pub const fn set_dma_trig_tx(&mut self, val: super::vals::IntCfg) {
            self.0 = (self.0 & !(0x03 << 4usize))
                | (((val.to_bits() as u32) & 0x03) << 4usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    impl core::fmt::Debug for EvtMode {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("EvtMode")
                .field("cpu", &self.cpu())
                .field("dma_trig_rx", &self.dma_trig_rx())
                .field("dma_trig_tx", &self.dma_trig_tx())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for EvtMode {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "EvtMode {{ cpu: {:?}, dma_trig_rx: {:?}, dma_trig_tx: {:?} }}", self
                .cpu(), self.dma_trig_rx(), self.dma_trig_tx()
            )
        }
    }
    ///Status Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct GprcmStat(pub u32);
    impl GprcmStat {
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstky(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[inline(always)]
        pub const fn set_resetstky(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for GprcmStat {
        #[inline(always)]
        fn default() -> GprcmStat {
            GprcmStat(0)
        }
    }
    impl core::fmt::Debug for GprcmStat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("GprcmStat").field("resetstky", &self.resetstky()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for GprcmStat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "GprcmStat {{ resetstky: {=bool:?} }}", self.resetstky())
        }
    }
    ///Interrupt FIFO Level Select Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ifls(pub u32);
    impl Ifls {
        ///SPI Transmit Interrupt FIFO Level Select The trigger points for the transmit interrupt are as follows:.
        #[must_use]
        #[inline(always)]
        pub const fn txiflsel(&self) -> super::vals::Txiflsel {
            let val = (self.0 >> 0usize) & 0x07;
            super::vals::Txiflsel::from_bits(val as u8)
        }
        ///SPI Transmit Interrupt FIFO Level Select The trigger points for the transmit interrupt are as follows:.
        #[inline(always)]
        pub const fn set_txiflsel(&mut self, val: super::vals::Txiflsel) {
            self.0 = (self.0 & !(0x07 << 0usize))
                | (((val.to_bits() as u32) & 0x07) << 0usize);
        }
        ///SPI Receive Interrupt FIFO Level Select The trigger points for the receive interrupt are as follows:.
        #[must_use]
        #[inline(always)]
        pub const fn rxiflsel(&self) -> super::vals::Rxiflsel {
            let val = (self.0 >> 3usize) & 0x07;
            super::vals::Rxiflsel::from_bits(val as u8)
        }
        ///SPI Receive Interrupt FIFO Level Select The trigger points for the receive interrupt are as follows:.
        #[inline(always)]
        pub const fn set_rxiflsel(&mut self, val: super::vals::Rxiflsel) {
            self.0 = (self.0 & !(0x07 << 3usize))
                | (((val.to_bits() as u32) & 0x07) << 3usize);
        }
    }
    impl Default for Ifls {
        #[inline(always)]
        fn default() -> Ifls {
            Ifls(0)
        }
    }
    impl core::fmt::Debug for Ifls {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ifls")
                .field("txiflsel", &self.txiflsel())
                .field("rxiflsel", &self.rxiflsel())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ifls {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Ifls {{ txiflsel: {:?}, rxiflsel: {:?} }}", self.txiflsel(), self
                .rxiflsel()
            )
        }
    }
    ///Interrupt control register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Intctl(pub u32);
    impl Intctl {
        ///Writing a 1 to this field re-evaluates the interrupt sources.
        #[must_use]
        #[inline(always)]
        pub const fn inteval(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Writing a 1 to this field re-evaluates the interrupt sources.
        #[inline(always)]
        pub const fn set_inteval(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
    }
    impl Default for Intctl {
        #[inline(always)]
        fn default() -> Intctl {
            Intctl(0)
        }
    }
    impl core::fmt::Debug for Intctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Intctl").field("inteval", &self.inteval()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Intctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Intctl {{ inteval: {=bool:?} }}", self.inteval())
        }
    }
    ///Peripheral Debug Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pdbgctl(pub u32);
    impl Pdbgctl {
        ///Free run control.
        #[must_use]
        #[inline(always)]
        pub const fn free(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Free run control.
        #[inline(always)]
        pub const fn set_free(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        /**Soft halt boundary control. This function is only available, if \[FREE\]
is set to 'STOP'.*/
        #[must_use]
        #[inline(always)]
        pub const fn soft(&self) -> super::vals::Soft {
            let val = (self.0 >> 1usize) & 0x01;
            super::vals::Soft::from_bits(val as u8)
        }
        /**Soft halt boundary control. This function is only available, if \[FREE\]
is set to 'STOP'.*/
        #[inline(always)]
        pub const fn set_soft(&mut self, val: super::vals::Soft) {
            self.0 = (self.0 & !(0x01 << 1usize))
                | (((val.to_bits() as u32) & 0x01) << 1usize);
        }
    }
    impl Default for Pdbgctl {
        #[inline(always)]
        fn default() -> Pdbgctl {
            Pdbgctl(0)
        }
    }
    impl core::fmt::Debug for Pdbgctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pdbgctl")
                .field("free", &self.free())
                .field("soft", &self.soft())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pdbgctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pdbgctl {{ free: {=bool:?}, soft: {:?} }}", self.free(), self.soft()
            )
        }
    }
    ///Power enable.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pwren(pub u32);
    impl Pwren {
        ///Enable the power.
        #[must_use]
        #[inline(always)]
        pub const fn enable(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Enable the power.
        #[inline(always)]
        pub const fn set_enable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::PwrenKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::PwrenKey::from_bits(val as u8)
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::PwrenKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Pwren {
        #[inline(always)]
        fn default() -> Pwren {
            Pwren(0)
        }
    }
    impl core::fmt::Debug for Pwren {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pwren")
                .field("enable", &self.enable())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pwren {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pwren {{ enable: {=bool:?}, key: {:?} }}", self.enable(), self.key()
            )
        }
    }
    ///Reset Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Rstctl(pub u32);
    impl Rstctl {
        ///Assert reset to the peripheral.
        #[must_use]
        #[inline(always)]
        pub const fn resetassert(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Assert reset to the peripheral.
        #[inline(always)]
        pub const fn set_resetassert(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Clear the RESETSTKY bit in the STAT register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstkyclr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Clear the RESETSTKY bit in the STAT register.
        #[inline(always)]
        pub const fn set_resetstkyclr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::ResetKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::ResetKey::from_bits(val as u8)
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::ResetKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Rstctl {
        #[inline(always)]
        fn default() -> Rstctl {
            Rstctl(0)
        }
    }
    impl core::fmt::Debug for Rstctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Rstctl")
                .field("resetassert", &self.resetassert())
                .field("resetstkyclr", &self.resetstkyclr())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Rstctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Rstctl {{ resetassert: {=bool:?}, resetstkyclr: {=bool:?}, key: {:?} }}",
                self.resetassert(), self.resetstkyclr(), self.key()
            )
        }
    }
    ///RXDATA Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Rxdata(pub u32);
    impl Rxdata {
        ///Received Data When PACKEN=1,two entries of the FIFO are returned as a 32-bit value. When PACKEN=0, 1 entry of FIFO is returned as 16-bit value. As data values are removed by the receive logic from the incoming data frame, they are placed into the entry in the receive FIFO, pointed to by the current FIFO write pointer. Received data less than 16 bits is automatically right justified in the receive buffer.
        #[must_use]
        #[inline(always)]
        pub const fn data(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///Received Data When PACKEN=1,two entries of the FIFO are returned as a 32-bit value. When PACKEN=0, 1 entry of FIFO is returned as 16-bit value. As data values are removed by the receive logic from the incoming data frame, they are placed into the entry in the receive FIFO, pointed to by the current FIFO write pointer. Received data less than 16 bits is automatically right justified in the receive buffer.
        #[inline(always)]
        pub const fn set_data(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize))
                | (((val as u32) & 0xffff) << 0usize);
        }
    }
    impl Default for Rxdata {
        #[inline(always)]
        fn default() -> Rxdata {
            Rxdata(0)
        }
    }
    impl core::fmt::Debug for Rxdata {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Rxdata").field("data", &self.data()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Rxdata {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Rxdata {{ data: {=u16:?} }}", self.data())
        }
    }
    ///Status Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Stat(pub u32);
    impl Stat {
        ///Transmit FIFO empty.
        #[must_use]
        #[inline(always)]
        pub const fn tfe(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Transmit FIFO empty.
        #[inline(always)]
        pub const fn set_tfe(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Transmit FIFO not full.
        #[must_use]
        #[inline(always)]
        pub const fn tnf(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Transmit FIFO not full.
        #[inline(always)]
        pub const fn set_tnf(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Receive FIFO empty.
        #[must_use]
        #[inline(always)]
        pub const fn rfe(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Receive FIFO empty.
        #[inline(always)]
        pub const fn set_rfe(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Receive FIFO not full.
        #[must_use]
        #[inline(always)]
        pub const fn rnf(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Receive FIFO not full.
        #[inline(always)]
        pub const fn set_rnf(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Busy.
        #[must_use]
        #[inline(always)]
        pub const fn busy(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Busy.
        #[inline(always)]
        pub const fn set_busy(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
    }
    impl Default for Stat {
        #[inline(always)]
        fn default() -> Stat {
            Stat(0)
        }
    }
    impl core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Stat")
                .field("tfe", &self.tfe())
                .field("tnf", &self.tnf())
                .field("rfe", &self.rfe())
                .field("rnf", &self.rnf())
                .field("busy", &self.busy())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Stat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Stat {{ tfe: {=bool:?}, tnf: {=bool:?}, rfe: {=bool:?}, rnf: {=bool:?}, busy: {=bool:?} }}",
                self.tfe(), self.tnf(), self.rfe(), self.rnf(), self.busy()
            )
        }
    }
    ///TXDATA Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Txdata(pub u32);
    impl Txdata {
        ///Transmit Data When read, last written value will be returned. If the last write to this field was a 32-bit write (with PACKEN=1), 32-bits will be returned and if the last write was a 16-bit write (PACKEN=0), those 16-bits will be returned. When written, one or two FIFO entries will be written depending on PACKEN value. Data values are removed from the transmit FIFO one value at a time by the transmit logic. It is loaded into the transmit serial shifter, then serially shifted out onto the TXD output pin at the programmed bit rate. When a data size of less than 16 bits is selected, the user must right-justify data written to the transmit FIFO. The transmit logic ignores the unused bits.
        #[must_use]
        #[inline(always)]
        pub const fn data(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///Transmit Data When read, last written value will be returned. If the last write to this field was a 32-bit write (with PACKEN=1), 32-bits will be returned and if the last write was a 16-bit write (PACKEN=0), those 16-bits will be returned. When written, one or two FIFO entries will be written depending on PACKEN value. Data values are removed from the transmit FIFO one value at a time by the transmit logic. It is loaded into the transmit serial shifter, then serially shifted out onto the TXD output pin at the programmed bit rate. When a data size of less than 16 bits is selected, the user must right-justify data written to the transmit FIFO. The transmit logic ignores the unused bits.
        #[inline(always)]
        pub const fn set_data(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize))
                | (((val as u32) & 0xffff) << 0usize);
        }
    }
    impl Default for Txdata {
        #[inline(always)]
        fn default() -> Txdata {
            Txdata(0)
        }
    }
    impl core::fmt::Debug for Txdata {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Txdata").field("data", &self.data()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Txdata {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Txdata {{ data: {=u16:?} }}", self.data())
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Cdmode {
        ///Manual mode: Data.
        Data = 0x0,
        _RESERVED_1 = 0x01,
        _RESERVED_2 = 0x02,
        _RESERVED_3 = 0x03,
        _RESERVED_4 = 0x04,
        _RESERVED_5 = 0x05,
        _RESERVED_6 = 0x06,
        _RESERVED_7 = 0x07,
        _RESERVED_8 = 0x08,
        _RESERVED_9 = 0x09,
        _RESERVED_a = 0x0a,
        _RESERVED_b = 0x0b,
        _RESERVED_c = 0x0c,
        _RESERVED_d = 0x0d,
        _RESERVED_e = 0x0e,
        ///Manual mode: Command.
        Command = 0x0f,
    }
    impl Cdmode {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Cdmode {
            unsafe { core::mem::transmute(val & 0x0f) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Cdmode {
        #[inline(always)]
        fn from(val: u8) -> Cdmode {
            Cdmode::from_bits(val)
        }
    }
    impl From<Cdmode> for u8 {
        #[inline(always)]
        fn from(val: Cdmode) -> u8 {
            Cdmode::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct ClkcfgKey(u8);
    impl ClkcfgKey {
        pub const Key: Self = Self(0xa9);
    }
    impl ClkcfgKey {
        pub const fn from_bits(val: u8) -> ClkcfgKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for ClkcfgKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xa9 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ClkcfgKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xa9 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for ClkcfgKey {
        #[inline(always)]
        fn from(val: u8) -> ClkcfgKey {
            ClkcfgKey::from_bits(val)
        }
    }
    impl From<ClkcfgKey> for u8 {
        #[inline(always)]
        fn from(val: ClkcfgKey) -> u8 {
            ClkcfgKey::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct CpuIntIidxStat(u8);
    impl CpuIntIidxStat {
        ///No interrupt pending.
        pub const NoIntr: Self = Self(0x0);
        ///RX FIFO Overflow Event/interrupt pending.
        pub const RxfifoOfvEvt: Self = Self(0x01);
        ///Transmit Parity Event/interrupt pending.
        pub const PerEvt: Self = Self(0x02);
        ///SPI receive time-out interrupt.
        pub const RtoutEvt: Self = Self(0x03);
        ///Receive Event/interrupt pending.
        pub const RxEvt: Self = Self(0x04);
        ///Transmit Event/interrupt pending.
        pub const TxEvt: Self = Self(0x05);
        ///Transmit Buffer Empty Event/interrupt pending.
        pub const TxEmpty: Self = Self(0x06);
        ///End of Transmit Event/interrupt pending.
        pub const IdleEvt: Self = Self(0x07);
        ///DMA Done for Receive Event/interrupt pending.
        pub const DmaDoneRxEvt: Self = Self(0x08);
        ///DMA Done for Transmit Event/interrupt pending.
        pub const DmaDoneTxEvt: Self = Self(0x09);
        ///TX FIFO underflow interrupt.
        pub const TxfifoUnfEvt: Self = Self(0x0a);
        ///RX FIFO Full Interrupt.
        pub const RxfullEvt: Self = Self(0x0b);
    }
    impl CpuIntIidxStat {
        pub const fn from_bits(val: u8) -> CpuIntIidxStat {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for CpuIntIidxStat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x0 => f.write_str("NoIntr"),
                0x01 => f.write_str("RxfifoOfvEvt"),
                0x02 => f.write_str("PerEvt"),
                0x03 => f.write_str("RtoutEvt"),
                0x04 => f.write_str("RxEvt"),
                0x05 => f.write_str("TxEvt"),
                0x06 => f.write_str("TxEmpty"),
                0x07 => f.write_str("IdleEvt"),
                0x08 => f.write_str("DmaDoneRxEvt"),
                0x09 => f.write_str("DmaDoneTxEvt"),
                0x0a => f.write_str("TxfifoUnfEvt"),
                0x0b => f.write_str("RxfullEvt"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for CpuIntIidxStat {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x0 => defmt::write!(f, "NoIntr"),
                0x01 => defmt::write!(f, "RxfifoOfvEvt"),
                0x02 => defmt::write!(f, "PerEvt"),
                0x03 => defmt::write!(f, "RtoutEvt"),
                0x04 => defmt::write!(f, "RxEvt"),
                0x05 => defmt::write!(f, "TxEvt"),
                0x06 => defmt::write!(f, "TxEmpty"),
                0x07 => defmt::write!(f, "IdleEvt"),
                0x08 => defmt::write!(f, "DmaDoneRxEvt"),
                0x09 => defmt::write!(f, "DmaDoneTxEvt"),
                0x0a => defmt::write!(f, "TxfifoUnfEvt"),
                0x0b => defmt::write!(f, "RxfullEvt"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for CpuIntIidxStat {
        #[inline(always)]
        fn from(val: u8) -> CpuIntIidxStat {
            CpuIntIidxStat::from_bits(val)
        }
    }
    impl From<CpuIntIidxStat> for u8 {
        #[inline(always)]
        fn from(val: CpuIntIidxStat) -> u8 {
            CpuIntIidxStat::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Cssel {
        ///CS line select: 0.
        Cssel0 = 0x0,
        ///CS line select: 1.
        Cssel1 = 0x01,
        ///CS line select: 2.
        Cssel2 = 0x02,
        ///CS line select: 3.
        Cssel3 = 0x03,
    }
    impl Cssel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Cssel {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Cssel {
        #[inline(always)]
        fn from(val: u8) -> Cssel {
            Cssel::from_bits(val)
        }
    }
    impl From<Cssel> for u8 {
        #[inline(always)]
        fn from(val: Cssel) -> u8 {
            Cssel::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct DmaTrigRxIidxStat(u8);
    impl DmaTrigRxIidxStat {
        ///No interrupt pending.
        pub const NoIntr: Self = Self(0x0);
        ///SPI receive time-out interrupt.
        pub const RtoutEvt: Self = Self(0x03);
        ///Receive Event/interrupt pending.
        pub const RxEvt: Self = Self(0x04);
    }
    impl DmaTrigRxIidxStat {
        pub const fn from_bits(val: u8) -> DmaTrigRxIidxStat {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for DmaTrigRxIidxStat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x0 => f.write_str("NoIntr"),
                0x03 => f.write_str("RtoutEvt"),
                0x04 => f.write_str("RxEvt"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DmaTrigRxIidxStat {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x0 => defmt::write!(f, "NoIntr"),
                0x03 => defmt::write!(f, "RtoutEvt"),
                0x04 => defmt::write!(f, "RxEvt"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for DmaTrigRxIidxStat {
        #[inline(always)]
        fn from(val: u8) -> DmaTrigRxIidxStat {
            DmaTrigRxIidxStat::from_bits(val)
        }
    }
    impl From<DmaTrigRxIidxStat> for u8 {
        #[inline(always)]
        fn from(val: DmaTrigRxIidxStat) -> u8 {
            DmaTrigRxIidxStat::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct DmaTrigTxIidxStat(u8);
    impl DmaTrigTxIidxStat {
        ///No interrupt pending.
        pub const NoIntr: Self = Self(0x0);
        ///Transmit Event/interrupt pending.
        pub const TxEvt: Self = Self(0x05);
    }
    impl DmaTrigTxIidxStat {
        pub const fn from_bits(val: u8) -> DmaTrigTxIidxStat {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for DmaTrigTxIidxStat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x0 => f.write_str("NoIntr"),
                0x05 => f.write_str("TxEvt"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DmaTrigTxIidxStat {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x0 => defmt::write!(f, "NoIntr"),
                0x05 => defmt::write!(f, "TxEvt"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for DmaTrigTxIidxStat {
        #[inline(always)]
        fn from(val: u8) -> DmaTrigTxIidxStat {
            DmaTrigTxIidxStat::from_bits(val)
        }
    }
    impl From<DmaTrigTxIidxStat> for u8 {
        #[inline(always)]
        fn from(val: DmaTrigTxIidxStat) -> u8 {
            DmaTrigTxIidxStat::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Dss {
        _RESERVED_0 = 0x0,
        _RESERVED_1 = 0x01,
        _RESERVED_2 = 0x02,
        ///Data Size Select bits: 4.
        Dss4 = 0x03,
        ///Data Size Select bits: 5.
        Dss5 = 0x04,
        ///Data Size Select bits: 6.
        Dss6 = 0x05,
        ///Data Size Select bits: 7.
        Dss7 = 0x06,
        ///Data Size Select bits: 8.
        Dss8 = 0x07,
        ///Data Size Select bits: 9.
        Dss9 = 0x08,
        ///Data Size Select bits: 10.
        Dss10 = 0x09,
        ///Data Size Select bits: 11.
        Dss11 = 0x0a,
        ///Data Size Select bits: 12.
        Dss12 = 0x0b,
        ///Data Size Select bits: 13.
        Dss13 = 0x0c,
        ///Data Size Select bits: 14.
        Dss14 = 0x0d,
        ///Data Size Select bits: 15.
        Dss15 = 0x0e,
        ///Data Size Select bits: 16.
        Dss16 = 0x0f,
        _RESERVED_10 = 0x10,
        _RESERVED_11 = 0x11,
        _RESERVED_12 = 0x12,
        _RESERVED_13 = 0x13,
        _RESERVED_14 = 0x14,
        _RESERVED_15 = 0x15,
        _RESERVED_16 = 0x16,
        _RESERVED_17 = 0x17,
        _RESERVED_18 = 0x18,
        _RESERVED_19 = 0x19,
        _RESERVED_1a = 0x1a,
        _RESERVED_1b = 0x1b,
        _RESERVED_1c = 0x1c,
        _RESERVED_1d = 0x1d,
        _RESERVED_1e = 0x1e,
        _RESERVED_1f = 0x1f,
    }
    impl Dss {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Dss {
            unsafe { core::mem::transmute(val & 0x1f) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Dss {
        #[inline(always)]
        fn from(val: u8) -> Dss {
            Dss::from_bits(val)
        }
    }
    impl From<Dss> for u8 {
        #[inline(always)]
        fn from(val: Dss) -> u8 {
            Dss::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Frf {
        ///Motorola SPI frame format (3 wire mode).
        Motorola3wire = 0x0,
        ///Motorola SPI frame format (4 wire mode).
        Motorola4wire = 0x01,
        ///TI synchronous serial frame format.
        TiSync = 0x02,
        ///National Microwire frame format.
        Mircowire = 0x03,
    }
    impl Frf {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Frf {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Frf {
        #[inline(always)]
        fn from(val: u8) -> Frf {
            Frf::from_bits(val)
        }
    }
    impl From<Frf> for u8 {
        #[inline(always)]
        fn from(val: Frf) -> u8 {
            Frf::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum IntCfg {
        ///The interrupt or event line is disabled.
        Disable = 0x0,
        ///The interrupt or event line is in software mode. Software must clear the RIS.
        Software = 0x01,
        ///The interrupt or event line is in hardware mode. The hardware (another module) clears automatically the associated RIS flag.
        Hardware = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl IntCfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> IntCfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for IntCfg {
        #[inline(always)]
        fn from(val: u8) -> IntCfg {
            IntCfg::from_bits(val)
        }
    }
    impl From<IntCfg> for u8 {
        #[inline(always)]
        fn from(val: IntCfg) -> u8 {
            IntCfg::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct PwrenKey(u8);
    impl PwrenKey {
        pub const Key: Self = Self(0x26);
    }
    impl PwrenKey {
        pub const fn from_bits(val: u8) -> PwrenKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for PwrenKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x26 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for PwrenKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x26 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for PwrenKey {
        #[inline(always)]
        fn from(val: u8) -> PwrenKey {
            PwrenKey::from_bits(val)
        }
    }
    impl From<PwrenKey> for u8 {
        #[inline(always)]
        fn from(val: PwrenKey) -> u8 {
            PwrenKey::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Ratio {
        ///Do not divide clock source.
        DivBy1 = 0x0,
        ///Divide clock source by 2.
        DivBy2 = 0x01,
        ///Divide clock source by 3.
        DivBy3 = 0x02,
        ///Divide clock source by 4.
        DivBy4 = 0x03,
        ///Divide clock source by 5.
        DivBy5 = 0x04,
        ///Divide clock source by 6.
        DivBy6 = 0x05,
        ///Divide clock source by 7.
        DivBy7 = 0x06,
        ///Divide clock source by 8.
        DivBy8 = 0x07,
    }
    impl Ratio {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Ratio {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Ratio {
        #[inline(always)]
        fn from(val: u8) -> Ratio {
            Ratio::from_bits(val)
        }
    }
    impl From<Ratio> for u8 {
        #[inline(always)]
        fn from(val: Ratio) -> u8 {
            Ratio::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct ResetKey(u8);
    impl ResetKey {
        pub const Key: Self = Self(0xb1);
    }
    impl ResetKey {
        pub const fn from_bits(val: u8) -> ResetKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for ResetKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xb1 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ResetKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xb1 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for ResetKey {
        #[inline(always)]
        fn from(val: u8) -> ResetKey {
            ResetKey::from_bits(val)
        }
    }
    impl From<ResetKey> for u8 {
        #[inline(always)]
        fn from(val: ResetKey) -> u8 {
            ResetKey::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Rxiflsel {
        ///Reserved.
        LvlOff = 0x0,
        ///RX FIFO >= 1/4 full.
        Lvl14 = 0x01,
        ///RX FIFO >= 1/2 full (default).
        Lvl12 = 0x02,
        ///RX FIFO >= 3/4 full.
        Lvl34 = 0x03,
        ///Reserved.
        LvlRes4 = 0x04,
        ///RX FIFO is full.
        LvlFull = 0x05,
        ///Reserved.
        LvlRes6 = 0x06,
        ///Trigger when RX FIFO contains >= 1 frame.
        Level1 = 0x07,
    }
    impl Rxiflsel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Rxiflsel {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Rxiflsel {
        #[inline(always)]
        fn from(val: u8) -> Rxiflsel {
            Rxiflsel::from_bits(val)
        }
    }
    impl From<Rxiflsel> for u8 {
        #[inline(always)]
        fn from(val: Rxiflsel) -> u8 {
            Rxiflsel::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Soft {
        ///The peripheral will halt immediately, even if the resultant state will result in corruption if the system is restarted.
        Immediate = 0x0,
        ///The peripheral blocks the debug freeze until it has reached a boundary where it can resume without corruption.
        Delayed = 0x01,
    }
    impl Soft {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Soft {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Soft {
        #[inline(always)]
        fn from(val: u8) -> Soft {
            Soft::from_bits(val)
        }
    }
    impl From<Soft> for u8 {
        #[inline(always)]
        fn from(val: Soft) -> u8 {
            Soft::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Sph {
        ///Data is captured on the first clock edge transition.
        First = 0x0,
        ///Data is captured on the second clock edge transition.
        Second = 0x01,
    }
    impl Sph {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Sph {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Sph {
        #[inline(always)]
        fn from(val: u8) -> Sph {
            Sph::from_bits(val)
        }
    }
    impl From<Sph> for u8 {
        #[inline(always)]
        fn from(val: Sph) -> u8 {
            Sph::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Txiflsel {
        ///Reserved.
        LvlOff = 0x0,
        ///TX FIFO <= 3/4 empty.
        Lvl34 = 0x01,
        ///TX FIFO <= 1/2 empty (default).
        Lvl12 = 0x02,
        ///TX FIFO <= 1/4 empty.
        Lvl14 = 0x03,
        ///Reserved.
        LvlRes4 = 0x04,
        ///TX FIFO is empty.
        LvlEmpty = 0x05,
        ///Reserved.
        LvlRes6 = 0x06,
        ///Trigger when TX FIFO has >= 1 frame free Should be used with DMA.
        Level1 = 0x07,
    }
    impl Txiflsel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Txiflsel {
            unsafe { core::mem::transmute(val & 0x07) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Txiflsel {
        #[inline(always)]
        fn from(val: u8) -> Txiflsel {
            Txiflsel::from_bits(val)
        }
    }
    impl From<Txiflsel> for u8 {
        #[inline(always)]
        fn from(val: Txiflsel) -> u8 {
            Txiflsel::to_bits(val)
        }
    }
}
