// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CpuInt {
    ptr: *mut u8,
}
unsafe impl Send for CpuInt {}
unsafe impl Sync for CpuInt {}
impl CpuInt {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Ctrregs {
    ptr: *mut u8,
}
unsafe impl Send for Ctrregs {}
unsafe impl Sync for Ctrregs {}
impl Ctrregs {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///CTL0 register.
    #[inline(always)]
    pub const fn ctl0(self) -> crate::common::Reg<regs::Ctl0, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Counter period register.
    #[inline(always)]
    pub const fn ld(self) -> crate::common::Reg<regs::Ld, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///Counter register.
    #[inline(always)]
    pub const fn cnt(self) -> crate::common::Reg<regs::Cnt, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct GenEvent {
    ptr: *mut u8,
}
unsafe impl Send for GenEvent {}
unsafe impl Sync for GenEvent {}
impl GenEvent {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Interrupt index.
    #[inline(always)]
    pub const fn iidx(self) -> crate::common::Reg<regs::Iidx, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Interrupt mask.
    #[inline(always)]
    pub const fn imask(self) -> crate::common::Reg<regs::Int, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
    }
    ///Raw interrupt status.
    #[inline(always)]
    pub const fn ris(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
    }
    ///Masked interrupt status.
    #[inline(always)]
    pub const fn mis(self) -> crate::common::Reg<regs::Int, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
    }
    ///Interrupt set.
    #[inline(always)]
    pub const fn iset(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x20usize) as _) }
    }
    ///Interrupt clear.
    #[inline(always)]
    pub const fn iclr(self) -> crate::common::Reg<regs::Int, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
    }
}
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Gprcm {
    ptr: *mut u8,
}
unsafe impl Send for Gprcm {}
unsafe impl Sync for Gprcm {}
impl Gprcm {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Power enable.
    #[inline(always)]
    pub const fn pwren(self) -> crate::common::Reg<regs::Pwren, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
    }
    ///Reset Control.
    #[inline(always)]
    pub const fn rstctl(self) -> crate::common::Reg<regs::Rstctl, crate::common::W> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
    }
    ///Status Register.
    #[inline(always)]
    pub const fn stat(self) -> crate::common::Reg<regs::Stat, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
    }
}
///PERIPHERALREGION.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Tim {
    ptr: *mut u8,
}
unsafe impl Send for Tim {}
unsafe impl Sync for Tim {}
impl Tim {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Subscriber Port 0.
    #[inline(always)]
    pub const fn fsub(self) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0400usize) as _) }
    }
    ///Publisher Port 0.
    #[inline(always)]
    pub const fn fpub(self) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0444usize) as _) }
    }
    #[inline(always)]
    pub const fn gprcm(self, n: usize) -> Gprcm {
        assert!(n < 1usize);
        unsafe { Gprcm::from_ptr(self.ptr.wrapping_add(0x0800usize + n * 24usize) as _) }
    }
    ///Peripheral Debug Control.
    #[inline(always)]
    pub const fn pdbgctl(self) -> crate::common::Reg<regs::Pdbgctl, crate::common::RW> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1018usize) as _) }
    }
    #[inline(always)]
    pub const fn cpu_int(self, n: usize) -> CpuInt {
        assert!(n < 1usize);
        unsafe {
            CpuInt::from_ptr(self.ptr.wrapping_add(0x1020usize + n * 44usize) as _)
        }
    }
    #[inline(always)]
    pub const fn gen_event(self, n: usize) -> GenEvent {
        assert!(n < 1usize);
        unsafe {
            GenEvent::from_ptr(self.ptr.wrapping_add(0x1050usize + n * 44usize) as _)
        }
    }
    ///Event Mode.
    #[inline(always)]
    pub const fn evt_mode(self) -> crate::common::Reg<regs::EvtMode, crate::common::R> {
        unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10e0usize) as _) }
    }
    ///One independent counter. The array is the eight the TRM documents and the interrupt registers have bits for; how many a device implements is `Timer::counters`, which is 4 on the G-series instances and 2 on the L-series ones.
    #[inline(always)]
    pub const fn ctrregs(self, n: usize) -> Ctrregs {
        assert!(n < 8usize);
        unsafe {
            Ctrregs::from_ptr(self.ptr.wrapping_add(0x1100usize + n * 256usize) as _)
        }
    }
}
pub mod regs {
    ///Counter register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cnt(pub u32);
    impl Cnt {
        ///Counter Value.
        #[must_use]
        #[inline(always)]
        pub const fn value(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///Counter Value.
        #[inline(always)]
        pub const fn set_value(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize))
                | (((val as u32) & 0xffff) << 0usize);
        }
    }
    impl Default for Cnt {
        #[inline(always)]
        fn default() -> Cnt {
            Cnt(0)
        }
    }
    impl core::fmt::Debug for Cnt {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Cnt").field("value", &self.value()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Cnt {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Cnt {{ value: {=u16:?} }}", self.value())
        }
    }
    ///CTL0 register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ctl0(pub u32);
    impl Ctl0 {
        ///Counter Enable.
        #[must_use]
        #[inline(always)]
        pub const fn en(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Counter Enable.
        #[inline(always)]
        pub const fn set_en(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Selects the source used to start the counter.
        #[must_use]
        #[inline(always)]
        pub const fn startsel(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x0f;
            val as u8
        }
        ///Selects the source used to start the counter.
        #[inline(always)]
        pub const fn set_startsel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize);
        }
        ///Selects the source used to stop the counter.
        #[must_use]
        #[inline(always)]
        pub const fn stopsel(&self) -> u8 {
            let val = (self.0 >> 8usize) & 0x0f;
            val as u8
        }
        ///Selects the source used to stop the counter.
        #[inline(always)]
        pub const fn set_stopsel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize);
        }
        ///Selects the source used to reset the counter.
        #[must_use]
        #[inline(always)]
        pub const fn resetsel(&self) -> u8 {
            let val = (self.0 >> 12usize) & 0x0f;
            val as u8
        }
        ///Selects the source used to reset the counter.
        #[inline(always)]
        pub const fn set_resetsel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize);
        }
        ///Clock sources.
        #[must_use]
        #[inline(always)]
        pub const fn clksel(&self) -> u8 {
            let val = (self.0 >> 16usize) & 0x0f;
            val as u8
        }
        ///Clock sources.
        #[inline(always)]
        pub const fn set_clksel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize);
        }
    }
    impl Default for Ctl0 {
        #[inline(always)]
        fn default() -> Ctl0 {
            Ctl0(0)
        }
    }
    impl core::fmt::Debug for Ctl0 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ctl0")
                .field("en", &self.en())
                .field("startsel", &self.startsel())
                .field("stopsel", &self.stopsel())
                .field("resetsel", &self.resetsel())
                .field("clksel", &self.clksel())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ctl0 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Ctl0 {{ en: {=bool:?}, startsel: {=u8:?}, stopsel: {=u8:?}, resetsel: {=u8:?}, clksel: {=u8:?} }}",
                self.en(), self.startsel(), self.stopsel(), self.resetsel(), self
                .clksel()
            )
        }
    }
    ///Event Mode.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct EvtMode(pub u32);
    impl EvtMode {
        ///Event line mode select for event corresponding to CPU_INT.
        #[must_use]
        #[inline(always)]
        pub const fn cpu_int_cfg(&self) -> super::vals::EvtCfg {
            let val = (self.0 >> 0usize) & 0x03;
            super::vals::EvtCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to CPU_INT.
        #[inline(always)]
        pub const fn set_cpu_int_cfg(&mut self, val: super::vals::EvtCfg) {
            self.0 = (self.0 & !(0x03 << 0usize))
                | (((val.to_bits() as u32) & 0x03) << 0usize);
        }
        ///Event line mode select for event corresponding to GEN_EVENT.
        #[must_use]
        #[inline(always)]
        pub const fn gen_event_cfg(&self) -> super::vals::EvtCfg {
            let val = (self.0 >> 2usize) & 0x03;
            super::vals::EvtCfg::from_bits(val as u8)
        }
        ///Event line mode select for event corresponding to GEN_EVENT.
        #[inline(always)]
        pub const fn set_gen_event_cfg(&mut self, val: super::vals::EvtCfg) {
            self.0 = (self.0 & !(0x03 << 2usize))
                | (((val.to_bits() as u32) & 0x03) << 2usize);
        }
    }
    impl Default for EvtMode {
        #[inline(always)]
        fn default() -> EvtMode {
            EvtMode(0)
        }
    }
    impl core::fmt::Debug for EvtMode {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("EvtMode")
                .field("cpu_int_cfg", &self.cpu_int_cfg())
                .field("gen_event_cfg", &self.gen_event_cfg())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for EvtMode {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "EvtMode {{ cpu_int_cfg: {:?}, gen_event_cfg: {:?} }}", self
                .cpu_int_cfg(), self.gen_event_cfg()
            )
        }
    }
    ///Publisher or subscriber port.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Fport(pub u32);
    impl Fport {
        ///0 = disconnected. 1-15 = connected to channelID = CHANID.
        #[must_use]
        #[inline(always)]
        pub const fn chanid(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///0 = disconnected. 1-15 = connected to channelID = CHANID.
        #[inline(always)]
        pub const fn set_chanid(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
    }
    impl Default for Fport {
        #[inline(always)]
        fn default() -> Fport {
            Fport(0)
        }
    }
    impl core::fmt::Debug for Fport {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Fport").field("chanid", &self.chanid()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Fport {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Fport {{ chanid: {=u8:?} }}", self.chanid())
        }
    }
    ///Interrupt index.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Iidx(pub u32);
    impl Iidx {
        ///Interrupt index status.
        #[must_use]
        #[inline(always)]
        pub const fn stat(&self) -> super::vals::IidxStat {
            let val = (self.0 >> 0usize) & 0x03ff;
            super::vals::IidxStat::from_bits(val as u16)
        }
        ///Interrupt index status.
        #[inline(always)]
        pub const fn set_stat(&mut self, val: super::vals::IidxStat) {
            self.0 = (self.0 & !(0x03ff << 0usize))
                | (((val.to_bits() as u32) & 0x03ff) << 0usize);
        }
    }
    impl Default for Iidx {
        #[inline(always)]
        fn default() -> Iidx {
            Iidx(0)
        }
    }
    impl core::fmt::Debug for Iidx {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Iidx").field("stat", &self.stat()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Iidx {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Iidx {{ stat: {:?} }}", self.stat())
        }
    }
    ///Interrupt mask, status, set or clear.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Int(pub u32);
    impl Int {
        ///Counter period match.
        #[must_use]
        #[inline(always)]
        pub const fn cntovf(&self, n: usize) -> bool {
            assert!(n < 8usize);
            let offs = 0usize + n * 3usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        ///Counter period match.
        #[inline(always)]
        pub const fn set_cntovf(&mut self, n: usize, val: bool) {
            assert!(n < 8usize);
            let offs = 0usize + n * 3usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
        ///Counter start.
        #[must_use]
        #[inline(always)]
        pub const fn cntstrt(&self, n: usize) -> bool {
            assert!(n < 8usize);
            let offs = 1usize + n * 3usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        ///Counter start.
        #[inline(always)]
        pub const fn set_cntstrt(&mut self, n: usize, val: bool) {
            assert!(n < 8usize);
            let offs = 1usize + n * 3usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
        ///Counter stop.
        #[must_use]
        #[inline(always)]
        pub const fn cntstop(&self, n: usize) -> bool {
            assert!(n < 8usize);
            let offs = 2usize + n * 3usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        ///Counter stop.
        #[inline(always)]
        pub const fn set_cntstop(&mut self, n: usize, val: bool) {
            assert!(n < 8usize);
            let offs = 2usize + n * 3usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
    }
    impl Default for Int {
        #[inline(always)]
        fn default() -> Int {
            Int(0)
        }
    }
    impl core::fmt::Debug for Int {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Int")
                .field("cntovf[0]", &self.cntovf(0usize))
                .field("cntovf[1]", &self.cntovf(1usize))
                .field("cntovf[2]", &self.cntovf(2usize))
                .field("cntovf[3]", &self.cntovf(3usize))
                .field("cntovf[4]", &self.cntovf(4usize))
                .field("cntovf[5]", &self.cntovf(5usize))
                .field("cntovf[6]", &self.cntovf(6usize))
                .field("cntovf[7]", &self.cntovf(7usize))
                .field("cntstrt[0]", &self.cntstrt(0usize))
                .field("cntstrt[1]", &self.cntstrt(1usize))
                .field("cntstrt[2]", &self.cntstrt(2usize))
                .field("cntstrt[3]", &self.cntstrt(3usize))
                .field("cntstrt[4]", &self.cntstrt(4usize))
                .field("cntstrt[5]", &self.cntstrt(5usize))
                .field("cntstrt[6]", &self.cntstrt(6usize))
                .field("cntstrt[7]", &self.cntstrt(7usize))
                .field("cntstop[0]", &self.cntstop(0usize))
                .field("cntstop[1]", &self.cntstop(1usize))
                .field("cntstop[2]", &self.cntstop(2usize))
                .field("cntstop[3]", &self.cntstop(3usize))
                .field("cntstop[4]", &self.cntstop(4usize))
                .field("cntstop[5]", &self.cntstop(5usize))
                .field("cntstop[6]", &self.cntstop(6usize))
                .field("cntstop[7]", &self.cntstop(7usize))
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Int {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Int {{ cntovf[0]: {=bool:?}, cntovf[1]: {=bool:?}, cntovf[2]: {=bool:?}, cntovf[3]: {=bool:?}, cntovf[4]: {=bool:?}, cntovf[5]: {=bool:?}, cntovf[6]: {=bool:?}, cntovf[7]: {=bool:?}, cntstrt[0]: {=bool:?}, cntstrt[1]: {=bool:?}, cntstrt[2]: {=bool:?}, cntstrt[3]: {=bool:?}, cntstrt[4]: {=bool:?}, cntstrt[5]: {=bool:?}, cntstrt[6]: {=bool:?}, cntstrt[7]: {=bool:?}, cntstop[0]: {=bool:?}, cntstop[1]: {=bool:?}, cntstop[2]: {=bool:?}, cntstop[3]: {=bool:?}, cntstop[4]: {=bool:?}, cntstop[5]: {=bool:?}, cntstop[6]: {=bool:?}, cntstop[7]: {=bool:?} }}",
                self.cntovf(0usize), self.cntovf(1usize), self.cntovf(2usize), self
                .cntovf(3usize), self.cntovf(4usize), self.cntovf(5usize), self
                .cntovf(6usize), self.cntovf(7usize), self.cntstrt(0usize), self
                .cntstrt(1usize), self.cntstrt(2usize), self.cntstrt(3usize), self
                .cntstrt(4usize), self.cntstrt(5usize), self.cntstrt(6usize), self
                .cntstrt(7usize), self.cntstop(0usize), self.cntstop(1usize), self
                .cntstop(2usize), self.cntstop(3usize), self.cntstop(4usize), self
                .cntstop(5usize), self.cntstop(6usize), self.cntstop(7usize)
            )
        }
    }
    ///Counter period register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ld(pub u32);
    impl Ld {
        ///Period value.
        #[must_use]
        #[inline(always)]
        pub const fn val(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///Period value.
        #[inline(always)]
        pub const fn set_val(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize))
                | (((val as u32) & 0xffff) << 0usize);
        }
    }
    impl Default for Ld {
        #[inline(always)]
        fn default() -> Ld {
            Ld(0)
        }
    }
    impl core::fmt::Debug for Ld {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ld").field("val", &self.val()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ld {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Ld {{ val: {=u16:?} }}", self.val())
        }
    }
    ///Peripheral Debug Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pdbgctl(pub u32);
    impl Pdbgctl {
        ///Free run control.
        #[must_use]
        #[inline(always)]
        pub const fn free(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Free run control.
        #[inline(always)]
        pub const fn set_free(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        /**Soft halt boundary control. This function is only available, if \[FREE\]
is set to 'STOP'.*/
        #[must_use]
        #[inline(always)]
        pub const fn soft(&self) -> super::vals::Soft {
            let val = (self.0 >> 1usize) & 0x01;
            super::vals::Soft::from_bits(val as u8)
        }
        /**Soft halt boundary control. This function is only available, if \[FREE\]
is set to 'STOP'.*/
        #[inline(always)]
        pub const fn set_soft(&mut self, val: super::vals::Soft) {
            self.0 = (self.0 & !(0x01 << 1usize))
                | (((val.to_bits() as u32) & 0x01) << 1usize);
        }
    }
    impl Default for Pdbgctl {
        #[inline(always)]
        fn default() -> Pdbgctl {
            Pdbgctl(0)
        }
    }
    impl core::fmt::Debug for Pdbgctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pdbgctl")
                .field("free", &self.free())
                .field("soft", &self.soft())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pdbgctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pdbgctl {{ free: {=bool:?}, soft: {:?} }}", self.free(), self.soft()
            )
        }
    }
    ///Power enable.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pwren(pub u32);
    impl Pwren {
        ///Enable the power.
        #[must_use]
        #[inline(always)]
        pub const fn enable(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Enable the power.
        #[inline(always)]
        pub const fn set_enable(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::PwrenKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::PwrenKey::from_bits(val as u8)
        }
        ///KEY to allow Power State Change 26h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::PwrenKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Pwren {
        #[inline(always)]
        fn default() -> Pwren {
            Pwren(0)
        }
    }
    impl core::fmt::Debug for Pwren {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pwren")
                .field("enable", &self.enable())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pwren {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f, "Pwren {{ enable: {=bool:?}, key: {:?} }}", self.enable(), self.key()
            )
        }
    }
    ///Reset Control.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Rstctl(pub u32);
    impl Rstctl {
        ///Assert reset to the peripheral.
        #[must_use]
        #[inline(always)]
        pub const fn resetassert(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Assert reset to the peripheral.
        #[inline(always)]
        pub const fn set_resetassert(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Clear the RESETSTKY bit in the STAT register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstkyclr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Clear the RESETSTKY bit in the STAT register.
        #[inline(always)]
        pub const fn set_resetstkyclr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[must_use]
        #[inline(always)]
        pub const fn key(&self) -> super::vals::ResetKey {
            let val = (self.0 >> 24usize) & 0xff;
            super::vals::ResetKey::from_bits(val as u8)
        }
        ///Unlock key B1h = KEY to allow write access to this register
        #[inline(always)]
        pub const fn set_key(&mut self, val: super::vals::ResetKey) {
            self.0 = (self.0 & !(0xff << 24usize))
                | (((val.to_bits() as u32) & 0xff) << 24usize);
        }
    }
    impl Default for Rstctl {
        #[inline(always)]
        fn default() -> Rstctl {
            Rstctl(0)
        }
    }
    impl core::fmt::Debug for Rstctl {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Rstctl")
                .field("resetassert", &self.resetassert())
                .field("resetstkyclr", &self.resetstkyclr())
                .field("key", &self.key())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Rstctl {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Rstctl {{ resetassert: {=bool:?}, resetstkyclr: {=bool:?}, key: {:?} }}",
                self.resetassert(), self.resetstkyclr(), self.key()
            )
        }
    }
    ///Status Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Stat(pub u32);
    impl Stat {
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[must_use]
        #[inline(always)]
        pub const fn resetstky(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///This bit indicates, if the peripheral was reset, since this bit was cleared by RESETSTKYCLR in the RSTCTL register.
        #[inline(always)]
        pub const fn set_resetstky(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for Stat {
        #[inline(always)]
        fn default() -> Stat {
            Stat(0)
        }
    }
    impl core::fmt::Debug for Stat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Stat").field("resetstky", &self.resetstky()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Stat {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Stat {{ resetstky: {=bool:?} }}", self.resetstky())
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum EvtCfg {
        ///The interrupt or event line is disabled.
        Disable = 0x0,
        ///The interrupt or event line is in software mode. Software must clear the RIS.
        Software = 0x01,
        ///The interrupt or event line is in hardware mode. The hardware (another module) clears automatically the associated RIS flag.
        Hardware = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl EvtCfg {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> EvtCfg {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for EvtCfg {
        #[inline(always)]
        fn from(val: u8) -> EvtCfg {
            EvtCfg::from_bits(val)
        }
    }
    impl From<EvtCfg> for u8 {
        #[inline(always)]
        fn from(val: EvtCfg) -> u8 {
            EvtCfg::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct IidxStat(u16);
    impl IidxStat {
        ///No bit is set means there is no pending interrupt request.
        pub const NoIntr: Self = Self(0x0);
        ///Counter0 period match interrupt.
        pub const Cnt0ovf: Self = Self(0x01);
        ///Counter 0 start.
        pub const Cnt0strt: Self = Self(0x02);
        ///Counter0 stop.
        pub const Cnt0stop: Self = Self(0x03);
        ///Counter1 period match interrupt.
        pub const Cnt1ovf: Self = Self(0x04);
        ///Counter 1 start.
        pub const Cnt1strt: Self = Self(0x05);
        ///Counter1 stop.
        pub const Cnt1stop: Self = Self(0x06);
        ///Counter2 period match interrupt.
        pub const Cnt2ovf: Self = Self(0x07);
        ///Counter 2 start.
        pub const Cnt2strt: Self = Self(0x08);
        ///Counter2 stop.
        pub const Cnt2stop: Self = Self(0x09);
        ///Counter3 period match interrupt.
        pub const Cnt3ovf: Self = Self(0x0a);
        ///Counter 3 start.
        pub const Cnt3strt: Self = Self(0x0b);
        ///Counter3 stop.
        pub const Cnt3stop: Self = Self(0x0c);
        ///Counter4 period match interrupt.
        pub const Cnt4ovf: Self = Self(0x0d);
        ///Counter 4 start.
        pub const Cnt4strt: Self = Self(0x0e);
        ///Counter4 stop.
        pub const Cnt4stop: Self = Self(0x0f);
        ///Counter5 period match interrupt.
        pub const Cnt5ovf: Self = Self(0x10);
        ///Counter 5 start.
        pub const Cnt5strt: Self = Self(0x11);
        ///Counter5 stop.
        pub const Cnt5stop: Self = Self(0x12);
        ///Counter6 period match interrupt.
        pub const Cnt6ovf: Self = Self(0x13);
        ///Counter 6 start.
        pub const Cnt6strt: Self = Self(0x14);
        ///Counter6 stop.
        pub const Cnt6stop: Self = Self(0x15);
        ///Counter7 period match interrupt.
        pub const Cnt7ovf: Self = Self(0x16);
        ///Counter 7 start.
        pub const Cnt7strt: Self = Self(0x17);
        ///Counter7 stop.
        pub const Cnt7stop: Self = Self(0x18);
    }
    impl IidxStat {
        pub const fn from_bits(val: u16) -> IidxStat {
            Self(val & 0x03ff)
        }
        pub const fn to_bits(self) -> u16 {
            self.0
        }
    }
    impl core::fmt::Debug for IidxStat {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x0 => f.write_str("NoIntr"),
                0x01 => f.write_str("Cnt0ovf"),
                0x02 => f.write_str("Cnt0strt"),
                0x03 => f.write_str("Cnt0stop"),
                0x04 => f.write_str("Cnt1ovf"),
                0x05 => f.write_str("Cnt1strt"),
                0x06 => f.write_str("Cnt1stop"),
                0x07 => f.write_str("Cnt2ovf"),
                0x08 => f.write_str("Cnt2strt"),
                0x09 => f.write_str("Cnt2stop"),
                0x0a => f.write_str("Cnt3ovf"),
                0x0b => f.write_str("Cnt3strt"),
                0x0c => f.write_str("Cnt3stop"),
                0x0d => f.write_str("Cnt4ovf"),
                0x0e => f.write_str("Cnt4strt"),
                0x0f => f.write_str("Cnt4stop"),
                0x10 => f.write_str("Cnt5ovf"),
                0x11 => f.write_str("Cnt5strt"),
                0x12 => f.write_str("Cnt5stop"),
                0x13 => f.write_str("Cnt6ovf"),
                0x14 => f.write_str("Cnt6strt"),
                0x15 => f.write_str("Cnt6stop"),
                0x16 => f.write_str("Cnt7ovf"),
                0x17 => f.write_str("Cnt7strt"),
                0x18 => f.write_str("Cnt7stop"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for IidxStat {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x0 => defmt::write!(f, "NoIntr"),
                0x01 => defmt::write!(f, "Cnt0ovf"),
                0x02 => defmt::write!(f, "Cnt0strt"),
                0x03 => defmt::write!(f, "Cnt0stop"),
                0x04 => defmt::write!(f, "Cnt1ovf"),
                0x05 => defmt::write!(f, "Cnt1strt"),
                0x06 => defmt::write!(f, "Cnt1stop"),
                0x07 => defmt::write!(f, "Cnt2ovf"),
                0x08 => defmt::write!(f, "Cnt2strt"),
                0x09 => defmt::write!(f, "Cnt2stop"),
                0x0a => defmt::write!(f, "Cnt3ovf"),
                0x0b => defmt::write!(f, "Cnt3strt"),
                0x0c => defmt::write!(f, "Cnt3stop"),
                0x0d => defmt::write!(f, "Cnt4ovf"),
                0x0e => defmt::write!(f, "Cnt4strt"),
                0x0f => defmt::write!(f, "Cnt4stop"),
                0x10 => defmt::write!(f, "Cnt5ovf"),
                0x11 => defmt::write!(f, "Cnt5strt"),
                0x12 => defmt::write!(f, "Cnt5stop"),
                0x13 => defmt::write!(f, "Cnt6ovf"),
                0x14 => defmt::write!(f, "Cnt6strt"),
                0x15 => defmt::write!(f, "Cnt6stop"),
                0x16 => defmt::write!(f, "Cnt7ovf"),
                0x17 => defmt::write!(f, "Cnt7strt"),
                0x18 => defmt::write!(f, "Cnt7stop"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u16> for IidxStat {
        #[inline(always)]
        fn from(val: u16) -> IidxStat {
            IidxStat::from_bits(val)
        }
    }
    impl From<IidxStat> for u16 {
        #[inline(always)]
        fn from(val: IidxStat) -> u16 {
            IidxStat::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct PwrenKey(u8);
    impl PwrenKey {
        pub const Key: Self = Self(0x26);
    }
    impl PwrenKey {
        pub const fn from_bits(val: u8) -> PwrenKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for PwrenKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0x26 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for PwrenKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0x26 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for PwrenKey {
        #[inline(always)]
        fn from(val: u8) -> PwrenKey {
            PwrenKey::from_bits(val)
        }
    }
    impl From<PwrenKey> for u8 {
        #[inline(always)]
        fn from(val: PwrenKey) -> u8 {
            PwrenKey::to_bits(val)
        }
    }
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
    pub struct ResetKey(u8);
    impl ResetKey {
        pub const Key: Self = Self(0xb1);
    }
    impl ResetKey {
        pub const fn from_bits(val: u8) -> ResetKey {
            Self(val & 0xff)
        }
        pub const fn to_bits(self) -> u8 {
            self.0
        }
    }
    impl core::fmt::Debug for ResetKey {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            match self.0 {
                0xb1 => f.write_str("Key"),
                other => core::write!(f, "0x{:02X}", other),
            }
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ResetKey {
        fn format(&self, f: defmt::Formatter) {
            match self.0 {
                0xb1 => defmt::write!(f, "Key"),
                other => defmt::write!(f, "0x{:02X}", other),
            }
        }
    }
    impl From<u8> for ResetKey {
        #[inline(always)]
        fn from(val: u8) -> ResetKey {
            ResetKey::from_bits(val)
        }
    }
    impl From<ResetKey> for u8 {
        #[inline(always)]
        fn from(val: ResetKey) -> u8 {
            ResetKey::to_bits(val)
        }
    }
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Soft {
        ///The peripheral will halt immediately, even if the resultant state will result in corruption if the system is restarted.
        Immediate = 0x0,
        ///The peripheral blocks the debug freeze until it has reached a boundary where it can resume without corruption.
        Delayed = 0x01,
    }
    impl Soft {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Soft {
            unsafe { core::mem::transmute(val & 0x01) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Soft {
        #[inline(always)]
        fn from(val: u8) -> Soft {
            Soft::from_bits(val)
        }
    }
    impl From<Soft> for u8 {
        #[inline(always)]
        fn from(val: Soft) -> u8 {
            Soft::to_bits(val)
        }
    }
}
