// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
///The wake-up controller. It watches for enabled interrupts while PD1 is power-gated in STOP and STANDBY, when the CPU and NVIC cannot, and hands the device back to the PMCU with the interrupt latched so the core still sees it after powering up. That needs no configuration and SLAU847 SS3.3.1.3 calls it transparent to software: these two subscriber ports are the whole programmable surface, and they let a generic event channel wake the device instead of an NVIC interrupt.
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Wuc {
    ptr: *mut u8,
}
unsafe impl Send for Wuc {}
unsafe impl Sync for Wuc {}
impl Wuc {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Subscriber Port.
    #[inline(always)]
    pub const fn fsub(
        self,
        n: usize,
    ) -> crate::common::Reg<regs::Fport, crate::common::RW> {
        assert!(n < 2usize);
        unsafe {
            crate::common::Reg::from_ptr(
                self.ptr.wrapping_add(0x0400usize + n * 4usize) as _,
            )
        }
    }
}
pub mod regs {
    ///Subscriber Configuration Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Fport(pub u32);
    impl Fport {
        ///0 = disconnected. 1-15 = connected to channelID = CHANID.
        #[must_use]
        #[inline(always)]
        pub const fn chanid(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x0f;
            val as u8
        }
        ///0 = disconnected. 1-15 = connected to channelID = CHANID.
        #[inline(always)]
        pub const fn set_chanid(&mut self, val: u8) {
            self.0 = (self.0 & !(0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize);
        }
    }
    impl Default for Fport {
        #[inline(always)]
        fn default() -> Fport {
            Fport(0)
        }
    }
    impl core::fmt::Debug for Fport {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Fport").field("chanid", &self.chanid()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Fport {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Fport {{ chanid: {=u8:?} }}", self.chanid())
        }
    }
}
