
pub(crate) static PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "ADC0",
        kind: "adc",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA27",
                signal: "0",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "1",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "3",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "7",
                pf: Some(0u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "ADC0",
            number: 4,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "ADC1",
        kind: "adc",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA17",
                signal: "2",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "3",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "8",
                pf: Some(0u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "ADC1",
            number: 5,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "AES",
        kind: "aes",
        version: None,
        pins: &[],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "AES",
            number: 28,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "CANFD0",
        kind: "canfd",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA27",
                signal: "CANRX",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA12",
                signal: "CANTX",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "CANTX",
                pf: Some(6u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "CANFD0",
            number: 6,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "CPUSS",
        kind: "cpuss",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: Some(PowerMode::Standby),
        usable_through: Some(PowerMode::Run),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "CRC",
        kind: "crc",
        version: None,
        pins: &[],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: Some(PowerMode::Standby),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "DEBUGSS",
        kind: "debugss",
        version: None,
        pins: &[
            PeripheralPin {
                pin: "PA20",
                signal: "SWCLK",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA19",
                signal: "SWDIO",
                pf: Some(2u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP0",
            number: 0,
            group_iidx: Some(2),
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "DMA",
        kind: "dma",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "DMA",
            number: 31,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Standby),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "EVENT",
        kind: "event",
        version: None,
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: None,
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "FLASHCTL",
        kind: "flashctl",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP0",
            number: 0,
            group_iidx: Some(3),
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "GPAMP",
        kind: "gpamp",
        version: None,
        pins: &[
            PeripheralPin {
                pin: "PA26",
                signal: "IN+",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "IN-",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "OUT",
                pf: Some(0u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "GPIOA",
        kind: "gpio",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA10",
                signal: "PA10",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA11",
                signal: "PA11",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA12",
                signal: "PA12",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA17",
                signal: "PA17",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "PA18",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA19",
                signal: "PA19",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA2",
                signal: "PA2",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA20",
                signal: "PA20",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "PA22",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "PA23",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "PA24",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "PA26",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA27",
                signal: "PA27",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "PA5",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "PA6",
                pf: Some(1u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "PA9",
                pf: Some(1u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP1",
            number: 1,
            group_iidx: Some(0),
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "GPIOB",
        kind: "gpio",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP1",
            number: 1,
            group_iidx: Some(1),
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "I2C0",
        kind: "i2c",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA11",
                signal: "SCL",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA10",
                signal: "SDA",
                pf: Some(4u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: Some(8usize),
        interrupt: Some(PeripheralInterrupt {
            name: "I2C0",
            number: 24,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "I2C1",
        kind: "i2c",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA17",
                signal: "SCL",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA11",
                signal: "SCL",
                pf: Some(8u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "SDA",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA10",
                signal: "SDA",
                pf: Some(8u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: Some(8usize),
        interrupt: Some(PeripheralInterrupt {
            name: "I2C1",
            number: 25,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "IOMUX",
        kind: "iomux",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: None,
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "RTC",
        kind: "rtc",
        version: Some("legacy"),
        pins: &[
            PeripheralPin {
                pin: "PA27",
                signal: "RTC_OUT",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "RTC_OUT",
                pf: Some(6u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "RTC",
            number: 30,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "SPI0",
        kind: "spi",
        version: None,
        pins: &[
            PeripheralPin {
                pin: "PA2",
                signal: "CS0",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "CS2_POCI2",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "CS3_CD_POCI3",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "PICO",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "PICO",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA10",
                signal: "POCI",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA11",
                signal: "SCLK",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA12",
                signal: "SCLK",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "SCLK",
                pf: Some(3u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: Some(4usize),
        interrupt: Some(PeripheralInterrupt {
            name: "SPI0",
            number: 9,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: Some(PowerMode::Standby),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "SPI1",
        kind: "spi",
        version: None,
        pins: &[
            PeripheralPin {
                pin: "PA26",
                signal: "CS0",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA2",
                signal: "CS0",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA27",
                signal: "CS1_POCI1",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "PICO",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA17",
                signal: "SCLK",
                pf: Some(3u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: Some(4usize),
        interrupt: Some(PeripheralInterrupt {
            name: "SPI1",
            number: 10,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: Some(PowerMode::Standby),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "SYSCTL",
        kind: "sysctl",
        version: Some("g350x_g310x_g150x_g110x"),
        pins: &[
            PeripheralPin {
                pin: "PA22",
                signal: "CLK_OUT",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA10",
                signal: "CLK_OUT",
                pf: Some(9u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "CLK_OUT",
                pf: Some(9u8),
            },
            PeripheralPin {
                pin: "PA12",
                signal: "FCC_IN",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "FCC_IN",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "HFCLKIN",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "HFXIN",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "HFXOUT",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "NRST",
                signal: "NRST",
                pf: Some(0u8),
            },
            PeripheralPin {
                pin: "PA2",
                signal: "ROSC",
                pf: Some(0u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP0",
            number: 0,
            group_iidx: Some(6),
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "TIMA0",
        kind: "tim",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA22",
                signal: "CCP0_CMPL",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "CCP0_CMPL",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "CCP1",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "CCP1",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA10",
                signal: "CCP2",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA11",
                signal: "CCP2_CMPL",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "CCP2_CMPL",
                pf: Some(8u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "CCP3",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA17",
                signal: "CCP3",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA12",
                signal: "CCP3",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "CCP3_CMPL",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "CCP3_CMPL",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "FAULT0",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "FAULT0",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "FAULT1",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA27",
                signal: "FAULT2",
                pf: Some(5u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMA0",
            number: 18,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: Some(false),
    },
    Peripheral {
        name: "TIMA1",
        kind: "tim",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA10",
                signal: "CCP0",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA17",
                signal: "CCP0",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA11",
                signal: "CCP1",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "CCP1",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "CCP1",
                pf: Some(8u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "CCP1_CMPL",
                pf: Some(8u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "FAULT0",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "FAULT0",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "FAULT1",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA27",
                signal: "FAULT2",
                pf: Some(5u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMA1",
            number: 19,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: Some(false),
    },
    Peripheral {
        name: "TIMG0",
        kind: "tim",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA12",
                signal: "CCP0",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "CCP0",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA5",
                signal: "CCP0",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "CCP1",
                pf: Some(5u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "CCP1",
                pf: Some(5u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMG0",
            number: 16,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: Some(true),
    },
    Peripheral {
        name: "TIMG12",
        kind: "tim",
        version: Some("v1"),
        pins: &[PeripheralPin {
            pin: "PA10",
            signal: "CCP0",
            pf: Some(6u8),
        }],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMG12",
            number: 21,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: Some(false),
    },
    Peripheral {
        name: "TIMG6",
        kind: "tim",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA5",
                signal: "CCP0",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "CCP1",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "CCP1",
                pf: Some(8u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMG6",
            number: 17,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: Some(false),
    },
    Peripheral {
        name: "TIMG7",
        kind: "tim",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA17",
                signal: "CCP0",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "CCP0",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "CCP0",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA2",
                signal: "CCP1",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "CCP1",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "CCP1",
                pf: Some(7u8),
            },
            PeripheralPin {
                pin: "PA27",
                signal: "CCP1",
                pf: Some(7u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMG7",
            number: 20,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: Some(false),
    },
    Peripheral {
        name: "TIMG8",
        kind: "tim",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA5",
                signal: "CCP0",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "CCP0",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "CCP0",
                pf: Some(8u8),
            },
            PeripheralPin {
                pin: "PA2",
                signal: "CCP1",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA6",
                signal: "CCP1",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA22",
                signal: "CCP1",
                pf: Some(3u8),
            },
            PeripheralPin {
                pin: "PA27",
                signal: "CCP1",
                pf: Some(4u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "TIMG8",
            number: 2,
            group_iidx: None,
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: Some(true),
    },
    Peripheral {
        name: "TRNG",
        kind: "trng",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd1,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP1",
            number: 1,
            group_iidx: Some(5),
        }),
        block_async: Some(false),
        retained_through: Some(PowerMode::Sleep),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "UART0",
        kind: "uart",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA9",
                signal: "CTS",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA11",
                signal: "RX",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA10",
                signal: "TX",
                pf: Some(2u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: Some(4usize),
        interrupt: Some(PeripheralInterrupt {
            name: "UART0",
            number: 15,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "UART1",
        kind: "uart",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA22",
                signal: "RTS",
                pf: Some(4u8),
            },
            PeripheralPin {
                pin: "PA18",
                signal: "RX",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA9",
                signal: "RX",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA17",
                signal: "TX",
                pf: Some(2u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: Some(4usize),
        interrupt: Some(PeripheralInterrupt {
            name: "UART1",
            number: 13,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "UART2",
        kind: "uart",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA22",
                signal: "RX",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "RX",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "TX",
                pf: Some(2u8),
            },
        ],
        power_domain: PowerDomain::Pd0,
        sys_fentries: Some(4usize),
        interrupt: Some(PeripheralInterrupt {
            name: "UART2",
            number: 14,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "UART3",
        kind: "uart",
        version: Some("v1"),
        pins: &[
            PeripheralPin {
                pin: "PA12",
                signal: "CTS",
                pf: Some(2u8),
            },
            PeripheralPin {
                pin: "PA23",
                signal: "CTS",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA24",
                signal: "RTS",
                pf: Some(6u8),
            },
            PeripheralPin {
                pin: "PA26",
                signal: "TX",
                pf: Some(2u8),
            },
        ],
        power_domain: PowerDomain::Pd1,
        sys_fentries: Some(4usize),
        interrupt: Some(PeripheralInterrupt {
            name: "UART3",
            number: 3,
            group_iidx: None,
        }),
        block_async: Some(true),
        retained_through: Some(PowerMode::Standby),
        usable_through: Some(PowerMode::Sleep),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "VREF",
        kind: "vref",
        version: None,
        pins: &[PeripheralPin {
            pin: "PA23",
            signal: "VREF+",
            pf: Some(0u8),
        }],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Standby),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "WUC",
        kind: "wuc",
        version: None,
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: None,
        block_async: Some(false),
        retained_through: None,
        usable_through: None,
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "WWDT0",
        kind: "wwdt",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP0",
            number: 0,
            group_iidx: Some(0),
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Stop),
        clocked_in_standby1: None,
    },
    Peripheral {
        name: "WWDT1",
        kind: "wwdt",
        version: Some("v1"),
        pins: &[],
        power_domain: PowerDomain::Pd0,
        sys_fentries: None,
        interrupt: Some(PeripheralInterrupt {
            name: "GROUP0",
            number: 0,
            group_iidx: Some(1),
        }),
        block_async: Some(false),
        retained_through: None,
        usable_through: Some(PowerMode::Stop),
        clocked_in_standby1: None,
    },
];
pub(crate) static INTERRUPTS: &[Interrupt] = &[
    Interrupt {
        name: "GROUP0",
        number: 0,
    },
    Interrupt {
        name: "GROUP1",
        number: 1,
    },
    Interrupt {
        name: "TIMG8",
        number: 2,
    },
    Interrupt {
        name: "UART3",
        number: 3,
    },
    Interrupt {
        name: "ADC0",
        number: 4,
    },
    Interrupt {
        name: "ADC1",
        number: 5,
    },
    Interrupt {
        name: "CANFD0",
        number: 6,
    },
    Interrupt {
        name: "SPI0",
        number: 9,
    },
    Interrupt {
        name: "SPI1",
        number: 10,
    },
    Interrupt {
        name: "UART1",
        number: 13,
    },
    Interrupt {
        name: "UART2",
        number: 14,
    },
    Interrupt {
        name: "UART0",
        number: 15,
    },
    Interrupt {
        name: "TIMG0",
        number: 16,
    },
    Interrupt {
        name: "TIMG6",
        number: 17,
    },
    Interrupt {
        name: "TIMA0",
        number: 18,
    },
    Interrupt {
        name: "TIMA1",
        number: 19,
    },
    Interrupt {
        name: "TIMG7",
        number: 20,
    },
    Interrupt {
        name: "TIMG12",
        number: 21,
    },
    Interrupt {
        name: "I2C0",
        number: 24,
    },
    Interrupt {
        name: "I2C1",
        number: 25,
    },
    Interrupt {
        name: "AES",
        number: 28,
    },
    Interrupt {
        name: "RTC",
        number: 30,
    },
    Interrupt {
        name: "DMA",
        number: 31,
    },
];
pub(crate) static INTERRUPT_GROUPS: &[InterruptGroup] = &[
    InterruptGroup {
        name: "GROUP0",
        number: 0,
        interrupts: &[
            GroupInterrupt {
                name: "WWDT0",
                number: 0,
            },
            GroupInterrupt {
                name: "WWDT1",
                number: 1,
            },
            GroupInterrupt {
                name: "DEBUGSS",
                number: 2,
            },
            GroupInterrupt {
                name: "FLASHCTL",
                number: 3,
            },
            GroupInterrupt {
                name: "SYSCTL",
                number: 6,
            },
        ],
    },
    InterruptGroup {
        name: "GROUP1",
        number: 1,
        interrupts: &[
            GroupInterrupt {
                name: "GPIOA",
                number: 0,
            },
            GroupInterrupt {
                name: "GPIOB",
                number: 1,
            },
            GroupInterrupt {
                name: "TRNG",
                number: 5,
            },
        ],
    },
];
pub(crate) static DMA_CHANNELS: &[DmaChannel] = &[
    DmaChannel {
        number: 0,
        full: true,
    },
    DmaChannel {
        number: 1,
        full: true,
    },
    DmaChannel {
        number: 2,
        full: true,
    },
    DmaChannel {
        number: 3,
        full: false,
    },
    DmaChannel {
        number: 4,
        full: false,
    },
    DmaChannel {
        number: 5,
        full: false,
    },
    DmaChannel {
        number: 6,
        full: false,
    },
];
pub(crate) static PINS: &[Pin] = &[
    Pin {
        pin: "PA26",
        pincm: 59u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA9",
        pincm: 20u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA10",
        pincm: 21u8,
        wakeup: Some(true),
    },
    Pin {
        pin: "PA11",
        pincm: 22u8,
        wakeup: Some(true),
    },
    Pin {
        pin: "PA12",
        pincm: 34u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA17",
        pincm: 39u8,
        wakeup: Some(true),
    },
    Pin {
        pin: "PA18",
        pincm: 40u8,
        wakeup: Some(true),
    },
    Pin {
        pin: "PA19",
        pincm: 41u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA20",
        pincm: 42u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA22",
        pincm: 47u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA23",
        pincm: 53u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA27",
        pincm: 60u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA24",
        pincm: 54u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA2",
        pincm: 7u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA5",
        pincm: 10u8,
        wakeup: Some(false),
    },
    Pin {
        pin: "PA6",
        pincm: 11u8,
        wakeup: Some(false),
    },
];
