// This file is autogenerated by mspm0-metapac-gen: do not edit by hand.

include!("../metadata_0053.rs");
static MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "FLASH",
        kind: MemoryKind::Flash,
        address: 0,
        size: 65536,
        retained_through: PowerMode::Shutdown,
    },
    MemoryRegion {
        name: "RAM",
        kind: MemoryKind::Ram,
        address: 536870912,
        size: 4096,
        retained_through: PowerMode::Standby,
    },
];
pub static METADATA: Metadata = Metadata {
    name: "mspm0l1106rge",
    family: "mspm0l110x",
    memory: MEMORY,
    peripherals: PERIPHERALS,
    pins: PINS,
    nvic_priority_bits: 2,
    interrupts: INTERRUPTS,
    interrupt_groups: INTERRUPT_GROUPS,
    dma_channels: DMA_CHANNELS,
    adc_memctl: 4,
    adc_vrsel: 5,
    max_mclk_hz: 32000000,
    max_ulpclk_hz: 32000000,
    backup_domain: false,
};
